### ISSUE TITLE
not response in osx 10.11, iterm2, vim7.4. how could i debug it?

### ISSUE THREAD

**Issue by gfgkmn** [jpalardy/vim-slime#104]
hi everyone . 

recently i found vim-slime, this plugin is awesome. and i was so happy to send code to ipython in tmux, it just like an IDE. 

but now when i send text to ipython, the vim will be stuck,  Every button-down will echo in vim's command line, and tmux wouldn't accept lines. 
[pic1](https://s31.postimg.org/lmnow3asr/Vim_i_Term2_Today_at_15_42_11.png)
[pic2](https://s31.postimg.org/l1dxemy9n/Vim_i_Term2_Today_at_15_42_52.png)
i don't know how to debug this error, and i don't know what's happening. 

this is my vim's info and plugins list:
Plugin 'gmarik/Vundle.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'vim-scripts/fencview.vim'
Plugin 'vim-scripts/camelcasemotion'
Plugin 'vim-scripts/LargeFile'
Plugin 'jiangmiao/auto-pairs'
Plugin 'SirVer/ultisnips'
Plugin 'mbbill/undotree'
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'Valloric/YouCompleteMe'
Plugin 'honza/vim-snippets'
Plugin 'kana/vim-textobj-user'
Plugin 'bps/vim-textobj-python'
Plugin 'kana/vim-textobj-indent'
Plugin 'kana/vim-textobj-line'
Plugin 'kana/vim-textobj-entire'
Plugin 'sgur/vim-textobj-parameter'
Plugin 'glts/vim-textobj-comment'
Plugin 'Julian/vim-textobj-variable-segment'
Plugin 'rizzatti/dash.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'terryma/vim-expand-region'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-scripts/EasyGrep'
Plugin 'vim-scripts/TaskList.vim'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'raymond-w-ko/vim-niji'
Plugin 'scrooloose/syntastic'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-fireplace'
Plugin 'derekwyatt/vim-scala'
Plugin 'ktvoelker/sbt-vim'
Plugin 'vim-scripts/CCTree'
Plugin 'vim-scripts/a.vim'

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 20 2016 11:48:50)
MacOS X (unix) version
Included patches: 1-1831
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+channel         -gettext         +netbeans_intg   +timers
+cindent         -hangul_input    +odbeditor       +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +transparency
+cmdline_compl   +job             +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.11/Frameworks -L/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -pagezero_size 10000 -image_base 100000000 -L/usr/local/lib -lluajit-5.1 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

**Comment by jpalardy** [comment]
Hi there, did you recently upgrade to tmux 2.2?

Can you try to upgrade the vim-slime bundle? There's a [commit](https://github.com/jpalardy/vim-slime/commit/befea664cdb93d9756768f0063514919cccc67dd) to work around the problem.

**Comment by gfgkmn** [comment]
Yeah, my tmux version is 2.2. cause my tmux is installed in brew, and i always keep it upgraded. 

i have upgrade vim-slime bundle, and it works ! 

thank you very much. 

I have review the commit, so the reason is tmux2.2 change its communication, so vim-slime now use buffer .slime-paste to save content? 

I really appreciate.

**Comment by jpalardy** [comment]
Glad to hear it :-)
