### ISSUE TITLE
question about output

### ISSUE THREAD

**Issue by githubfun** [jpalardy/vim-slime#113]
I sent the following code to ipython with vim-slime, Could anyone explain why the value of a is not echoed? 

```
In [1]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:a=1
:b=2
:a
:b
:--
Out[1]: 2

```

**Comment by jpalardy** [comment]
What's the behavior if you manually paste the same input? (outside of vim and slime)

**Comment by githubfun** [comment]
manual paste would be like this
```
In [9]: a=1

In [10]: b=2

In [11]: a
Out[11]: 1

In [12]: b
Out[12]: 2

```

**Comment by jpalardy** [comment]
A manual %cpaste, I mean.

**Comment by githubfun** [comment]
looks like that's how %cpaste works, that explains it, thanks! so if I need see results of multiple lines I'll have to send them individually, just an inconvenience.

**Comment by jpalardy** [comment]
good to know :-)
