### ISSUE TITLE
how to run SlimeConfig with vimscript?

### ISSUE THREAD

**Issue by Alok** [jpalardy/vim-slime#122]
I want to be able to do something to the effect of this pseudocode:

```
SlimeConfig:  b:terminal_job_id
```

I'm using a function to essentially spawn a neovim terminal, open ipython, and then run `SlimeConfig`. The issue is in automatically running `SlimeConfig` and feeding it the jobid of the current terminal.

**Comment by jpalardy** [comment]
In practice, it would be as easy as:

    let b:slime_config = {"jobid": b:terminal_job_id}

But the first variable (slime_config) is a buffer variable for the buffer sending text, while the second variable (terminal_job_id) is a buffer variable for the buffer receiving text. Without seeing the function you're using to spawn, it's hard to debug this.

**Comment by Alok** [comment]
I use this autocmd:

```vim
augroup Terminal
  autocmd!
  autocmd TermOpen * let g:last_terminal_job_id = b:terminal_job_id
augroup END
```

to get the jobid.

Then I run this function:

```vim
function! functions#slime#slime_config() abort
    " split window and open a terminal
    vsplit
    enew
    call termopen('ipython3')

    let g:slime_default_config = g:last_terminal_job_id

    " go to previous split
    execute 'normal!' . "\<c-w>p"
endfunction
```

**Comment by jpalardy** [comment]
As I understand it, this would work the _**first time**_, if you hadn't run vim-slime before spawning for the first time.

If you remove the `let g:slime_default_config` line (or comment it out) and use:

    let b:slime_config = {"jobid": b:terminal_job_id}

_after_ the "go to previous split" execute statement, I think it would work.

The logic being:

1. spawn a shell, capture the job id
2. return to the text buffer
3. set the slime config
4. at this point, everything is setup correctly, for that buffer, to call vim-slime

Let me know how that goes.

**Comment by Alok** [comment]
This code worked properly. I tweaked yours a bit to make it work correctly, and added GoldenView's split function so I don't have to care about vertical/horizontal splits.

```vim
function! functions#slime#slime_config(cmd) abort
    " Split window nicely and open a terminal.
    call GoldenView#Split()
    " Spawn shell.
    " `terminal` will put you in insert mode, so don't use it.
    enew | call termopen(a:cmd)
    let l:repl_job_id = b:terminal_job_id
    " Go to previous split.
    execute 'normal!' . "\<c-w>p"
    " let buffer's REPL be the one we just entered.
    let b:slime_config = {'jobid': l:repl_job_id}
endfunction
```

**Comment by jpalardy** [comment]
Looking good.

**Comment by Alok** [comment]
This is actually *really* convenient. You may want to consider adding something like this, but making it REPL-agnostic. Something like `SlimeSpawnREPL`.
