### ISSUE TITLE
Indentation in ipython messed up

### ISSUE THREAD

**Issue by Kareeeeem** [jpalardy/vim-slime#125]
Get an indentation error from ipython

offending test code
```
def foo(n):
    for i in range(n):
        if i == 5:
            break
    return i
```

ipython error
```
In [3]: def foo(n):
   ...:         for i in range(n):
   ...:                 if i == 5:
   ...:                         break
   ...:             return i
  File "<ipython-input-3-95cc693453b1>", line 5
    return i
            ^
IndentationError: unindent does not match any outer indentation level
```
Made a screenshot aswell

http://imgur.com/a/FAlon

**Comment by jpalardy** [comment]
Hi there,

What's your situation based on [this](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python)?

Which version of ipython are you using? Is your `g:slime_python_ipython` variable set or not?

**Comment by Kareeeeem** [comment]
ipython version 5.1.0

g:slime_python_ipython is set to 1.

**Comment by Kareeeeem** [comment]
Problem solved. I was lazy loading slime on running the config or send commands. I took out the lazy loading and it works now.

offending lines in vimrc. 
```
  150 Plug 'jpalardy/vim-slime',
  151             \ {'on': [
  152             \ '<Plug>SlimeConfig',
  153             \ '<Plug>SlimeParagraphSend',
  154             \ '<Plug>SlimeRegionSend']}
```

**Comment by jpalardy** [comment]
ok, thanks for letting me know.
