### ISSUE TITLE
Only the first command is pasted to ipython

### ISSUE THREAD

**Issue by randomizedthinking** [jpalardy/vim-slime#126]
When using slime to paste commands to ipython (5.1.0), only the first command is pasted to the destination. For instance, given the following simple code, when press `Ctrl-C Ctrl-C` in nvim,

    x = 1
    y = 2

Only `x = 1` showed up in the ipython session. On the other hand, I can verify that all texts are sent to the terminal correctly (using a bash shell), yet only the first command takes effect somehow if the target is a ipython terminal. Not sure whether it is a slime or ipython issue. Any ideas? Thanks!

  - neovim: 0.2.0
  - vim-slime: most update version on github
  - ipython3: 5.1.0

**Comment by jpalardy** [comment]
Hi there,

What's your situation based on [this](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python)?

Is your g:slime_python_ipython variable set or not?

**Comment by randomizedthinking** [comment]
Now, it works. Thanks for pointing out the link.

**Comment by jpalardy** [comment]
This isn't the first time this happens :-)

How do you think it could have been clearer?

**Comment by randomizedthinking** [comment]
Thanks for asking. I think it would be great to have such information in the vim-slime help doc. People usually look at it for help first.

**Comment by jpalardy** [comment]
There's a duality here between the documentation in the README (on github) and the offline documentation in `doc/`.

While patches have been coming in, the accompanying documentation corrections have not. As such, there's a drift in "where" and "whether" things are documented.

Would it be unreasonable for the offline documentation to _only_ point to the online one? On the other hand, an effort would have to be made to sync the documentation...

Would you be willing to send me a documentation patch for how/where you would have wanted to see help?
