### ISSUE TITLE
Paste in IPython v3.2.1

### ISSUE THREAD

**Issue by zhelezov** [jpalardy/vim-slime#129]
C-c, c
Result: pasted block gets assigned to '-'
Expected: pasted block gets executed

Works as expected after changing ftplugin/python/slime.vim:4
from
`    return ["%cpaste -q\n", a:text, "--\n"]`
to
`    return ["%cpaste\n", a:text, "--\n"]`

Might be a bug in IPython assuming the dash in '-q' is the variable to assign to. Whatever the bug the above change fixes it. Please have a look into it.

**Comment by jpalardy** [comment]
This is a recent change.

@fluffactually can you explain why you added `-q` and under what cases it would or wouldn't work?

Specifically, we're talking about 602172878abab17997bb56381e35a57acd3c39df

**Comment by fluffactually** [comment]
Purely cosmetic change, adding this silences the
`Pasting code; enter '--' alone on the line to stop or use Ctrl-D.``
and
`--`
lines above and below the selected text.

I haven't tested it with older versions of IPython (I believe the 5.x versions fixed a lot of pasting functionality). It should be removed if you want to maintain compatibility with older versions. Form follows function and all that... Or just update IPython if possible (newer versions are much prettier)

**Comment by jpalardy** [comment]
I can imagine a few solutions to this problem:

- revert the `-q` flag to remain backward compatible
- add some variable (`g:slime_python_cpaste`) that's user-customizable
- urge people to upgrade

thoughts?

**Comment by zhelezov** [comment]
Another option would be to test which version of IPython is available on the system if you can figure out the buggy ones. I've upgraded mine since to v5.3.0 and I agree that the output is less cluttered with `-q`. Compatibility is important though. Debian stable is stuck with 2.3.0 at the moment, Fedora with 3.2.1. A lot of users including me wouldn't upgrade if they are not having any issues with the current one. Simplifies package management...

**Comment by jpalardy** [comment]
@zhelezov want to send me a PR? :-)

**Comment by zhelezov** [comment]
On a second thought I decided I shouldn't have posted the bug here in the first place. Bloating vim-slime's code to fix the misbehaviour of a separate component is not the answer to the issue. So I opened a bug against IPython on Red Hat Bugzilla: [1427842](https://bugzilla.redhat.com/show_bug.cgi?id=1427842)

We can get rid of this issue now.

**Comment by jpalardy** [comment]
Ok, re-open another issue if needed.
