### ISSUE TITLE
ipython 5.3.0 indentation problems

### ISSUE THREAD

**Issue by ssbothwell** [jpalardy/vim-slime#131]
Hi. I'm really sorry if this is a duplicate, I saw similar posts but everyone seems to have their problem solved with "let g:slime_python_ipython = 1"

Some code is pasting into the ipython correctly but a lot isnt. For example:

```
def bubbleSort(arr):
    # Loop through list once per element
    for _ in range ( 0, len(arr)):
        for i in range(0, len(arr)-1):
            # compare and swap adjacent elements
            if arr[i] > arr[i+1]:
                arr[i], arr[i+1] = arr[i+1], arr[i]
    return arr
```

The final return is indented in an extra 13 spaces in ipython.

I tried "let g:slime_python_ipython = 1" with no change in results.

Vim is set to use soft tabs. Pasting this code block with the system clipboard works fine. 

I'm using tmux 2.2 and ipython 5.3.0 in MacOs 10.12.3.

**Comment by jpalardy** [comment]
Does it work with all spaces?

**Comment by ssbothwell** [comment]
I think soft-tabs means tabs are replaced by spaces? In any case, I tried removing the indentation and replacing it with all spaces and the same result.

**Comment by jpalardy** [comment]
In iPython, you see the `cpaste`? (i.e. it's going through the correct branch in the code)

**Comment by ssbothwell** [comment]
Oh interesting. If i do %paste then the code is pasted correctly.

**Comment by jpalardy** [comment]
We're good, then?

**Comment by ssbothwell** [comment]
Well I can use %paste from within ipython but then I am exiting vim to paste the code into ipython.

**Comment by jpalardy** [comment]
If `let g:slime_python_ipython = 1` is correctly set, I don't see how this would happen.

**Comment by jpalardy** [comment]
Can you give me a configuration which reproduces this?

**Comment by ssbothwell** [comment]
Do you want a copy of my full vimrc?
https://gist.github.com/ssbothwell/6a98a14a042920df60bcaab128138491

**Comment by jpalardy** [comment]
If you could trim it down to the bare minimum `.vimrc` with just vim-slime as a plugin -- and confirm the problem is still there -- that would be great.

**Comment by ssbothwell** [comment]
Yes I'll do that after work today. Sorry about my slow response time with this.

**Comment by ssbothwell** [comment]
Okay, sorry about the delay. Everything is commented out from my .vimrc other then the following lines:

```
let g:slime_target = "tmux"                                                        
let g:slime_default_config = {"socket_name": split($TMUX, ",")[1], "target_pane": ":.1"}                                                                              
let g:slime_python_ipython = 1                                                     
```

As an example, I'm getting an indent error on the return call in the bubbleSort() function in the following py file: https://github.com/ssbothwell/Algorithms/blob/master/sorting/bubbleSort.py

It gets pasted into ipython as follows:
```
In [7]: def bubbleSort(arr):
   ...:         # Loop through list once per element
   ...:         for _ in range ( 0, len(arr)):
   ...:                 for i in range(0, len(arr)-1):
   ...:                         # compare and swap adjacent elements
   ...:                         if arr[i] > arr[i+1]:
   ...:                                 arr[i], arr[i+1] = arr[i+1], arr
   ...: [i]
   ...:                     return arr
  File "<ipython-input-7-1f18921509cd>", line 8
    return arr
              ^
IndentationError: unindent does not match any outer indentation level
```
Looks like the line prior to the return is getting wrapped funny.

I'm using vim 8.0, tmux 2.2, python 2.7.13, and ipython 5.3.0

**Comment by jpalardy** [comment]
Interesting.

Are you indenting with tabs or spaces?

Could you try 2 spaces and see if that changes anything?

**Comment by ssbothwell** [comment]
I use 4 spaces for indent. 

I changed the function to use 2 spaces for indent and it is pasting correctly.

**Comment by jpalardy** [comment]
hmmm… so weird!

Let me think about this.

**Comment by jpalardy** [comment]
def bubbleSort(arr):
    # Loop through list once per element
    for _ in range ( 0, len(arr)):
        for i in range(0, len(arr)-1):
            # compare and swap adjacent elements
            if arr[i] <= arr[i+1]:
                continue
            arr[i], arr[i+1] = arr[i+1], arr[i]
    return arr

How about this? ^

It's just to test what happens if we try to fit under a certain text width.

**Comment by ssbothwell** [comment]
I copied that into vim, then pasted into ipython and it worked! Ipython even corrected the indentation. 

The longest line in the non-working codeblock is 51 characters and your modified code's longest line is 43 characters.

**Comment by jpalardy** [comment]
That doesn't sound like a slime problem :-/

> ipython even corrected the indentation

What line needed to be fixed?

In your `HOME` directory, does the `.slime_paste` file always contain the right content, byte-for-byte, for all the permutations (the ones that work and the ones that don't)?

**Comment by ilyakopy** [comment]
Try turning off canonical mode on the terminal where python is running by typing `stty -cbreak` into shell. 

I'm having no trouble pasting Python functions of arbitrary length and complexity into the terminal when I turn off canonical mode.

**Comment by jpalardy** [comment]
@ssbothwell did @ilyakopy's tip help?

**Comment by ssbothwell** [comment]
Unfortunately no it didn't change anything. I just noticed that when I paste into ipython with vimslime the number of spaces gets changed. Heres a couple examples:

Two space indent in Vim:
```
def bubbleSort(arr: List[Ord]) -> List[Ord]:
  # Loop through list once per element
  for _ in range(0, len(arr)):
    for i in range(0, len(arr)-1):
      # compare and swap adjacent elements
      if arr[i] > arr[i+1]:
        arr[i], arr[i+1] = arr[i+1], arr[i]
  return arr
```

IPython result:
```
In [10]: def bubbleSort(arr: List[Ord]) -> List[Ord]:
    ...:       # Loop through list once per element
    ...:       for _ in range(0, len(arr)):
    ...:             for i in range(0, len(arr)-1):
    ...:                   # compare and swap adjacent elements
    ...:                   if arr[i] > arr[i+1]:
    ...:                         arr[i], arr[i+1] = arr[i+1], arr[i]
    ...:                   return arr
    ...:
```
All the spaces got doubled, except the return which got indented all the way into the second for loop (valid indent level but breaks the function).

4 Space indent in Vim:
```
def bubbleSort(arr: List[Ord]) -> List[Ord]:
    # Loop through list once per element
    for _ in range(0, len(arr)):
        for i in range(0, len(arr)-1):
            # compare and swap adjacent elements
            if arr[i] > arr[i+1]:
                arr[i], arr[i+1] = arr[i+1], arr[i]
    return arr
```
Ipython result:
```
In [10]: def bubbleSort(arr: List[Ord]) -> List[Ord]:
    ...:         # Loop through list once per element
    ...:         for _ in range(0, len(arr)):
    ...:                 for i in range(0, len(arr)-1):
    ...:                         # compare and swap adjacent elements
    ...:                         if arr[i] > arr[i+1]:
    ...:                                 arr[i], arr[i+1] = arr[i+1], arr[i]
    ...:                     return arr
  File "<ipython-input-10-1bb47e06bb86>", line 8
    return arr
              ^
IndentationError: unindent does not match any outer indentation level
```
This time all the spaces got doubled except the return line which had 14 spaces added to it putting it at an invalid indent level.

**Comment by jpalardy** [comment]
Old issue, re-open if needed.

**Comment by RobertM314** [comment]
On the off chance that someone else stumbles across this, in my case it was a problem with the autoindent in Ipython.

This can be toggled for an individual session by using the %autoindent magic in ipython. 

>  Autoindent is ON by default, but it can cause problems with the pasting of multi-line indented code (the pasted code gets re-indented on each line). A magic function %autoindent allows you to toggle it on/off at runtime. You can also disable it permanently on in your ipython_config.py file (set TerminalInteractiveShell.autoindent=False).
 If you want to paste multiple lines in the terminal, it is recommended that you use %paste.

**Comment by lispercat** [comment]
I am having this issue in neovim v0.8.1 using neovim terminal
Python 3.11.1.
Enabling let g:slime_python_ipython = 1 doesn't work because jypiter-console responds:
"UsageError: Line magic function `%cpaste` not found"

Same as trying to toggle  %autoindent resluts in:
UsageError: Line magic function `%autoindent` not found.
