### ISSUE TITLE
Problem with <SNR>60_SlimeSendOp[19]..<SNR>60_SlimeSend:

### ISSUE THREAD

**Issue by Ethefor** [jpalardy/vim-slime#132]
When I set in my .vimrc:
```
let b:slime_default_config = {"sessionname": "python", "windowname": "bash"}  
let g:slime_dont_ask_default = 1  
```
And I try to run C-c C-c I've got following errors:
```
Error in function <SNR>60_SlimeSendOp[19]..<SNR>60_SlimeSend:
row    8:
E121: Unset variable: b:slime_config
Error in function <SNR>60_SlimeSendOp[19]..<SNR>60_SlimeSend:
row    8:
E116: Too many arguments for function <SNR>60_SlimeDispatch
```

**Comment by jpalardy** [comment]
I don't think you can set `b:` variables from `.vimrc`…

Try it as:

    let b:slime_default_config = {"sessionname": "python", "windowname": "bash"}  

Or set the `b:` variable from Python's ftplugin config.

Let me know.

**Comment by jpalardy** [comment]
Update? ^

**Comment by jpalardy** [comment]
Closing, re-open if not solved.

**Comment by Ethefor** [comment]
Thank you for your help, and I am sorry for not replying quickly... But I don't know what is "b: variables" (I am not vim expert yet). I just want to do this, what is written in _Advanced configuration in README_:
> 
> If you want vim-slime to prefill the prompt answers, you can set a default configuration:
> ```
> " screen:
> let b:slime_default_config = {"sessionname": "xxx", "windowname": "0"}
> 
> " tmux:
> let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}
> ```
> If you want vim-slime to bypass the prompt and use the specified default configuration options, set the 
> g:slime_dont_ask_default option:
> 
> ```
> let g:slime_dont_ask_default = 1
> ```

I use screen, and I want to make this settings permanent so I put this in my .vimrc. But this unfortunately doesn't work. What am I missing?

**Comment by jpalardy** [comment]
Hmmm… (!) I think the README is wrong. It should be `g:slime…` for both:

    " screen:
    let g:slime_default_config = {"sessionname": "xxx", "windowname": "0"}

    " tmux:
    let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}

Can you confirm?

**Comment by Ethefor** [comment]
Yes! Now it works as expected :) Thank you very much! :)

**Comment by jpalardy** [comment]
That's good news -- I'll fix the doc.
