### ISSUE TITLE
Explore possibility of using Vim 8's async process support when dispatching messages

### ISSUE THREAD

**Issue by ethagnawl** [jpalardy/vim-slime#138]
Sending text from vim to Tmux (in my case) _can_ take ~3 seconds and the editor is blocked during that time. It'd be great if vim-slime could (conditionally, for users who are using >= Vim 8) take advantage of the Vim's new async API when dispatching text from vim to Tmux/Screen/etc.

Admittedly, I haven't looked very deeply into 1) whether or not this is possible or 2) how much effort would be involved in implementing it, but I wanted to make a note and potentially get a conversation started.

**Comment by jpalardy** [comment]
Whoah… ≈3 seconds?

I'd like to understand in what circumstances that happen. For my own use (admittedly short snippets of text), it's always been instant.

Also: was it always like that or did it change? (different versions of vim, etc)

**Comment by ethagnawl** [comment]
> I'd like to understand in what circumstances that happen. For my own use (admittedly short snippets of text), it's always been instant.

This issue applies in all circumstances (all REPLs, Bash, etc.) and to all snippets (length doesn't have any effect).

It's always been this way, I've just never been annoyed enough by it to raise an issue. 

Environment: 
- Debian 8.8
- Tmux 1.9
- Vim 8.0.1-606

**Comment by jpalardy** [comment]
Let's be clear: I'm not trying to say that your problem doesn't exist. I'm just trying to find the combination of things that conspires to make it happen.

Ideas:

* tmux vs screen
* use of `g:slime_paste_file` or not
* use of vim vs not

You say the last point doesn't apply. You've sent content of files into tmux using only a terminal? (and you've seen a 3 second delay then?)

**Comment by ethagnawl** [comment]
> Let's be clear: I'm not trying to say that your problem doesn't exist. 

I wasn't getting that impression :)

> Ideas:

- use of g:slime_paste_file or not
  - no difference
- use of vim vs not
  - `tmux send-keys -t right 'hi'` appears immediately
- screen 
  - I will try using Screen and/or upgrading Tmux when I find a few minutes and follow-up with the results

> You've sent content of files into tmux using only a terminal? (and you've seen a 3 second delay then?)

The use case I was outlining was sending text from Vim into Bash - as opposed to a running REPL (which could potentially add overhead).

**Comment by ethagnawl** [comment]
> I will try ... upgrading Tmux, disabling other Vim plugins, etc. when I find a few minutes and follow-up with the results

I've upgraded to Tmux 2.5 and disabled every other Vim plugin and still see the multi-second delay.

**Comment by jpalardy** [comment]
My last hope: did you try screen?

**Comment by ethagnawl** [comment]
I just tried Screen and also using a different terminal (Terminator) and saw the same behavior.

**Comment by jpalardy** [comment]
I don't know if you would be open to doing some screen sharing on Google Hangout or Skype?

Otherwise, I'm not sure what's next? … A virtual machine with Debian 8.8 to try to reproduce?

**Comment by ethagnawl** [comment]
I wouldn't be opposed, but let's hold off for a few more days.

I was planning to do a clean install of Debian Stretch (on a new SSD, so this problematic environment will persist) when it's released later this week and I'm curious to see if the issue will be present there, too.

To take a step back and revisit my initial question, though: would you consider accepting a PR which - conditionally - makes use of the new async job feature?

**Comment by jpalardy** [comment]
You could say that the scope of `vim-slime` has grown over time. A lot of people helped and contributed -- good thing too because my vimscript is so-so at best.

If it were any other language, I would refactor the code: one separate file for each concerns (tmux, screen, …). The same would go for "async job" … it would be great as a plugin, but I don't know what it will look like _weaved_ into the current code base.

I'm not against it in principle. But I would have to contemplate the impact once I have a PR to look at.

**Comment by jpalardy** [comment]
Old issue, re-open if needed.

**Comment by ethagnawl** [comment]
Just circling back to this in case anyone else is seeing similar issues. I believe that in my case this lag was the result of having `set shellcmdflag=-ic` in my .vimrc.

**Comment by jpalardy** [comment]
Thanks for posting ^
