### ISSUE TITLE
Cannot send text to another pane

### ISSUE THREAD

**Issue by sdeleon28** [jpalardy/vim-slime#141]
I have a tmux session with multiple windows, and multiple panes in it. If I enter some text with an `i` in front of it, like `i1+1;` (and do `:SlimeSendCurrentLine`) it goes into insert mode and pastes `1+1;` in. So far so good (it can clearly send text to the same pane I'm in, which is not super useful but proves that it works).

What I can't accomplish is sending `1+1;` to a different pane. I've tried setting `"target_pane"` to `:.2` (second pane in this window), and I've even tried with a fully qualified target string: `"session_name:5.2"`. No text shows up in the target pane.

This is the slime related part of my `.vimrc`:

```
Plug 'jpalardy/vim-slime'
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": ":"}
```

**Comment by sdeleon28** [comment]
I found out I could fix this by using `:.+1` as the target pane

**Comment by jpalardy** [comment]
I use the `TMUX_PANE` environment variable to find out a pane's identifier: `%7`, for example.

I added a [binding](https://github.com/jpalardy/dotfiles/blob/master/tmux.conf#L12) in tmux under `c-a, j`.
