### ISSUE TITLE
Need sleep while sending pieces.

### ISSUE THREAD

**Issue by fx-kirin** [jpalardy/vim-slime#142]
When I use it to execute multiline commands with ipython and tmux, the first time execution stops after 'paste' command executed. It seems the commands after `paste` aren't properly received. From the second time on, it works properly.

So I think sleep should be used between pieces like the code below. Then the problem was fixed.

```
function! s:SlimeSend(text)
  call s:SlimeGetConfig()

  " this used to return a string, but some receivers (coffee-script)
  " will flush the rest of the buffer given a special sequence (ctrl-v)
  " so we, possibly, send many strings -- but probably just one
  let pieces = s:_EscapeText(a:text)
  for piece in pieces
    call s:SlimeDispatch('Send', b:slime_config, piece)
    sleep 100m
  endfor
endfunction

```

Thanks.

**Comment by jpalardy** [comment]
Interesting.

This could be a global config, like `g:slime_dispatch_pause`
