### ISSUE TITLE
unable to send to tmux

### ISSUE THREAD

**Issue by jpmorris** [jpalardy/vim-slime#143]
vim: 8.0.586
libevent: 2.1.8
ncurses: 6.0
tmux: 2.5

I can't for the life of me get this plugin to work.  I CAN manually send keys to my tmux session using 'tmux send-keys', but other than that the very simple case of sending to default:0 (which works on my laptop), doesn't work for me.  I should note that this is on a system that I have no root access to, so I've had to manually compile libevent/ncurses/tmux (so maybe the problem lies there).  Is there a way to debug the process?  What is the shell command that this plugin executes to try and send to tmux?  (My .slilme_paste file does include the selected text that was executed too.)

**Comment by jpalardy** [comment]
Hi there,

Most of the relevant action happens [here](https://github.com/jpalardy/vim-slime/blob/master/plugin/slime.vim#L64-L65): a combination of `load-buffer` and `paste-buffer`.

If you can't get it to work from the command-line, it won't work from the plugin (the plugin shells out).

You can also lean on the `TMUX_PANE` environment variable as a non-ambiguous target.

Let me know how that goes.

**Comment by jpmorris** [comment]
Thanks for your reply.  Sorry I'm kind of vimscript stupid.  I saw those lines but didn't know what to do with them.  Is it 'tmux paste-buffer -d -t'.....then?  Not sure I can make sense of all this buffer/window/pane/socket stuff

**Comment by jpalardy** [comment]
No problem, here's a recipe:

    $ echo date > cmd             # creates a file containing the word "date"
    $ tmux load-buffer cmd        # puts the file's content in the tmux buffer
    $ tmux paste-buffer -t %198   # pastes the buffer into a pane

but you'll have to change `%198` by the value of `echo $TMUX_PANE` running inside tmux.

**Comment by jpmorris** [comment]
Thanks for your help. I was able to successfully send 'date' to my tmux window using pane '%0' and your code above  Yet if I simply run vim type 'date' press c-c and select 'default' and ':' (or %0) to that same session it doesnt work.  I should mention that I have two separate putty terminals running (though the putty session I run vim on can see the tmux session with 'tmux ls', and it DOES work with screen). I've tried making my vimrc the bare minimum but cant for the life of me send anything to that tmux session.   Do you have  other suggestions on how I could debug this further?  Thanks again for your help.

**Comment by jpalardy** [comment]
Here's something to try:

- repeat the experiment from above and confirm everything works (with the right TMUX_PANE)
- modify the plugin's code to skip the socket, replacing line 59 with:

    return system("tmux " . a:args)

If it works when you do it manually, there's no reason it wouldn't work from vim… we'll tweak until it does :-)

**Comment by jpmorris** [comment]
Sorry, but still no joy.  My socket is /tmp/tmux-54870/default,74782,0  .  It works from the command line like above, but with 'tmux socket name or absolute path' "default" and "tmux target name" as %0 (same as the test above) (or ":") it still doesn't send with the code change you mentioned.  Thanks again for your help.

```
function! s:TmuxCommand(config, args)
  let l:socket = a:config["socket_name"]
  " For an absolute path to the socket, use tmux -S.
  " For a relative path to the socket in tmux's temporary directory, use tmux -L.
  " Case sensitivity does not matter here, but let's follow good practice.
  " TODO: Make this cross-platform. Windows supports tmux as of mid-2016.
  let l:socket_option = l:socket[0] ==? "/" ? "-S" : "-L"
  "return system("tmux " . l:socket_option . " " . shellescape(l:socket) . " " . a:args)
  return system("tmux ".a:args)
endfunction
```

**Comment by jpalardy** [comment]
I don't have any more ideas.

Let me know if you find a solution.

**Comment by jpmorris** [comment]
Will do. It might be something particular to my setup or my compile flags for vim or one of its dependencies. Thanks so much for your help.

**Comment by jpalardy** [comment]
Sure thing.

Re-open if I can help.

**Comment by Ayutthaya** [comment]
I had exactly the same weird symptoms. This was due to the fact that tmux was an alias to the actual tmux path. Changing 'tmux' by the path to the actual tmux fixed the problem. Maybe this will help someone.

**Comment by Bragueton-Fitz** [comment]
Just to explain what "_changing 'tmux' by the actual tmux fixed the problem_" means:

In the file vim-slime/autoload/slime.vim of your installation:
Replace the line 77:
`
return system("tmux " . l:socket_option . " " . shellescape(l:socket) . " " . a:args)
`
by 
`
return system("YOUR_FULL_TMUX_PATH " . l:socket_option . " " . shellescape(l:socket) . " " . a:args)
`
where YOUR_FULL_TMUX_PATH is the output of `which tmux`.
