### ISSUE TITLE
Garbled text when sending text to R

### ISSUE THREAD

**Issue by ilyakopy** [jpalardy/vim-slime#144]
Hi,
I am using your package with Vim 8.0 and Tmux 2.5.

When I use SlimeRegionSend with VIM visual mode to send any commands over 15 lines in length to R, I get garbled text (usually several letters repeated over and over again interspersed by spaces) and `Error: unexpected symbol in`. Obviously, this prevents me from sending functions over to the R interpreter. The text is perfectly displayed in ~/.slime_paste file

Please let me know if you have any ideas about how to fix this.

Thanks.

**Comment by jpalardy** [comment]
Interesting… I primarily use vim-slime w/ R and I haven't seen this problem.

Could you check the `$HOME/.slime_paste` file and check that it contains _everything_ you're trying to paste. (if it doesn't, then the problem is with vim-slime itself … otherwise, it might be tmux related)

Also, do you think you can post a screenshot of the problem? (if you think that might help)

**Comment by ilyakopy** [comment]
Sure! Below is an image of me trying paste a function into an R interpreter.

Yes! Slime paste is exactly as correct.
<img width="657" alt="screen shot 2017-07-05 at 11 32 11 pm" src="https://user-images.githubusercontent.com/1012258/27894479-52034b76-61da-11e7-8f13-a01d4155de5d.png">

**Comment by ilyakopy** [comment]
Are you using Tmux? Which OS?

**Comment by jpalardy** [comment]
Whoah… that doesn't look good at all.

my setup:

* MacOS
* tmux 2.5
* vim 8

**Comment by ilyakopy** [comment]
Same here. Mac OS X Sierra?

**Comment by ilyakopy** [comment]
I think we're going wrong somewhere here
`call s:TmuxCommand(a:config, "load-buffer " . g:slime_paste_file)
 call s:TmuxCommand(a:config, "paste-buffer -d -t " . shellescape(a:config["target_pane"]))`

Any ideas about how to diagnose/fix?

**Comment by jpalardy** [comment]
Did you check the slime_paste_file?

**Comment by ilyakopy** [comment]
Yes. It contains EVERYTHING I'm trying to paste.

**Comment by ilyakopy** [comment]
Here's what I get:
<img width="669" alt="screen shot 2017-07-06 at 12 13 40 am" src="https://user-images.githubusercontent.com/1012258/27895323-fdd9b0ca-61df-11e7-820f-50cc8c75e7c0.png">

**Comment by jpalardy** [comment]
Hmmm… so tmux or R, rather than vim-slime.

How large is the slime_paste file?

You might want to experiment with "number of lines" or "number of bytes" and see if there's some magic power-of-2 threshold that you hit.

**Comment by ilyakopy** [comment]
Which version of R are you running?

**Comment by jpalardy** [comment]
3.4.0

**Comment by jpalardy** [comment]
you can also try to `paste-buffer` into something else (like `cat`) and see if everything is coming through.

**Comment by ilyakopy** [comment]
It pastes into anything except an R terminal hmmm.

**Comment by ilyakopy** [comment]
Can you paste your .tmux.conf when you get a chance? Thanks

**Comment by jpalardy** [comment]
https://github.com/jpalardy/dotfiles/blob/master/tmux.conf

**Comment by ilyakopy** [comment]
Solved: https://unix.stackexchange.com/questions/131105/how-to-read-over-4k-input-without-new-lines-on-a-terminal

`stty cbreak` solves the problem

**Comment by jpalardy** [comment]
Damn -- that's good to know.

Thanks for pointing it out.
