### ISSUE TITLE
Send whole file to tmux or send a custom command

### ISSUE THREAD

**Issue by GhostValk** [jpalardy/vim-slime#145]
It's possible to send the entire content of the current buffer to the tmux pane instead of only the selection? Also, it's possible to send an specific string + the file?

**Comment by jpalardy** [comment]
It's not built-in directly, but you can make it work.

You can hook up what you need with [these commands](https://github.com/jpalardy/vim-slime/blob/master/plugin/slime.vim#L294-L296).

You'll have to make a binding that captures the whole file (either programmatically or something like `ggVG`) and calls vim-slime.

Is this enough to go on?

**Comment by GhostValk** [comment]
Thanks, i've done it (in a way that satisfies my need for my specific codes). This is what i made:

function! s:SlimeSendFile() abort
  call s:SlimeGetConfig()

  write
  let pth = expand('%:p:h')
  let spth = join(["setwd('", pth, "'); "], "")
  let src = expand('%:p')
  let ssrc = join(["source('", src, "',echo = TRUE)"], "")
  let bla = 'rm(list = setdiff(ls(), lsf.str())); '
  let sfin = join([bla,spth,ssrc], "")
  call s:SlimeSend(sfin)

endfunction

Which basically, (1) sets the path to the current directory, (1) removes all variables but not the functions in R caché and (3) sources the file. As i said, i made that 'file sourcing' function specifically for the codes i run (same variable names, with a lot of predefined functions, etc.)

The code line is sent properly to the buffer, the only problem is that i haven't figured out how to "press enter" in the buffer, the line is sent, but it's just printed in the prompt, gotta press enter manually.

I believe it's a problem with the s:SlimeSend() command..

Any idea? Thanks in advance!

**Comment by jpalardy** [comment]
Idea: try putting "\r" or "\n" in the string you send.

I think that would work, let me know.

**Comment by GhostValk** [comment]
I was trying with <cr> and nothing, but with \n worked perfectly, now is fully working, thanks a lot bro!!

`let sfin = join([bla,spth,ssrc], "") -> let sfin = join([bla,spth,ssrc,"\n"], "")`

**Comment by jpalardy** [comment]
Awesome :-)

**Comment by tankorsmash** [comment]
Seems like the modern way of doing this is now `:%SlimeSend`, which is great too! Thanks for the plugin!

**Comment by JoaquimEsteves** [comment]
Just found out this discussion, like @tankorsmash  I've also been enjoying using `:%SlimeSend` a lot. If the maintainers are against a new command I'd consider adding a little extra line like so to the docs/readme

```diff
:<range>SlimeSend	Send a [range] of lines to screen, tmux or whimrepl.
			If no range is provided the current line is sent.
+			To send a whole file try *:%SlimeSend*.
```

**Comment by jpalardy** [comment]
@JoaquimEsteves that sounds good: send the PR so you get the credit? 😃

**Comment by JoaquimEsteves** [comment]
> [@JoaquimEsteves](https://github.com/JoaquimEsteves) that sounds good: send the PR so you get the credit? 😃

Hell yeah! Cheers brother.
