### ISSUE TITLE
A little expansion on the plugin..

### ISSUE THREAD

**Issue by GhostValk** [jpalardy/vim-slime#146]
Well, this is not an issue, but following a question i asked in the past about transfering the whole file from an R script to Tmux, i kept diggin' and applied the same logic to basically make a wide compiler for many languages i use.

This is the result, i wanted to share it here as i find it very useful:

```
" Specific Language Compiler

function! s:SlimeSendScript() abort
  let g:slime_default_config = {"socket_name": "default", "target_pane": "t1:0.0"}
  write
  let suf = join([" ", expand('%:p'), "\n"], "")
  let ext = expand('%:e')

  if ext == "pl"
	  let spth = join(["perl", suf], "")
  elseif ext == "sh"
	  let spth = join(["sh", suf], "")
  elseif ext == "rb"
	  let spth = join(["ruby", suf], "")
  elseif ext == "py"
	  let spth = join(["python2", suf], "")
  elseif ext == "awk"
	  let spth = join(["awk", suf], "")
  elseif ext == "fish"
	  let spth = join(["fish", suf], "")
  elseif ext == "hs"
	  let spth = join(["ghc -o ", expand('%:r'), " ", expand('%'), "; and ", expand('%:r'), "\n"], "")
  elseif ext == "cc"
	  let spth = join(["g++ ", expand('%'), " -o ", expand('%:r'), "; and ", expand('%:r'), "\n"], "")
  elseif ext == "r"
	  let g:slime_default_config = {"socket_name": "default", "target_pane": "t1:0.1"}
	  let clr = 'rm(list = setdiff(ls(), lsf.str())); '
	  let spr = join(["setwd('", expand('%:p:h'), "'); "], "")
 	  let ssrc = join(["source('", expand('%:p'), "',echo = TRUE)"], "")
	  let spth = join([clr,spr,ssrc,"\n"], "")
  endif

  call s:SlimeSend(spth)

endfunction
```

As can be seen, tmux's panel 0 is a  terminal prompt and panel 1 is the R prompt; i have already tested it and works perfect, saving me a lot of time.

**Comment by GhostValk** [comment]
Following that logic, slime could become the default Vim compiler-bridge for all the standard languages!

**Comment by jpalardy** [comment]
I'm not sure I'm following the logic here…

In the original issue, you were pushing the whole file through again (removing the variables). This is a generalized version of that?

**Comment by GhostValk** [comment]
Yeah, something like that :) i made a general function that transfers a custom line (depending on the buffer extension) that runs the current script in an R prompt (for R files) or a terminal prompt (for all the other ones).

Thought it could be a good complement to your plugin, making it a bit wider for running scripts.

**Comment by jpalardy** [comment]
I can't say it's a common use-case. Either people don't do that, or they all came up with their own solutions…

I don't think I would integrate this directly in vim-slime. But I can imagine it as a "side" plugin. If you decide to go that way, I could add a link to your project in the README.

Let me know.
