### ISSUE TITLE
Multiple lines getting clipped

### ISSUE THREAD

**Issue by libgober** [jpalardy/vim-slime#148]
Possibly this is something obvious, but trying to copy multiple lines into ipython isn't working for me. I am using tmux. My .slimepaste file reads like:

```
import os
import glob

foo = glob.glob("*.csv.gz")
```

Yet only "import os" goes through. I get a name error when I enter glob, so clearly the second import statement has not been evaluated. What could be happening?

**Comment by jpalardy** [comment]
Hi there,

Are you configured [like this](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python)?

**Comment by libgober** [comment]
No I was not, thanks!

**Comment by jpalardy** [comment]
Yeah, sorry about that.

iPython has its own quirks, and vim-slime needs extra love to work correctly.
