### ISSUE TITLE
SlimeSend doesn't preserve cursor position

### ISSUE THREAD

**Issue by qwfy** [jpalardy/vim-slime#151]
In a buffer like this:
```
1 blah # the first column is line number
2 blah
3 blah <- current cursor position
4 blah
```
and the cursor is at line 3, execute `:1,4 SlimeSend` will place the cursor at the beginning of line 1, expectation: cursor position should still be at line 3.

**Comment by jpalardy** [comment]
Hi there,

I checked the code -- cursor position preservation is a feature that came relatively late. It was tackled on the "happy path", the regular `c-c, c-c` binding.

It would be possible to add the feature to the other paths in the code.

Any reason you would call `:1,4 SlimeSend` manually rather than with a visual selection or the default behavior (current paragraph)?

**Comment by qwfy** [comment]
The reason is to send codes between two markers ([some IDE call this a cell](https://pythonhosted.org/spyder/editor.html)) to the terminal.

I wrap some codes I want to send with a marker, say `# %%`, and send it with:

    noremap <S-ENTER> :?^# %%\(\s\\|$\)?+1,/^# %%\(\s\\|$\)/-1 SlimeSend<CR>

The codes I want to send is too long to fit in one paragraph, and visual selection soon becomes tedious if you want to send the same codes again and again.

PS. Thanks for the plugin :+1:, greatly improved my QOL, before this I have to copy and paste.

**Comment by jpalardy** [comment]
Interesting :-)

I'm not sure how much of that line could be substituted by a visual selection, something like:

- find previous %%
- start visual selection
- find next %%
- call slime with `c-c, c-c`

At this point, it's very macro-like 🤔

**Comment by qwfy** [comment]
Looking at the documentation (`:help func-range`):

    When the [range] argument is added, the function is
    expected to take care of a range itself.  The range is
    passed as "a:firstline" and "a:lastline".  If [range]
    is excluded, ":{range}call" will call the function for
    each line in the range, with the cursor on the start
    of each line.  See |function-range-example|.
    The cursor is still moved to the first line of the
    range, as is the case with all Ex commands.

Seems the problem is caused by passing range to `call`: [`command -range -bar -nargs=0 SlimeSend <line1>,<line2>call s:SlimeSendRange()`](https://github.com/jpalardy/vim-slime/blob/65201427e125f8dc29ae434b7897e1eb854276ab/plugin/slime.vim#L293), I did the following change, it now preserves the cursor position.

    --- a/plugin/slime.vim
    +++ b/plugin/slime.vim
    @@ -238,12 +238,12 @@ function! s:SlimeSendOp(type, ...) abort
       call s:SlimeRestoreCurPos()
     endfunction

    -function! s:SlimeSendRange() range abort
    +function! s:SlimeSendRange(startline, endline) abort
       call s:SlimeGetConfig()

       let rv = getreg('"')
       let rt = getregtype('"')
    -  silent exe a:firstline . ',' . a:lastline . 'yank'
    +  silent exe a:startline . ',' . a:endline . 'yank'
       call s:SlimeSend(@")
       call setreg('"', rv, rt)
     endfunction
    @@ -314,7 +314,7 @@ endfunction
     """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

     command -bar -nargs=? SlimeConfig call s:SlimeConfig(<f-args>)
    -command -range -bar -nargs=0 SlimeSend <line1>,<line2>call s:SlimeSendRange()
    +command -range -bar -nargs=0 SlimeSend call s:SlimeSendRange(<line1>, <line2>)
     command -nargs=+ SlimeSend1 call s:SlimeSend(<q-args> . "\r")
     command -nargs=+ SlimeSend0 call s:SlimeSend(<args>)
     command! SlimeSendCurrentLine call s:SlimeSend(getline(".") . "\r")

**Comment by jpalardy** [comment]
I can live with that. Send it as a PR?
