### ISSUE TITLE
Add configuration for vim terminal

### ISSUE THREAD

**Issue by addadi** [jpalardy/vim-slime#155]
it would be useful to have optional configuration for vim 8 terminal, for example:
let g:slime_default_config = {"vertical" : 1, "term_finish": "close"} 

and then in VimterminalDescription something like:
let new_bufnr = term_start(cmd, b:vimterminal_config)
(assuming vimterminal_config reads from slime_default_config)

Thanks,

**Comment by jpalardy** [comment]
Hi there,

If you're willing to prototype this and send me a PR, I would certainly consider it.

**Comment by addadi** [comment]
ok, I just did so (with my very humble viml skills)

**Comment by jpalardy** [comment]
moved to #157

**Comment by addadi** [comment]
you can close this now

**Comment by jpalardy** [comment]
Thanks for the PR :-)
