### ISSUE TITLE
extra newline when sending to vim8 :terminal?

### ISSUE THREAD

**Issue by andymass** [jpalardy/vim-slime#161]
I'm using `g:slime_target = 'vimterminal'`, most recent vim and vim-slime, archlinux, zsh/bash.  I've noticed `:SlimeSendLine` sends an extra `<cr>` to the terminal, in addition to the one that runs the command.  It also happens with `<plug>SlimeRegionSend` when selecting a partial line, so I think it's not a matter of e.g. accidentally grabbing the current line's newline.  vim-slime seems to be adding two newlines when the sent text does not have one already.

As an example, where `[ ]` is the visual selection,

    [some line] some extra

Pressing `<plug>SlimeRegionSend` in visual mode, the terminal would look like:

    $ some line<cr>
    $ <cr>
    $ [cursor]

`<cr>` for emphasis.

So, is this the expected behavior?  I can see how it might be intentional and useful to separate multiple terminal sends, but I didn't see anything about it in the documentation or existing issues mentioning it.

However, I'm wondering if it's possible to disable this?  I am running a command which expects keyboard input, and the newline is being sent into that interactive command.

**Comment by gbarta** [comment]
While it is possible that some people might like the extra newline, I think it is just a bug due to the way that the text is sent to the vim terminal line-by-line.  I'll look into a fix tomorrow.

**Comment by andymass** [comment]
I looked into this and have a simple workaround.  The basic problem is here:

https://github.com/jpalardy/vim-slime/blob/e58486b791e6e1126ffd46d4ef634b8fef104f7f/plugin/slime.vim#L156-L159

Since the unnamed register is always converted to visual line mode, `call setreg('"', @", 'V')`, it will always have a trailing `^J`.  Then, splitting it with keepempty will have the final element being an empty string.  So I just remove that element:

```vim
  for l in split(a:text,"\n",1)[:-2]
    call term_sendkeys(bufnr,l."\<cr>")
    call term_wait(bufnr)
  endfor
```

**Comment by pfernandez** [comment]
Bump. Seeing the same issue. In fact if I simply execute the file with `:SlimeSend1 ./my-script`, two extra carriage returns are sent, not one as documented.
