### ISSUE TITLE
Plugin always send the same thing to tmux pane

### ISSUE THREAD

**Issue by mrbig033** [jpalardy/vim-slime#162]
I'm on MX Linux 17, using NVIM v0.2.3, IPython 5.1.0  and Python 3.5.3. Tmux reports that it's version is `master`, I don't know what that means. Here's my nvim config files: https://github.com/mrbig033/dotfiles/tree/master/nvim.

The issue: every time I hit `<c-c><c-c>`, slime sends the same string to both ipython3 and ipython on the other pane: 

```
In [1]: " https://github.com/jpalardy/vim-slime
  File "<ipython-input-1-227d8b085015>", line 1
    " https://github.com/jpalardy/vim-slime
                                           ^
SyntaxError: EOL while scanning string literal
```

**Comment by jpalardy** [comment]
Link to dotfiles is gone…

**Comment by jpalardy** [comment]
Re-open if you still have that problem.

**Comment by mrbig033** [comment]
It's been a long time and my configurations are totally different right now. Sorry.

**Comment by jpalardy** [comment]
I'm sorry too… I missed the github notification and your issue fell through the cracks :-(
