### ISSUE TITLE
Require a noobs friendly tutorial in the ReadMe

### ISSUE THREAD

**Issue by ghost** [jpalardy/vim-slime#163]
I am a noob and was trying to create a python REPl similar to this one in [vim (Python instead of R)](https://github.com/jpalardy/vim-slime/blob/master/assets/vim-slime.gif) one python editor and the other as output monitor. I tried to follow this [tutorial ](https://technotales.wordpress.com/2007/10/03/like-slime-for-vim/) but I cant understand anything. I have installed the latest tmux, ipython, screen, vim and used pathogen to install this plugin. I read whatever article avialable in the web to undertand its installation  process but failed completely. Can you please add a noobs friendly tutorial to the readme.

**Comment by jpalardy** [comment]
Hi there,

I'm not sure I'm in the best position to write a noobs friendly tutorial. Neither vim nor tmux are especially noobs friendly in the first place.

If someone wrote one, I would be willing to include a link from the README.

**Comment by jpalardy** [comment]
no reply
