### ISSUE TITLE
C-c C-c sent multiple lines by default ?

### ISSUE THREAD

**Issue by xiangpeng2008** [jpalardy/vim-slime#164]
Hi,
I don't know if I'm the only person who has this problem, when I press C-c C-c without selection, it sends all the lines before next blanc line to target session. For example, in the code below, if the cursor is on the line of `a=1`, C-c C-c will send both `a=1` and `b=2` to target session. 
```
a=1
b=2

c=3
```
Is it normal ?
Thanks!

**Comment by LeOtaku** [comment]
Yes, this is Experten behavior. „C-c C-c“ defaults to :SlimeParagraphSend. There is also :SlimeSendCurrentLine, which is probably what you want.
