### ISSUE TITLE
"let" assigment on ghci is no longer needed with ghci-8.2+

### ISSUE THREAD

**Issue by mimi1vx** [jpalardy/vim-slime#166]
https://github.com/jpalardy/vim-slime/blob/e58486b791e6e1126ffd46d4ef634b8fef104f7f/ftplugin/haskell/slime.vim#L19

**Comment by jpalardy** [comment]
no reply

**Comment by jpalardy** [comment]
@mickk-on-cpp 

Would you be open to?
- creating a PR
- making this configurable (so people can switch between modes)
- update the Haskell-related documentation
