### ISSUE TITLE
slime_python_ipython set to 1 but still 1 line being copied over

### ISSUE THREAD

**Issue by brickinedifice** [jpalardy/vim-slime#167]
Hi: I set the variable above to 1 but still one line is being copied.  Attached is the version number of iPython and the setting of the variable slime_python_ipython variable in .vimrc.

Could you share any guidance on how I can troubleshoot this?  I am using %load -r magic in iPython as a workaround for now. 

<img width="482" alt="screen shot 2018-08-31 at 17 26 59" src="https://user-images.githubusercontent.com/35044211/44936664-a22be580-ad43-11e8-9802-a30ba189c31d.png">
<img width="256" alt="screen shot 2018-08-31 at 17 28 24" src="https://user-images.githubusercontent.com/35044211/44936665-a22be580-ad43-11e8-8a92-b708233e8ef6.png">

**Comment by jpalardy** [comment]
You can check other people's [config](https://github.com/search?q=%22slime_python_ipython%22&type=Code).

Did you ever make it work for yourself?

**Comment by brickinedifice** [comment]
I am coding in node.js. Slime seems to work fine with node.

**Comment by jpalardy** [comment]
Yeah, python REPLs are sensitive to whitespace…

What vim-slime does is closer to pasting than inputting data manually.

You can check what the ftplugin tries to do [here](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim). It's not much code, and you're supposed to hit the `if` part.

**Comment by brickinedifice** [comment]
Thanks.
