### ISSUE TITLE
Vertical Split by Default?

### ISSUE THREAD

**Issue by danilofreire** [jpalardy/vim-slime#168]
Hi @jpalardy! 

I hope you're doing very well. Thanks for the great plugin! I have a very newbie question which I haven't been able to answer. I'm using the vim terminal as my default option and I would like the windows to open vertically by default. I added `set splitright` and `set splitbelow` to my `.vimrc` file but it doesn't seem to work. I couldn't figure out how to configure `vim-slime` from reading the README.md, I'm sorry. Any help would be greatly appreciated, thanks :)

**Comment by jpalardy** [comment]
Did you add

`let g:slime_target = "vimterminal"`

to your `.vimrc`?

Roughly, it would look like:

- type `:terminal`
- `ctrl-w, ctrl-w` to come back to your buffer
- type some text, `ctrl-c, ctrl-c` to send
- pick number from prompt
- text appears in terminal

**Comment by danilofreire** [comment]
Hi Jonathan,

Thanks very much for your reply. Yes, I did add that to my `.vimrc`. I
would like to ask if you if there is any option I could pass to
`g:slime_vimterminal_config` so that the terminal opens vertically by
default. Thanks again!

On 17 Sep 2018 00:42, "Jonathan Palardy" <notifications@github.com> wrote:

Did you add

let g:slime_target = "vimterminal"

to your .vimrc?

Roughly, it would look like:

   - type :terminal
   - ctrl-w, ctrl-w to come back to your buffer
   - type some text, ctrl-c, ctrl-c to send
   - pick number from prompt
   - text appears in terminal

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jpalardy/vim-slime/issues/168#issuecomment-421889256>,
or mute the thread

**Comment by danilofreire** [comment]
Hi Jonathan,

Thanks very much for your reply. Yes, I did add that to my `.vimrc` file. I would like to ask if you if there is any option I could pass to `let g:slime_vimterminal_config =` so that the terminal opens vertically by default. Thanks again!

**Comment by jpalardy** [comment]
`vim-slime` doesn't take care of opening a `:terminal` for you; it always assumes you've done that for yourself first.

As for `vertical`, I found:

`:vertical terminal`

and

`:botright vertical terminal`

which, I think, does what you want. These are not fun to type, so you would probably create a keyboard mapping for them. (although you can type the shorter `:bo vert term`)

**Comment by danilofreire** [comment]
Many thanks for your reply, @jpalardy. I will do as you recommend, this solves my issue. 

Congratulations again for the great plugin :)

**Comment by jpalardy** [comment]
awesome 😄

**Comment by victorkristof** [comment]
For the record, you can pass option to `term_start()` using `g:slime_vimterminal_config`. One useful option is `"vertical"`, which you can set to `1` to open the terminal vertically:
```
let g:slime_vimterminal_config = { "vertical": 1 }
```
Other useful options can be set, such as automatically closing the terminal when exiting ipython. Have a look at `:help term_start()` :)

**Comment by danilofreire** [comment]
Thanks, @victorkristof!
