### ISSUE TITLE
Indentation breaks when pasting into a tmux pane

### ISSUE THREAD

**Issue by randomizedthinking** [jpalardy/vim-slime#169]
I use vim-slime under tmux for various tasks. One item I noticed is that the indentation of the codes could be broken for some REPL apps -- not as sever as python codes, but still annoying.

Some observations:

- the indentation is correct if paste into the buffer by mouse click;
- the indentation is broke if paste by C-c C-c through vim-slime.

I found that for tmux, the bracket paste mode is *not* set. Should it be turned on, the indentation is well reserved: `paste-buffer -d -p ...`. Now the general paste operation should be done in three steps:

1. load-buffer and check whether the buffer contains an ending CR -- if yes, remove it;
1. paste-buffer under bracketed paste mode;
1. paste a CR if the checking in 1. is true.

I tend to think, with the bracketed paste mode set up correctly, no special treatment is required for python or any other language.

Thanks.

**Comment by ivan-krukov** [comment]
I wonder if this is a `ipython` specific behaviour? Pasting works well for me in `nvim`+`tmux`+`python3`. However, it breaks with `ipython`. See here for a fix: https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python

Suggestion: if this is a common problem, should this be brought up into the main `README`?

**Comment by jpalardy** [comment]
The main README [links](https://github.com/jpalardy/vim-slime#language-support) to the python / ipython README…

I'm not sure how to make it more obvious without hijacking the README.

I'm open to suggestions.

**Comment by ivan-krukov** [comment]
Yup. It does. You're right - there might not be a better way to do it.

**Comment by randomizedthinking** [comment]
No, this is not an ipython specific behavior. It is a generic issue.

BTW, just tested that with the bracketed paste mode, vim-slime can work for
ipython without any magic.

**Comment by oblitum** [comment]
I get indentation issue with another nvim instance in another pane, the target nvim has to be in paste mode for it to work. I tried that after seeing the same indentation issue with `pgcli`, vim-sliming this:

```sql
INSERT INTO teachers (first_name, last_name, school, hire_date, salary)
VALUES ('Janet', 'Smith', 'F.D. Roosevelt HS', '2011-10-30', 36200),
       ('Lee', 'Reynolds', 'F.D. Roosevelt HS', '1993-05-22', 65000),
       ('Samuel', 'Cole', 'Myers Middle School', '2005-08-01', 43500),
       ('Samantha', 'Bush', 'Myers Middle School', '2011-10-30', 36200),
       ('Betty', 'Diaz', 'Myers Middle School', '2005-08-30', 43500),
       ('Kathleen', 'Roush', 'F.D. Roosevelt HS', '2010-10-22', 38500);
```

Leads to:

```sql
INSERT INTO teachers (first_name, last_name, school, hire_date, salary)
VALUES ('Janet', 'Smith', 'F.D. Roosevelt HS', '2011-10-30', 36200),
       ('Lee', 'Reynolds', 'F.D. Roosevelt HS', '1993-05-22', 65000),
           ('Samuel', 'Cole', 'Myers Middle School', '2005-08-01', 43500),
               ('Samantha', 'Bush', 'Myers Middle School', '2011-10-30', 36200),
                   ('Betty', 'Diaz', 'Myers Middle School', '2005-08-30', 43500),
                       ('Kathleen', 'Roush', 'F.D. Roosevelt HS', '2010-10-22', 38500);
```

Still searching the issue tracker for how to solve this. This issue looked like the most related one.

**Comment by oblitum** [comment]
Ah, I guess it's a common issue due to program's auto indent that piles up to the leading source indentation. Any idea how to avoid this?
