### ISSUE TITLE
Question: Replay multi line code in IPython

### ISSUE THREAD

**Issue by kariya2** [jpalardy/vim-slime#176]
Apologies if this is an ignorant question. When I send over a chunk of code to Ipython in a tmux window it executes a cpaste in my ipython session. There is no way for me to go back and rerun that chunk of code. Is there any way to enable this functionality?

**Comment by jpalardy** [comment]
Do you mean: "how do I paste the same thing several times?"

If so, you can re-select the section of code and hit `ctrl-c, ctrl-c` again. That's essentially "free" if the selection is "the current paragraph".

If the selection is more complicated, you can re-select with `gv`.
