### ISSUE TITLE
Wrong Tmux panel indexing instructions in doc?

### ISSUE THREAD

**Issue by oblitum** [jpalardy/vim-slime#178]
Hi, just trying this plugin, it's great. I'm using tmux, and it seems docs are not correct at `":i"`, it should be `":.i"`, at least this is what worked for me (tried with `":.2"` after setting it up again with <kbd>ctrl</kbd><kbd>c</kbd>, <kbd>v</kbd>, my tmux indexing starts at 1). I figured that out from this line which I'm not using `let g:slime_default_config = {"socket_name": split($TMUX, ",")[0], "target_pane": ":.2"}`.

**Comment by jpalardy** [comment]
Hi there,

> it's great

Thanks :-)

Can you explain your setup and give me an example of what works and what doesn't? If possible, a PR would be appreciated too.

**Comment by oblitum** [comment]
Hi, it's just that README and docs states to index tmux with `":i"` syntax, but what works for indexing panes has been `":.i"`, `:i`, without `.`, doesn't work.

**Comment by oblitum** [comment]
This is my `tmux.conf` where I set indexing to 1, which is a common approach, but that's not particularly relevant, I just have to use ":.2" on a two sided split, instead of ":.1":

- https://github.com/oblitum/dotfiles/blob/ArchLinux/.tmux.conf#L17-L18

**Comment by jpalardy** [comment]
Ok, here's what I tried:

```bash
> tmux ls
# ...snip...
20: 1 windows (created Tue Dec  4 09:10:05 2018) [160x44] (attached)
```
That session has 1 window, 1 pane.

```bash
> seq 3 14 > nums.txt
> tmux load-buffer nums.txt; tmux paste-buffer -d -t 20:
> tmux load-buffer nums.txt; tmux paste-buffer -d -t 20:0
> tmux load-buffer nums.txt; tmux paste-buffer -d -t 20:0.0
```

These all work the same ^. (for me)

From within the session, `:`, `:0`, `:0.0` also work.

**Comment by oblitum** [comment]
```
~ ❯❯❯ tmux load-buffer nums.txt; tmux paste-buffer -d -t :2
3
4
5
6
7
8
9
10
11
12
13
14
~ ❯❯❯ 3
cd: no such entry in dir stack
~ ❯❯❯ 4
cd: no such entry in dir stack
~ ❯❯❯ 5
cd: no such entry in dir stack
~ ❯❯❯ 6
cd: no such entry in dir stack
~ ❯❯❯ 7
cd: no such entry in dir stack
~ ❯❯❯ 8
cd: no such entry in dir stack
~ ❯❯❯ 9
cd: no such entry in dir stack
~ ❯❯❯ 10
zsh: command not found: 10
~ ❯❯❯ 11
zsh: command not found: 11
~ ❯❯❯ 12
zsh: command not found: 12
~ ❯❯❯ 13
zsh: command not found: 13
~ ❯❯❯ 14
zsh: command not found: 14
~ ❯❯❯
~ ❯❯❯ tmux load-buffer nums.txt; tmux paste-buffer -d -t :.2
(correctly pasted to vim in insert mode on pane 2)
```

**Comment by jpalardy** [comment]
Yeah…

That's not a great outcome, but that's how the indexing work. `:2` means "window 2, current pane", while `:.2` means "current window, 2nd pane" (using base-1 indexes)

**Comment by jpalardy** [comment]
I feel that using `%TMUX_PANE` is simpler and clearer, most of the time.

Using `X:Y.Z` breaks me out of my flow 😄

**Comment by oblitum** [comment]
> I feel that using `%TMUX_PANE` is simpler and clearer, most of the time.
> 
> Using `X:Y.Z` breaks me out of my flow smile

Ah sure, agreed, thanks for that tip. That should be indeed the more useful one. Sorry about the confusion.

**Comment by oblitum** [comment]
From docs:

> ":i"    means the ith window, current pane

I'm now wondering whether there's tracking of current pane for using as an index in another window, or whether `":i"` just means window `i`, pane `0`.

**Comment by oblitum** [comment]
> From docs:
> 
> > ":i"    means the ith window, current pane
> 
> I'm now wondering whether there's tracking of current pane for using as an index in another window, or whether `":i"` just means window `i`, first pane.

From `man tmux`:

> target-pane (or src-pane or dst-pane) may be a pane ID or takes a similar form to target-window but with the optional addition of a period followed by a pane index or pane ID, for example: ‘mysession:mywindow.1’.  If the pane index is omitted, the currently active pane in the specified window is used.

**Comment by oblitum** [comment]
Last one, by checking docs I just learned of `{right-of}`, which is a great default, better than numbering:

```
let g:slime_default_config = {'socket_name': 'default', 'target_pane': '{right-of}'}
```

**Comment by jpalardy** [comment]
oooh… I like that.

Can you create a PR for the README. Let's keep the previous example and add this one -- maybe also a link to online documentation so people can try to untangle this themselves.

**Comment by oblitum** [comment]
OK, will do it.
