### ISSUE TITLE
Feature Request: directional send

### ISSUE THREAD

**Issue by oblitum** [jpalardy/vim-slime#180]
After learning of [tmux's special tokens](http://man.openbsd.org/OpenBSD-current/man1/tmux.1#_up-of_) which can be used to target panes in the surroundings of the current one, I thought it would be nice if vim-slime worked a little different when that's available, which is to support directional mappings like, `<c-c><c-h>`, `<c-c><c-j>`, `<c-c><c-k>`, `<c-c><c-l>`, that would take advantage of those directional tokens (by default, on tmux at least). This removes the need to have a fixed layout workflow, or have to reconfigure vim-slime when it changes.

**Comment by jpalardy** [comment]
Personally, that's not how I work. There's usually "where I type" and "where stuff runs".

I can imagine commands like "send left", and that's currently possible with config (meaning: without having to modify vim-slime).

Maybe we need a page with customization recommendations. It could be a sort of wiki for config people found useful.

**Comment by oblitum** [comment]
> Personally, that's not how I work. There's usually "where I type" and "where stuff runs".

In a sense, same for me, but _sometimes_ I have a need for a different workflow layout depending of the tools/panes involved.

> I can imagine commands like "send left", and that's currently possible with config (meaning: without having to modify vim-slime).

Ops, I didn't notice that could be configurable, I'd possibly not have opened the issue. So all is fine in that case, I'll check how I can do that.

> Maybe we need a page with customization recommendations. It could be a sort of wiki for config people found useful.

Sure, I guess that's just a matter of having a section for that on Wiki.

**Comment by jpalardy** [comment]
Let me know if you want to take a stab at "useful config" wiki 😃

**Comment by oblitum** [comment]
OK 👍

**Comment by oblitum** [comment]
FWIW, easier than I thought (plus saving last direction for reuse with `<c-c><c-c>`):

```vim
xmap <silent> <c-c><c-h> :exec 'let g:slime_default_config.target_pane = "{left-of}"'<cr><c-c><c-c>
nmap <silent> <c-c><c-h> :exec 'let g:slime_default_config.target_pane = "{left-of}"'<cr><c-c><c-c>
xmap <silent> <c-c><c-j> :exec 'let g:slime_default_config.target_pane = "{down-of}"'<cr><c-c><c-c>
nmap <silent> <c-c><c-j> :exec 'let g:slime_default_config.target_pane = "{down-of}"'<cr><c-c><c-c>
xmap <silent> <c-c><c-k> :exec 'let g:slime_default_config.target_pane = "{up-of}"'<cr><c-c><c-c>
nmap <silent> <c-c><c-k> :exec 'let g:slime_default_config.target_pane = "{up-of}"'<cr><c-c><c-c>
xmap <silent> <c-c><c-l> :exec 'let g:slime_default_config.target_pane = "{right-of}"'<cr><c-c><c-c>
nmap <silent> <c-c><c-l> :exec 'let g:slime_default_config.target_pane = "{right-of}"'<cr><c-c><c-c>
```

**Comment by jpalardy** [comment]
I started up the wiki: https://github.com/jpalardy/vim-slime/wiki/configurations

Please add more details and other tips.

**Comment by oblitum** [comment]
@jpalardy nice, I was going to put that example there but since it's there already, fine. For now I don't have anything more in mind, it's my sole additional conf.
