### ISSUE TITLE
please make g:slime_vimterminal_cmd

### ISSUE THREAD

**Issue by jDrunken** [jpalardy/vim-slime#181]
I always use Node in vim-slime with macvim.
annoying to type command 'node', so make Global variable like `g:slime_vimterminal_cmd`

like this,

```
# ./plugin/slime.vim :: line 187

if !exists("g:slime_vimterminal_cmd")
    let cmd = input("Enter a command to run [".&shell."]:")
    if len(cmd)==0
        let cmd = &shell
    endif
else
    let cmd = g:slime_vimterminal_cmd
endif
```

thank you!

**Comment by jpalardy** [comment]
Hi @jDrunken 

Send me a PR for this 😃 

Please include a comment in the README to document the flag.

**Comment by jDrunken** [comment]
merged. thanx. :)
