### ISSUE TITLE
Question: Mapping keys to send to a particular tmux pane

### ISSUE THREAD

**Issue by kariya2** [jpalardy/vim-slime#190]
Would it be possible to define a mapping such as C-c 1 / C-c 2 to send text to tmux pane 1:.1 / 1:.2? 

My workflow usually involves 2 ipython sessions and so I was hoping to find a good solution for this problem. Thanks :)

**Comment by jpalardy** [comment]
Hi @kariya2 ,

I don't see why not :-)

It would have to be 2 steps:
- change the config
- send `c-c, c-c` normally
