### ISSUE TITLE
Paste comes with additional indentation with pgcli

### ISSUE THREAD

**Issue by oblitum** [jpalardy/vim-slime#191]
Using vim-slime to send a paragraph like the following to [pgcli](https://github.com/dbcli/pgcli)

```sql
CREATE TABLE number_data_types (
    numeric_column numeric(20,5),
    real_column real,
    double_column double precision
);
```

It gets pasted, but for each new line there's additional indentation:

```
analysis> CREATE TABLE number_data_types (
     numeric_column numeric(20,5),
         real_column real,
             double_column double precision
             );
```

**Comment by jpalardy** [comment]
It seems like `pgcli` has a [multiline mode](https://www.pgcli.com/multi-line). Can you check if that works?

(also found [here](https://github.com/dbcli/pgcli/issues/389))

**Comment by oblitum** [comment]
I use the multiline mode, it's not the problem.

**Comment by oblitum** [comment]
My suspicion is that pgcli does alignment on new lines, that sums up to the initial space coming from the paste.

**Comment by oblitum** [comment]
I think this issue could be solved if slime provided and option to remove all indentation when pasting. It's a generic solution for a generic problem.

**Comment by oblitum** [comment]
I've applied the pull #170 that sadly ended up closed before merged and it does fix the issue for me with pgcli. It's great because it pastes with correct indentation, not needing to actually strip it out.

**Comment by oblitum** [comment]
I'm currently using Plug 'jpalardy/vim-slime', {'commit': '7059908'} to avoid this issue.

**Comment by jpalardy** [comment]
Hi @oblitum 

I'll close this for now. We can reopen later if we come up with a better way.
(I'm happy you can use that commit in the meantime)
