### ISSUE TITLE
Evaluating smaller bits of code

### ISSUE THREAD

**Issue by jboynyc** [jpalardy/vim-slime#192]
Right now `C-c C-c` evaluates the whole "paragraph" the cursor is located in. In s-exp based languages like Lisp, Scheme or Racket that usually means an entire form.

Afaict, it is not currently possible to evaluate smaller syntactical units, say an individual symbol or a sub expression. This would be useful, so consider this a feature request. 

Here's how I imagine this would work: `C-c C-c` could behave the way it currently does, but something like `C-c C-e` would evaluate either the symbol the cursor is currently on, or the expression closed by the parenthesis the cursor is currently on.

**Comment by jpalardy** [comment]
Hi @jboynyc 

Although it's not super obvious from the README (I just checked), smaller regions are supported. For example, if you visual-select something, that's what `C-c C-c` will send over.

The [code itself](https://github.com/jpalardy/vim-slime/blob/master/plugin/slime.vim#L10-L36) supports more. It's not especially complicated to [use those](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L21-L22).

If you can figure out a "movement" that selects something interesting, you can send it to slime.

**Comment by jboynyc** [comment]
Thanks, this is really helpful @jpalardy!

**Comment by jpalardy** [comment]
nice!
