### ISSUE TITLE
Sending blank lines to pane

### ISSUE THREAD

**Issue by johnwoodill** [jpalardy/vim-slime#193]
I am trying to get `vim-slime` installed and cannot figure out why it is sending blank lines to `ipython`. I have vim-slime installed and my `~/.vimrc` file looks like this:

```
Plugin 'jpalardy/vim-slime'
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}                                                                                                      
```
When I hit (C-c C-c) it sends blank lines to pane 1 which has ipython on it, but not the selected text. Why is this happening?

I'm logging into ssh (Ubuntu system), opening tmux with vim configured files, then open vim test.py in one pane and ipython in another pane.

**Comment by jpalardy** [comment]
Hi @johnwoodill 

That's a new one.

Have you tried sending text "manually" using command-line commands?
Does this happen for non ipython panes also?
Can you try the value of `TMUX_PANE` (something like %4 instead of "1") for the `target_pane`?

Let me know how that goes

**Comment by johnwoodill** [comment]
Thank you for your prompt reply.

If I type `:SlimeLineSend` manually I get:

> E492: Not an editor command: :SlimeLineSend

This behavior happens with non-ipython panes as well, such as R or simply the command line.

I set `target_pane` to `%4` as follows:

`let g:slime_default_config = {"socket_name": "default", "target_pane": "%4"}`

and I get no response. 

Any other ideas?

**Comment by jpalardy** [comment]
Let's start with a simpler setup:

- one terminal
- start tmux
- split vertically: `ctrl-a, %`   -- assuming `ctrl-a` is your tmux prefix…
- in the right split, type: `echo $TMUX_PANE`, write down the result
- switch to left pane, start vim
- type `ls`, `ctrl-c, ctrl-c`
- when prompted for `tmux target pane`, use the result from the `echo` above
- what happens then?

…

I've been using [{right-of}](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L24) in my own slime_default_config.

You can give that a try.

**Comment by johnwoodill** [comment]
Thanks again.

I did as you suggested. When I type `$TMUX_PANE` I get `%14`. I typed that in after `:SlimeConfig` and still get blank sends to the pane. I've also tried `{right-of}`.

I can't imagine it should be this difficult to get setup but I don't know why it is not working.

**Comment by jpalardy** [comment]
Let's try manually:

* create a file named "data" and generate text, save and quit  (or `seq 3 14 | shuf > data`)
* get your `TMUX_PANE` value again, possibly still `%14` but double-check
* in another terminal:

```bash
    $ tmux load-buffer data            # data is the filename
    $ tmux paste-buffer -d -t %14      # replace %14 by correct value
```

At this point, only tmux is involved (no vim, no vim-slime, no magic). If this doesn't work, could you try on another computer?

**Comment by johnwoodill** [comment]
Thanks again.

I created a file called `test.txt` with `test 1...2...3...4...` as the first line of text. I then typed in the terminal,

```
    $ tmux load-buffer test.txt            # data is the filename
    $ tmux paste-buffer -d -t %14      # replace %14 by correct value
```

and it sent to the pane correctly, so that worked. 

Now how to add in usage for vim and vim-slime?

**Comment by jpalardy** [comment]
Nice, tmux works.

Are you using vim-slime in tmux mode? (`let g:slime_target = "tmux"` in .vimrc)

Which version of vim are you using? (how's the rest of your setup: OS? etc…)

**Comment by johnwoodill** [comment]
Vim version is `version 7.4.1689`. Here is my `~/.vimrc` content:

```
call plug#begin()
Plug 'jpalardy/vim-slime'
call plug#end()

let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "%14"}
let g:slime_dont_ask_default = 1
```

OS: Ubuntu 16.04.3 LTS

I ssh into the server and run all my code from the command line terminal using shell `-csh`. (C-shell). I use tmux to manage windows.

**Comment by jpalardy** [comment]
Hmm… `csh`, I wonder…

Have you tried on another computer?

**Comment by johnwoodill** [comment]
I just tried setting up on my laptop and it works under bash, so it might be `csh`. Any idea how to fix this and still use `csh`?

Thanks for your help troubleshooting.

**Comment by jpalardy** [comment]
interesting…

vim-slime certainly shells out to interact with tmux (and to create the `.slime_paste` file). I didn't think we were doing anything bash (or zsh) -specific.

[This](https://github.com/jpalardy/vim-slime/blob/master/autoload/slime.vim#L230-L233) would have to be the problem.

I don't know if you want to debug this or just "live with it"? Let me know.

**Comment by johnwoodill** [comment]
Thanks! I'll try to debug it a bit further and send a PR if I get it working. Thanks for your help troubleshooting and for the plugin!

**Comment by jpalardy** [comment]
👍
