### ISSUE TITLE
Feature request - Allow selection to be sent as single line

### ISSUE THREAD

**Issue by mitermayer** [jpalardy/vim-slime#194]
**Background**

I really enjoy that when doing "<c-c><c-c>" slime sends all the block lines one by one to the repl. But some repls require the block to be sent at once.

**Poblem**

Some repls do not support multine and require all commands to be inlined.

**Proposal**

 Would be great if there was an option to send all the current selection inlined into a single line for repls that do not support multiline commands

**Comment by jpalardy** [comment]
Hi there,

By default, slime sends a block as a "chunk", not line by line. That behavior defaults on the ftplugin though.

What kind of code and REPL are you using?

**Comment by mitermayer** [comment]
@jpalardy,

We use "hack" (https://github.com/facebook/hhvm) at FB. When I attempt to send it to the repl it is currently sending line by line which is incompatible with what `hphpd` expects.

**Comment by jpalardy** [comment]
If you could show me a minimal example, I would try to reproduce and debug it myself.

Specifically:
- your setup (tmux, bash, other relevant)
- how you run the REPL
- what code block to send to reproduce

Thanks

**Comment by avonmoll** [comment]
I'm not sure if this is actually the same issue that OP is describing, but I am seeing something like the following:

`.slime_paste` contains
```julia
x = 1

y = 2
```

and when this gets sent to the Julia REPL, for example, each line is evaluated individually:

```
julia> x = 1
1

julia>

julia> y = 2
2
```

However, inside Julia's REPL, you can enter multi-line commands by typing `x = 1`<kbd>Alt+Enter</kbd><kbd>Alt+Enter</kbd>`y = 2`<kbd>Enter</kbd>.

**Comment by jpalardy** [comment]
Hi @avonmoll,

Trimming the blank line(s) between code lines is something that could be done by the ftplugin.

As for inserting <kbd>Alt-Enter</kbd> … that's trickier. Is <kbd>Alt-Enter</kbd> even a sequence that could be inserted in `.slime_paste` or something the REPL captures directly from its inputs 🤔

**Comment by avonmoll** [comment]
That's an interesting question that I don't know the answer to. I think that where this issue might matter is in cases like the following

```julia
function multiplyBy2(x)
    return 2*x
end
```

Fortunately, in the case of Julia, the REPL knows to wait for an `end` when it sees the start of a code block. Thus typing `function multiplyBy2(x)`<kbd>Enter</kbd> advances to a new line automatically (much like <kbd>Alt+Enter</kbd> would. However, I wonder if the REPL mentioned by OP doesn't handle this situation as I described.

Side note: considering opening an issue requesting Julia support as I don't know if I am patient enough to figure out how to write the ftplugin part myself :)

**Comment by junyixu** [comment]
What about
begin
*your code*
end
