### ISSUE TITLE
With C-c C-c .slime_paste does not update

### ISSUE THREAD

**Issue by johnwoodill** [jpalardy/vim-slime#197]
This is only happening on a remote server and I have no idea why. I have deleted .vim folder, .vimrc, and reinstalled vim-slime using vim-plugin and still get the issue. To fix I edited `~/.vim/plugged/vim-slime/autoload/slime.vim`.

```
function! s:WritePasteFile(text)
  " could check exists("*writefile")
  call system("rm " . g:slime_paste_file)
  call system("cat > " . g:slime_paste_file, a:text)
endfunction
```

Remote Server Info:

Ubuntu 16.04
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

From our previous discussion:
> interesting…
> 
> vim-slime certainly shells out to interact with tmux (and to create the `.slime_paste` file). I didn't think we were doing anything bash (or zsh) -specific.
> 
> [This](https://github.com/jpalardy/vim-slime/blob/master/autoload/slime.vim#L230-L233) would have to be the problem.
> 
> I don't know if you want to debug this or just "live with it"? Let me know.
> 
> _Originally posted by @jpalardy in https://github.com/jpalardy/vim-slime/issues/193#issuecomment-474085164_

**Comment by jpalardy** [comment]
Hey there,

Let's skip the `cat` completely:

```vim
  call writefile([a:text], g:slime_paste_file)
```

Does that work for you?

**Comment by johnwoodill** [comment]
Hi,

No, it gets stuck at,

`In [1]: %cpaste -q`

and doesn't paste the paragraph into the terminal.

When I revert back to my suggestions it works.

**Comment by jpalardy** [comment]
😞
