### ISSUE TITLE
Sending IPython no longer uses CPaste

### ISSUE THREAD

**Issue by rbpatt2019** [jpalardy/vim-slime#201]
I think this is related to #200, as the call to include CPaste seems to have been removed.

Basically, sending to iPython was working great until I updated about an hour ago (via :PlugUpdate since I use vim-plug). Now, I'm getting some very odd behavior when I try to send indented text.

If I have a block of code that looks like...
```python
for x in range(10):
    print(x)
```
Everything sends fine. But if I make that indented block even slightly more complex...
```python
for x in range(10):
    print(x)
    print(x)
```
It fails with a syntax error as the second print call gets pasted 2 indents over. It appears that without using IPython's CPaste, each successive line is pasted a cumulative extra indent over. ie if you add a third print call, it will be 3 indents over instead of 1, etc. Which is obviously problematic for any but the most basic indented blocks!

**Comment by rbpatt2019** [comment]
UPDATE: It's definitely related to #200 . I just reverted the update and the problem resolved itself.

**Comment by jpalardy** [comment]
@NedWestern ok, let's roll this back for now.

**Comment by jpalardy** [comment]
@rbpatt2019 reverted on master.

sorry about this.

**Comment by rbpatt2019** [comment]
@rbpatt2019 No worries! I love the plugin, and if I get a moment, I might take a look at some of the issues related to!

**Comment by NedWestern** [comment]
OK, sorry about that. Can I ask what version of IPython you are using?

**Comment by jpalardy** [comment]
@rbpatt2019 :+1:

**Comment by NedWestern** [comment]
@rbpatt2019 Can you please try this new version? It only adds an extra newline so... I can't see why it would break for you.
