### ISSUE TITLE
keybings not work

### ISSUE THREAD

**Issue by itetao** [jpalardy/vim-slime#203]
hey, may i get your help, thanks.

my keybinds here

    1 " plugin 'jpalardy/vim-slime'                                                                           
    2 """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    3 let g:slime_target="tmux"
    4 let g:slime_default_config={"socket_name": "default", "target_pane": "2"}
    5 let g:slime_dont_ask_default=1
    6 let g:slime_no_mappings=1
    7 augroup schemeRun
    8     autocmd FileType scheme nnoremap <Space>r <Plug>SlimeLineSend
    9     autocmd FileType scheme xnoremap <Space>r <Plug>SlimeRegionSend
   10     autocmd FileType scheme nnoremap <Space>R <Plug>SlimeParagraphSend
   11     autocmd FileType scheme xnoremap <Space>R <Plug>SlimeRegionSend   
   12 augroup END
   13 augroup lispRun
   14     autocmd FileType lisp nnoremap <Space>r <Plug>SlimeLineSend
   15     autocmd FileType lisp xnoremap <Space>r <Plug>SlimeRegionSend
   16     autocmd FileType lisp nnoremap <Space>R <Plug>SlimeParagraphSend
   17     autocmd FileType lisp xnoremap <Space>R <Plug>SlimeRegionSend   
   18 augroup END

it do nothing, when i press these key.

neovim : 0.3.5
tmux: 2.9

**Comment by jpalardy** [comment]
Is it vim-slime related, or does the mapping work when set to other commands?

I would start with something simpler -- like using echo or echom.

Let me know how that goes. 😃

**Comment by itetao** [comment]
yeah, this is my work picture:
![11](https://user-images.githubusercontent.com/46645709/58607877-dda81000-82d3-11e9-869f-594833e2c489.png)

when  i  bindkey like this:
    1 autocmd FileType lisp xnoremap <Space>r :SlimeSend<cr>                                                  
    2 autocmd FileType lisp nnoremap <Space>r :SlimeSend<cr>
    3 autocmd FileType scheme xnoremap <Space>r :SlimeSend<cr>
    4 autocmd FileType scheme nnoremap <Space>r :SlimeSend<cr>

it work well, you see : 
![22](https://user-images.githubusercontent.com/46645709/58608033-55763a80-82d4-11e9-869e-adc17226014a.png)


and , when i switch bind to `<Plug>Slime....`     it just work like no bindkey when i press, and no echo message

**Comment by itetao** [comment]
`   1 autocmd FileType lisp xnoremap <Space>r :SlimeSend<cr>  `                                             
  `  2 autocmd FileType lisp nnoremap <Space>r :SlimeSend<cr>`
    `3 autocmd FileType scheme xnoremap <Space>r :SlimeSend<cr>`
   ` 4 autocmd FileType scheme nnoremap <Space>r :SlimeSend<cr>`

**Comment by jpalardy** [comment]
I'm not overly familiar with how `<Plug>` works... this was a contribution from a pull request.

If it works without `<Plug>`, what's the downside of that approach?

**Comment by itetao** [comment]
yeah, i find slime command can be directly to use, they are: SlimeSend, SlimeSend0, SlimeSend1, SlimeSendCurrentLine

but i don't exactly know how to use them, may i have one command to send currentline, one command to send paragrah,

**Comment by jpalardy** [comment]
Here are [some mappings](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L20-L24) I use, if that helps.

**Comment by itetao** [comment]
yeah, thanks  for your time
