### ISSUE TITLE
Commands not executing in IPython with SlimeSend1 and SlimeSendCurrentLine

### ISSUE THREAD

**Issue by hanschen** [jpalardy/vim-slime#208]
`SlimeSend1` and `SlimeSendCurrentLine` used to send the specified text/current line to IPython and then execute the line. Now they send the line and then append a carriage return without executing the line.

This issue seems to have been introduced by #206.

**To reproduce**

1. Open tmux, open vim in a tmux pane and IPython in another tmux pane.
2. Run `:SlimeSend1 1` in vim.

**Expected behavior**

    In[1]: 1
    Out[1]: 1

The line (`1`) is executed in IPython.

**Actual behavior**

    In [1]: 1
        ...:

A newline is appended to the line instead of executing the line.

**Other information**

Reproduced with neovim 0.4.0 and vim 8.1 using tmux 2.9a and newest version of vim-slime (commit 705990815e7874cabf13c77a41462f1326d04ca2).

vim-slime is configured as follows:

    let g:slime_target = 'tmux'

**Comment by jpalardy** [comment]
Hi @hanschen,

I [reverted](https://github.com/jpalardy/vim-slime/commit/dc8ca22cef3f87999d926e18e2e230145e013838) to before #206. Can you confirm that it fixes this issue?

@oblitum ^

**Comment by oblitum** [comment]
:-/

Sad this feature is ended up being reverted. I guess the closed issues related will at least need to get reopened, as it is slime doesn't work with `pgcli`.

**Comment by hanschen** [comment]
@jpalardy Yes, that fixes this issue. The latest vim-slime (dc8ca22cef3f87999d926e18e2e230145e013838) works as expected.

**Comment by jpalardy** [comment]
@hanschen ok, I'm going to close this for now.

@oblitum I'm open to suggestions on #191. In the meantime, how do you feel about putting the reverted code on a branch?

**Comment by oblitum** [comment]
> @oblitum I'm open to suggestions on #191. In the meantime, how do you feel about putting the reverted code on a branch?

I'm currently using `Plug 'jpalardy/vim-slime', {'commit': '7059908'}`.

**Comment by oblitum** [comment]
> @oblitum I'm open to suggestions on #191.

Let's reopen it  as first step :-/

**Comment by oblitum** [comment]
hey @jpalardy, I finally got bit fed up with being stuck at 7059908 and gave a look at this issue, you can't imagine how easy it's the fix, it came as soon as I opened slime source and notice this:

```vim
command -nargs=+ SlimeSend1 call slime#send(<q-args> . "\r")
```

So I thought about changing `"\r"` for `"\n"` just to see if it worked, and it works!

Do you wish to give a look at this or want a PR? It seems in the source code this is the only place where `\r` is used, so the pull would just revert the revert, and apply this tweak.

**Comment by oblitum** [comment]
Oh sorry, actually not exactly the same behavior. With this fix and that change, `ipython` does get the "<kbd>enter</kbd>", but it seems after a newline, it's subtle to notice but, there's this ... in `ipython`, and it's the only difference:

without fix:
```
In [4]: 1
Out[4]: 1

```

with fix:
```
In [5]: 1
   ...:
Out[5]: 1
```

**Comment by oblitum** [comment]
ah, got it, with bracket paste mode, there's no need to append `"\r"` or `"\n"` :)

**Comment by oblitum** [comment]
Scratch what I said, ok, here's the thing. To actually fix this issue at the time bracket paste was merged it was simple, indeed, it was just a matter of changing `"\r"` for `"\n"`: 

```diff
diff --git a/plugin/slime.vim b/plugin/slime.vim
index 146e489..d133735 100644
--- a/plugin/slime.vim
+++ b/plugin/slime.vim
@@ -9,9 +9,9 @@ let g:loaded_slime = 1

 command -bar -nargs=0 SlimeConfig call slime#config()
 command -range -bar -nargs=0 SlimeSend call slime#send_range(<line1>, <line2>)
-command -nargs=+ SlimeSend1 call slime#send(<q-args> . "\r")
+command -nargs=+ SlimeSend1 call slime#send(<q-args> . "\n")
 command -nargs=+ SlimeSend0 call slime#send(<args>)
-command! SlimeSendCurrentLine call slime#send(getline(".") . "\r")
+command! SlimeSendCurrentLine call slime#send(getline(".") . "\n")

 noremap <SID>Operator :<c-u>call slime#store_curpos()<cr>:set opfunc=slime#send_op<cr>g@
```

With that patch applied on top of 7059908, this is fixed, plus bracket paste mode is still in.

Sadly the current state of master changed substantially and currently I ignore how to undo and get all goodies back.

I made bad reverts while I was testing hence the confusion.
