### ISSUE TITLE
Support fenced code blocks in markdown and rmarkdown files

### ISSUE THREAD

**Issue by joelostblom** [jpalardy/vim-slime#209]
Thanks for making vim-slime, I have just started using it and it is already great!

Do you think it is within the scope of the plugin to support execution of fenced code blocks within markdown and rmarkdown documents? I am thinking that `SimeParagraphSend` could be made able to detect that the cursor is within a fenced code block (only in the relevant file types) and send over the contents of the code block, but not the backticks. The appropriate `Escape_text` function could be selected based on the language indicated at the top of the fenced code block, e.g.

    ```python
    4 + 5
    ```

One approach of detecting language in code blocks [can be seen in the `vim-markdown` plugin's syntax file](https://github.com/vim-pandoc/vim-rmarkdown/blob/master/syntax/rmarkdown.vim).

In case you don't consider this worthwhile implementing, maybe a workaround could be added to the wiki? I am currently using the mappings below together with the default slime bindings and it is working quite well (just started so not sure about edge cases).

    autocmd FileType rmarkdown nmap <c-c><c-c> ?`<CR>j0v/`<CR>b$<c-c><c-c>
    autocmd FileType pandoc nmap <c-c><c-c> ?`<CR>j0v/`<CR>b$<c-c><c-c>

In the above commands, `rmarkdown` and `pandoc` are filtetypes assigned by `vim-pandoc` and `vim-rmarkdown`, they should be changed to whatever `:set ft` shows when in a `.md` or `.rmd` file. Since I mostly write Python, I just copied the `python` folder in `ftpplugin` and pasted as `rmarkdown` and `pandoc` folders together with changing the name of the `EscapeText_python` function to match the folders. This is of course not very flexible when writing in multiple languages.

**Comment by jpalardy** [comment]
Hi @joelostblom,

I'm happy that you're enjoying vim-slime!

This is a problem I face myself: how to copy-paste from triple-backquotes in Rmd files… In practice, I leave an empty line around the code to be able to select with `vip`. (the default way to "grab" with <kbd>ctrl-c</kbd><kbd>ctrl-c</kbd>)

If you're willing to code the ftplugins for this, I'll consider merging them. Presumably, it would be something like:
- if the first and last start with \`\`\`, remove those lines
- _or_, simpler, remove _any_ line starting with \`\`\`?

Let me know.

**Comment by joelostblom** [comment]
Thanks for the quick reply!

I am not very familiar with vimscript, so this solution is probably suboptimal by quite a bit, but it is what I came up with for now:

```
function! _EscapeText_rmarkdown(text)
  " Remove all fences
  let trimmed = substitute(a:text, '```{.*}\n', '', 'g')
  let trimmed = substitute(trimmed, '```\n', '', 'g')
  " Detect language
  if match(a:text,'```{python}') > -1
    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, trimmed, "--\n"]
  else
    return [trimmed]
  endif
endfunction
```

This worked well for me with short R and Python code blocks. There are some potential problems, such as that tripple backtick is stripped everywhere, even if it would be in a string that should be printed. For more languages, there would need to be a few else if statements.

Most importantly, I am not sure how to address multi paragraph code blocks, since `SlimeParagraphSend` only sends a single paragraph. Seems like this might need to happen outside of the ftpplugin and I am not quite sure how to go about that.

Meanwhile the keymapping I suggested above is still working without any edge cases, but it would be nice with language detection somehow.

**Comment by jpalardy** [comment]
Hi @joelostblom 

I'm definitely not a vimscript expert either … in fact, I've been thinking about extracting some of the functionality _out_ of the slime plugin into command-line filters. This would open up many possibilities:

- people wouldn't have to use vimscript (they could use any language they want)
- that code would live outside slime and be more easily switched and replaced
- smaller programs, possibly chainable?
- similar to what [ale](https://github.com/dense-analysis/ale), [syntastic](https://github.com/vim-syntastic/syntastic), etc... already do

You already identified the limitations of your code, and the challenges of making-it-work-for-all-cases … as for a more generic solution, it's a lot more work 😄

**Comment by pkyoung** [comment]
This is quite aged issue now, but do you have any progress with this?
I am looking for a simple way to ignore lines starting with triple backticks selecting lines as `vip`.
