### ISSUE TITLE
Sending Multiple line with visual block. pasted to multiple command line in ipython not to single command line

### ISSUE THREAD

**Issue by capitanoh** [jpalardy/vim-slime#210]
I'm new user of the vim-slime. I thinks this is wonderful plugin for vim environment.
But I have one problem about sending multiple line using the visual block to ipython.
(I'm working on IPython 7.4.0, Python 3.7.3, tmux 2.0, VIM - Vi IMproved 7.4 )
After making visual block all below code in vi and sending code with <c-c><c-c> 

When I send below code to ipython of tmux pane using visual block, below code are pasted in two command line.
It looks that the code are pasted separately to ipython command line becuase of the blank line (line number 5)

Is it Normal operation? or some bugs?

**- code in vi**
1 class test_class(object): 
2    def __ init __(self, args):
3      self.test_val  = 3
4
5      print(self.test_val)

**- ipython result in tmux pane**
**In [39]:** class test_class(object): 
    ...:     def __ init __(self, args):
    ...:       self.test_val  = 3
    ...:                                                                       

**In [40]:**     print(self.test_val)

NameError                                 Traceback (most recent call last)
<ipython-input-40-19edd1b87a61> in <module>
----> 1 print(self.test_val)
NameError: name 'self' is not defined

**what I expect :**
**In [39]:** class test_class(object): 
    ...:    def __init__(self, args):
    ...:      self.test_val  = 3
    ...:                                                                       
    ...:      print(self.test_val)                                                                       

Is there any solution to avoid to be pasted separately ?

**Comment by jpalardy** [comment]
Hi @capitanoh,

Before digging deeper, did you try [this](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python)?

**Comment by capitanoh** [comment]
Hi @jpalardy 

Yes, I've already added 'let g:slime_python_ipython = 1' in my  ~/.vimrc file.
It looks like that is not care about the blank line.

**Comment by jpalardy** [comment]
/sigh ipython …

I'll have to defer to someone who uses ipython with slime.

**Comment by kariya2** [comment]
This is normal operation, a block is a  section of code that has no blank lines between it, selected by vims `vip` command

**Comment by jpalardy** [comment]
closing as per @kariya2's comment.
