### ISSUE TITLE
Long text is not sent properly to tmux pane

### ISSUE THREAD

**Issue by slowkow** [jpalardy/vim-slime#211]
# Problem

When I use `Ctrl-c Ctrl-c` to send very short snippets of text from a tmux pane running vim to another tmux pane running R, it works perfectly.

However, when I send longer snippets of text, there seems to be a problem.

# Reproducible example

- Open a terminal and start a new tmux session.
- Open a pane for vim.
- Open a pane for R.
- Configure vim-slime to send to the R pane.
- Open the following R script and try to send the text to R.

Here is the R script `test-vim-slime.R`:

```r
f <- function(x) {
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  x <- x + 1
  print(x)
}
f(0)
```

After I do `Ctrl-c Ctrl-c`, I would expect to see the following content as the last lines in the tmux pane running R:

```
> f(0)
[1] 78
```

However, it seems that some of the text is not sent correctly, because this is what I actually see:

```
+   x <- x + 1
+   x <- x + 1
+   x   x   x   x   x  x)
Error: unexpected symbol in:
"  x <- x + 1
  x   x"
}
f(0)
> }
Error: unexpected '}' in "}"
f(0)
> f(0)
[1] 78
>
```

# Possible solutions

I also tried running the `load-buffer` and `paste-buffer` commands manually, without using vim at all, and I get the same error in the tmux pane running R.

These are the commands:

https://github.com/jpalardy/vim-slime/blob/dc8ca22cef3f87999d926e18e2e230145e013838/autoload/slime.vim#L74-L78

This leads me to believe that the issue I am facing is independent of vim and vim plugins like vim-slime.

I also tried using Terminal.app instead of iTerm2, and I got the same error.

So, the issue is probably caused by tmux or R, but I'm not sure which one.

If you have any tips or advice, I would greatly appreciate your help.

# System information

macOS Version 10.13.6
iTerm2 Build 3.3.1
tmux Version 2.8
vim Version 8.0

**Comment by slowkow** [comment]
I tried to reproduce this issue without using R at all. Instead, I send the `paste-buffer` contents to a tmux pane running vim. And it works perfectly!

So, at this point my understanding is that R is the cause of my issue.

This thread suggests that R can only accept 4095 bytes of pasted text in the console:

https://community.rstudio.com/t/does-console-impose-an-upper-limit-on-the-length-of-strings/12872/7

**Comment by jpalardy** [comment]
hi @slowkow,

hmmm… 4095 bytes doesn't seem random 😄 

Let me know if you think there's a tmux solution for this, otherwise I'll close in a few weeks.

**Comment by slowkow** [comment]
Hi @jpalardy, I think I have an idea for a workaround.

I noticed that you have a special function `_EscapeText` defined in `slime.vim`, and you allow the user to create additional functions for each filetype.

So, I tried to solve my issue with a hacky function in my `~/.vimrc`:

```vim
function! s:_EscapeText_r(text)
  let pieces = s:split(a:text, "\n")
  return pieces
endfunction
```

I can tell that my function is getting called now when I run `Ctrl-c Ctrl-c`, but it throws an error:

```
Error detected while processing function slime#send_op[19]..slime#send[6]..<SNR>83__EscapeText[4].._EscapeText_r:
E121: Undefined variable: text
```

If you could help me modify the `_EscapeText_r` function to split the text into a list of short strings, that should solve this issue for me.

Thanks for any help!

**Comment by jpalardy** [comment]
possible problem: the `s:` prefix  ?

**Comment by slowkow** [comment]
I am getting closer... but this function is still buggy, and it seems to work sometimes but not all the time.

Could I please ask for any hints?

```vim
function! _EscapeText_r(text)
  let l = strlen(a:text)
  if l < 4095
    return a:text
  endif
  let pieces = []
  let s = 0
  let e = min(s + 100, l)
  while s < l
    pieces += [a:text[s:e]]
    s = e + 1
    e = min(s + 100, l)
  endwhile
  return pieces 
endfunction
```

This function should split the text into chunks, so each chunk gets sent to R separately.

I don't know if this is the best approach, but I thought it was worth a shot.

Strangely, even when this function seems to work, my tmux pane navigation stops working after executing it. I don't understand why that would happen, and it is a deal breaker.

I think it's important to press <kbd>Enter</kbd> after sending each chunk, so I also tried `a:text[s:e] . '\n'`, but that seems to change nothing.

Thanks for any help or tips.

**Comment by jpalardy** [comment]
I don't think your first condition is correct:

```vim
  if l < 4095
    return a:text
  endif
```

it would return a string rather than an array of strings.

As for the rest … I am not a vim script expert 😄 … it looks good but it's hard to tell without debugging (try [echom](http://learnvimscriptthehardway.stevelosh.com/chapters/01.html) and `messages`).

Another approach would be to split on `\n` and gather pieces up to a length of 4095 🤔

**Comment by slowkow** [comment]
Finally, I found a function that works for me with R:

```vim
function! _EscapeText_r(text)
  call system("cat > ~/.slime_r", a:text)
  return ["source('~/.slime_r', echo = TRUE, max.deparse.length = 4095)\r"]
endfunction
```

And you can create an identical function called `_EscapeText_rmd` for R markdown files.

So, instead of sending the text into the tmux pane running R, we send the text into a file. Then, we can send a very short string to the tmux pane which tells R to source the file.

Ok, maybe now I can finally get back to work! 😄

**Comment by meriops** [comment]
FWIW, I have the same issue, but _only_ with  [randy3k/radian](https://github.com/randy3k/radian), not with the R console (nor with anything else). The last function proposed by @slowkow seems to solve the issue though...
