### ISSUE TITLE
can't send raw data to rpc channel ?

### ISSUE THREAD

**Issue by z-huabao** [jpalardy/vim-slime#212]
Hello, does it config right? 

![2019-08-22 10-53-50 的屏幕截图](https://user-images.githubusercontent.com/27676436/63482424-77deb500-c4cb-11e9-90da-14ac44cd2c73.png)

config as show above, and use default keybind `<C-c><C-c>` get error.

**Comment by z-huabao** [comment]
![2019-08-22 11-23-15 的屏幕截图](https://user-images.githubusercontent.com/27676436/63483526-4667e880-c4cf-11e9-93c5-c0cc68e4fc5c.png)
why different error now?

**Comment by jpalardy** [comment]
Hi @z-huabao 

Is this only happening for neovim? Did you try the tmux or screen mode?

Let me know.

**Comment by z-huabao** [comment]
tmux work well two days ago.
I install some plugins and chang some configs recently,  it don't work now:

    after setting 'socket name' and 'target pane', it show nothing, no error.

**Comment by jpalardy** [comment]
It's possible that different plugins interfere with each other.

Can you try "vim-slime only" to see if that works? Then, you can try adding plugins back one at a time.

**Comment by z-huabao** [comment]
Thanks,
I try "vim-slime only" , and it works with tmux. Then, I try adding plugins back, tmux works too???

but neovim always not work, same error as before(second picture).

**Comment by jpalardy** [comment]
I installed (from scratch) neovim, vim-slime and I'm able to send text into the `:terminal`

You seem to set the `g:slime_default_config`, could you try without it? (it's not containing the right config for neovim in the screenshot above)

**Comment by z-huabao** [comment]
Now find the problem(Neovim):

* plugin `davidhalter/jedi-vim` will cause the first pic error
* plugin `ncm2/ncm2` with setting `autocmd BufEnter * call ncm2#enable_for_buffer()` also cause fisrt error.
* setting `g:slime_default_config` cause second pic error even not use conflicting plugins above.

So, can you solve the conflict? 
And, I'd like setting `g:slime_default_config` with `target_pane=bottom`, not default right pane, can you solve it like tmux setting do?
Please!

**Comment by jpalardy** [comment]
I'm not sure neovim has a concept for "the bottom pane" … it seems to be numerical job ids.

**Comment by z-huabao** [comment]
how about a named terminal? And send code to this terminal
reference: [how-to-change-buffer-name-for-neovim-terminal-special-buffer](https://vi.stackexchange.com/questions/9566/how-to-change-buffer-name-for-neovim-terminal-special-buffer)

**Comment by jpalardy** [comment]
I'm not sure, I didn't write that part of the plugin.

Let me know if you come up with something.

**Comment by z-huabao** [comment]
No, I am not familiar with vimscript.
Recentlly, I want to have a special neovim terminal window, like IDE's console, to print log or run command or recieve `vim-slime` code, and it can be show/hide(don't kill) by a shortcut.

**Comment by jpalardy** [comment]
Yeah, vimscript isn't too fun 😢

**Comment by z-huabao** [comment]
:worried:

**Comment by z-huabao** [comment]
@jpalardy I have try to solve `rpc channel error` in [slime.vim](https://github.com/z-huabao/vim-slime/blob/81bd9b87a455b7b624b1199ae8127268969e77eb/autoload/slime.vim#L131)

And have make the features which I need, such as, `tareget_pane = bottom`, "named terminal window", "ipython cells", etc. 
my plugin: [z-huabao/vim-slime-ipython](https://github.com/z-huabao/vim-slime-ipython)

**Comment by jpalardy** [comment]
nice! 👍
