### ISSUE TITLE
EOF in triple-quoted

### ISSUE THREAD

**Issue by z-huabao** [jpalardy/vim-slime#213]
I use [Ultisnips](https://github.com/SirVer/ultisnips) to auto complete a function, which cause EOF error in triple-quoted, 
I don't think there are any invalid code.

![2019-08-23 11-10-38 的屏幕截图](https://user-images.githubusercontent.com/27676436/63564262-08ce9280-c597-11e9-85ad-86e32c94ba81.png)

**Comment by jpalardy** [comment]
hi @z-huabao 

Is this a problem with slime? Isn't just pasting exactly what's in your buffer?

As for the [code](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim#L8), is that what you would expect?

**Comment by z-huabao** [comment]
not really understand ...
can you tell me how to run the whole class above by `<Plug>SlimeParagraphSend`?
do I have to 'visual' whole class and use `<Plug>SlimeRegionSend` ?

**Comment by jpalardy** [comment]
There's no keyboard shortcut to "send the whole class" … that's python-specific.

You'll have to come up with the right logic for this and create your own shortcut.

**Comment by z-huabao** [comment]
Oh, thank for your ans!
I have try [https://github.com/hanschen/vim-ipython-cell](https://github.com/hanschen/vim-ipython-cell), which make vim like the Jupyter Notebook. And I wrongly thought your plugin can replace all of it, but it not running very well on marks mode.

**Comment by jpalardy** [comment]
sorry to hear that :-(
