### ISSUE TITLE
Send to external terminal window (e.g. gnome-terminal window)

### ISSUE THREAD

**Issue by KShutter** [jpalardy/vim-slime#215]
Is there a way to use vim-slime to send code/text to an external (to vim) terminal window (not talking about using multi-screen software like tmux, just solo independent terminal window)? For instance, if under Linux, to send to a gnome-terminal window (e.g. selecting target window by PID). This functionality would allow for such a great flexibility in setting up work-flows.

For example, it would make it easy to work with vim + vim-slime in a multiple monitors setup without having to resort to more invasive solutions like GNU Screen or Tmux.

**Comment by jpalardy** [comment]
Hi @KShutter,

vim-slime needs a "target": software that can receive the characters and use them (somehow). In practice, that means `GNU Screen / tmux / whimrepl / ConEmu session / NeoVim Terminal / Vim Terminal`, as listed [in the README](https://github.com/jpalardy/vim-slime).

It's not especially hard to add support for new software -- but the software must allow for this type of "scripting".

As for multiple monitors setup, that's not limited by tmux in itself. Whatever target you have (gnome-terminal) on whatever monitor, you can run tmux inside it, no?
