### ISSUE TITLE
how do I map something that would send the whole file/buffer?

### ISSUE THREAD

**Issue by BradleySmall** [jpalardy/vim-slime#216]
I would like to send the whole buffer/file over to the REPL. But I can't seem to make a map to do it. I was able to do a key macro like magg\sG`a but not sure how to map that to a key

Something like this: 
nmap <f5> magg<Plug>SlimeMotionSend()G`a

**Comment by jpalardy** [comment]
Hi @BradleySmall,

I'm not an expert: I had to try a few things, but here's what I came up with:

```nmap <c-c><c-x> :%SlimeSend<cr>```

(map <kbd>ctrl-c</kbd><kbd>ctrl-x</kbd> to SlimeSend the whole file)

does that work for you?

**Comment by BradleySmall** [comment]
That works!

I did find a way to tell the python REPL to run the file from disk, probably what I actually want to do anyway...

nmap <f5> :w<cr>:SlimeSend0 "exec(open('" . expand('%:p') . "').read())\n"<CR>

**Comment by jpalardy** [comment]
oh, nice!

I'm glad you could make it work 👍
