### ISSUE TITLE
Question: how to setup `g:slime_vimtermial_config` ?

### ISSUE THREAD

**Issue by hieuvijjo** [jpalardy/vim-slime#217]
I would like to run commands without being asked for `config`. Which options should I put into `g:slime_vimterminal_config`? I read the doc but couldn't find any information.
Thank you!

**Comment by jpalardy** [comment]
Hi @hieuvijjo,

The variable you're looking for is `g:slime_default_config`, which you would set to the values needed for your specific "receiver" (vimterminal in your case).

```vim
" for example...
let g:slime_default_config = {"bufnr": "XXX"}
```

You can refer to the [code](https://github.com/jpalardy/vim-slime/blob/master/autoload/slime.vim#L182-L219) (unfortunately) for other config.

If you think you can make this clearer for the next person, I'm willing to discuss a documentation PR, let me know.

**Comment by hieuvijjo** [comment]
Hi @jpalardy,

There is a slight issue. The buffer number for the terminal can change wildly, depending on how I open previous buffers. Is there a default value that I can set, say `0`, to immediate send texts to the opened vim terminal, or a newly created terminal if there's none open?

Thank you for your responsive response!

**Comment by jpalardy** [comment]
I don't use vimterminal, so that's hard to say…

I'm sure there's a way to automate some of this, but you would have to read the doc.

**Comment by victorkristof** [comment]
HI there, maybe this can help @hieuvijjo? You could do something like this:
```
" Create new vertical terminal.
:terminal
" Get terminal buffer number.
:let bufnr = term_list()[0]
" Set Slime to pick terminal.
:let g:slime_default_config = {"bufnr": bufnr}
```

The function `term_list()` returns a list of `Numbers`, where each entry is the buffer number of an open terminal. If there is only one terminal open, then `term_list()[0]` will give you its buffer number. If there you have opened several terminals, then `term_list()[0]` will pick up the most recent opened terminal.

The help  says:
```
:h term_list()
Return a list with the buffer numbers of all buffers for terminal windows.
```
