### ISSUE TITLE
display which panel is connected

### ISSUE THREAD

**Issue by slowkow** [jpalardy/vim-slime#219]
I often have tmux sessions with 2 vim panels and 2 REPL panels. Sometimes I open more panels and then I forget which vim panel is connected to which REPL panel.

It would be very helpful if the vim session would show me which tmux panel is connected with `vim-slime`, right next to the name of the currently open file.

Could I please ask if you might be able to help me figure out how to do this? If I get a chance, I might try to hack this together myself, but I'm not sure where to start.

For example, right now the last line in my vim panel looks like this:

```
NORMAL  .vimrc
```

And I would like it to look like this instead:

```
NORMAL  .vimrc  tmux-slime:1.2
```

I'd be thrilled if you would consider adding this feature. Thanks!

**Comment by jpalardy** [comment]
Hi @slowkow ,

As far as I understand, this is something you can do yourself: you can [customize your statusline](https://shapeshed.com/vim-statuslines/).

For example, I tried `set statusline=%{b:slime_config['target_pane']}` and that works 😄 

Let me know how that goes.

**Comment by slowkow** [comment]
Thanks!

That seems to work. Could I please ask if you know how to customize the status line?

Here's what I added to my `~/.vimrc`:

```
function! StatusSlime()
  if exists("b:slime_config")
    let l:target = b:slime_config['target_pane']
    return strlen(l:target) > 0 ? '  '.l:target.' ' : ''
  endif
  return ''
endfunction

set statusline+=%{StatusSlime()}
```

When I'm in a vim session, I can get the `1.3` to appear in my statusline after executing `:source ~/.vimrc`.

The `1.3` appears briefly, and then it reverts back to the regular statusline that shows the current filename, etc.

Also, my code seems to add the `1.3` string over and over, so eventually the statusline looks like `1.3  1.3  1.3  1.3`.

Do you know how to add this string to the "default" statusline so I don't need to execute `:source ~/.vimrc`?

**Comment by jpalardy** [comment]
Not sure, it depends what the rest of your vim config looks like.

If you have another plugin tweaking the `statusline`, it might overwrite your assignment.

**Comment by slowkow** [comment]
@jpalardy Thanks for your patience. I spent some time learning about this today, and my approach using `set statusline` was not the right way to go.

In my `~/.vimrc` I noticed that I am using [lightline.vim](https://github.com/itchyny/lightline.vim) to configure the statusline.

My new statusline looks like this when vim-slime is configured to send to tmux panel `:.1`:

```
NORMAL  python-figure-panels.py | :.1

                                  ^-- There it is! Hooray!
```

This is how I configured lightline to show the panel.

```vim
let g:lightline = {
  \   'colorscheme': 'seoul256',
  \   'active': {
  \     'left': [ [ 'mode', 'paste' ],
  \               [ 'readonly', 'filename', 'modified', 'slimetarget' ] ]
  \   },
  \   'component_function': {
  \     'slimetarget': 'SlimeTarget'
  \   }
  \ }

function! SlimeTarget()
  if exists("b:slime_config")
    let l:target = b:slime_config['target_pane']
    return strlen(l:target) > 0 ? l:target : ''
  endif
  return ''
endfunction
```

Thank you for making vim-slime!

**Comment by jpalardy** [comment]
I'm glad you found a way 👍
