### ISSUE TITLE
how to send the function which have blank line.

### ISSUE THREAD

**Issue by capitanoh** [jpalardy/vim-slime#222]
Hi, 
I'm trying to send the code to ipython pane using the vim-slime.
When I send the functions using Ctrl+c+c with the visual block in vim, 
The code of functions are separated into two codes cell in ipython if there is blank line.

I want to send the all function codes to one cell of ipython even if there is blank line.
Is there any way to send all selected code(by visual block in vim) to one cell of ipython?

ipython 7.6.1
VIM - Vi IMproved 8.0
tmux 2.6
Python 3.7.3

![image](https://user-images.githubusercontent.com/49934546/72545650-ad49cc00-38cc-11ea-9c1f-fbe413b31bc5.png)

**Comment by jpalardy** [comment]
Hi @capitanoh,

You're right about the defaults in vim-slime… but the good news is that anything-is-possible™  … if you can think of the logic you need to decide what constitutes a "chunk" to send over, you can select before you invoke the bindings to send the text over.

At one extreme, it means manually selecting your text before pressing `ctrl-c, ctrl-c`

At the other extreme, it would mean writing some custom vimscript to automate the process.

**Comment by vhristev** [comment]
I have the same issue with bpython. I want to use ctlrl-C C to send all lines of my code without selecting it. 
I know i can select line 1,2,3 and send it or just point my cursor over line 5 and execute it but if i have simple code below i just send x and y and stop before the 'if' statement. I want to have easy way to pres CTRL + CC and execute entire code not partion of it. 

```
x = 10
y = 20 

if x < y:
    print('Nice)
```

**Comment by jpalardy** [comment]
Hi @vhristev,

How would vim-slime know what to grab and when to stop? 🤔 

If selecting code manually is too tedious, you can use <kbd>{</kbd> and <kbd>}</kbd> to move one paragraph at a time.

**Comment by vhristev** [comment]
I assume it sending the entire code from first to the last line it seems its not working like that which is my bad not to read carefully. I know how to select all lines at once and then execute CTRL + CC just searching if someone did map to run them all at once. Something like` !python '%'`

**Comment by capitanoh** [comment]
> Hi @capitanoh,
> 
> You're right about the defaults in vim-slime… but the good news is that anything-is-possible™ … if you can think of the logic you need to decide what constitutes a "chunk" to send over, you can select before you invoke the bindings to send the text over.
> 
> At one extreme, it means manually selecting your text before pressing `ctrl-c, ctrl-c`
> 
> At the other extreme, it would mean writing some custom vimscript to automate the process.

**Comment by capitanoh** [comment]
Hi, @jpalardy 

In the above image, 
I was tried 'manually' selecting the my text using the visual block of vim(which is from line.2 ~ line.10) and then pressing ctrl-c, ctrl-c. 
but, selected text was pasted into two cell divided by 'blank line'. 
I thinks It is a clear what constitutes a "chunk" to send over,  if i select it by visual block of vim. 

Like above image, my use case is very simple sending function code which have blank line.
(but currently I can't send the function code if there is blank line.)
I thinks It will be very useful to send function code to ipython, Cuz most of function code will have a blank line in function.

Is there any trick or small modification to send selected text(even if there is blank line) to one cell of ipython? Or Is any way to send function code(which have blank line) to one cell of ipython ?

**Comment by jpalardy** [comment]
Hi @capitanoh,

Have you tried [this](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python)? I'm not a ipython user myself but this is probably a good place to start.

**Comment by capitanoh** [comment]
Hi, @jpalardy 
below option value was already added in my .vimrc file.  😭 
let g:slime_python_ipython = 1

**Comment by jpalardy** [comment]
I was afraid of that…

You can read the [python plugin](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim) directly (it's less than 20 lines of code) and let me know if that helps pinpointing the problem.

**Comment by lodagro** [comment]
@capitanoh Is the file you are editing a python file (_.py_ extension)? If not, the mentioned plugin is not loaded. I enabled ```let g:slime_python_ipython = 1``` and it resolved the issue of blank lines in IPython.

**Comment by capitanoh** [comment]
Hi, @lodagro 
I was editing the python file(xx.py). On my side,  If there is blank line in the code, it were pasted into two cells of ipython.
You can see the file name as test.py on the right bottom of my screenshot.
If works well on your side, Could you tell me your environment?

ipython - 
VIM - 
tmux - 
Python - 
vim-slime -

**Comment by lodagro** [comment]
Do you get the ```%cpaste -q``` ?

For example:
*.py file with
````
test_val = "hello"

print(test_val)
````

result in IPython is

```
In [2]: %cpaste -q
test_val = "hello"

print(test_val)
--
hello
```

ipython - 7.8.0
VIM - 8.2 (including patches 1-14)
tmux - 2.8
Python - 3.7.3
vim-slime - master cf896c1

**Comment by capitanoh** [comment]
Hi @lodagro 

Thanks for kind example.
As you told me, If i copied the code manually and then paste the code manually to ipython cell after %cpaste -q.
It is works well I expected.

**But My question** was sending code and then run code automatically  using just vim-slime shortcut (Ctrl+c, Ctrl+c)
(Do not enter %cpaste -q, paste code, and  '--')

My scenario is like below. 
1. Open the vim(*.py) and ipython on the tmux. 
2. Select the code(which include the blank line) using the **visual block of VIM** (refer to my first image)
3. Sending the code(which include the blank line) using the **vim-slime shortcut (Ctrl+c, Ctrl+c)**
4. (Result ) Code should be pasted in one cell of ipython and worked well.


Plus, When I checked python plugin code on my pc, '%cpaste -q ' looks used.
(vi ~/.vim/bundle/vim-slime/ftplugin/python/slime.vim)
```
if !exists("g:slime_dispatch_ipython_pause")
  let g:slime_dispatch_ipython_pause = 100
end
function! _EscapeText_python(text)
  if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
  else
    let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
    let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
    let dedent_pat = '\(^\|\n\)\zs'.matchstr(no_empty_lines, '^\s*')
    let dedented_lines = substitute(no_empty_lines, dedent_pat, "", "g")
    let except_pat = '\(elif\|else\|except\|finally\)\@!'
    let add_eol_pat = '\n\s[^\n]\+\n\zs\ze\('.except_pat.'\S\|$\)'
    return substitute(dedented_lines, add_eol_pat, "\n", "g")
  end
endfunction
```

Is there any solution?

**Comment by lodagro** [comment]
The example i showed used your four step scenario, so i did no manual cut&paste. ```vim-slime``` does the transfer from my text file to the IPython pane and adds the ```%cpaste -q``` block, after which the code is ran automatically. My cursor did not leave the vim-pane.

In your image at the top of this thread there is no ```%cpaste -q``` in the IPython part. Although you have set ```let g:slime_python_ipython = 1``` in your ```.vimrc```. So i was wondering why it is missing. Possible option was that the file under edit did not have ```ft=python``` set, this way the vim-slime python plugin is not loaded. But this is not the case since you edit a ```*.py``` file (for which ```ft=python``` is set automatically).

In vim, when you have your python code loaded can you check the output of the command ```: let g:slime_python_ipython```, it should give 1 as a result? You can also check ```:set ft```, it should return ```filetype=python```.

**Comment by capitanoh** [comment]
Hi @lodagro 
Thanks for detailed explanation, I understood what you wonder for my issue. 
when i check the g:slime_python_ipython option and ft, It returned 1 and python like below image.
Plus, even if i removed "exists('g:slime_python_ipython') && " condition like below code, It is still pasted into two cell. 

If it works well,  "%cpaste-q" and "--" texts should appeared in ipython pane ?
If so, It looks like that 'python/slime.vim' file or '_ExcapeText_python' function are not launched on my side..
Do you know other check point for this issue? 

```
##vi ~/.vim/bundle/vim-slime/ftplugin/python/slime.vim

function! _EscapeText_python(text)
  if len(split(a:text,"\n")) > 1      #Removed "exists('g:slime_python_ipython') &&"
    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
```
![image](https://user-images.githubusercontent.com/49934546/73899052-c1cb2400-48ce-11ea-8f0f-62629cae7c61.png)
![image](https://user-images.githubusercontent.com/49934546/73899059-c7c10500-48ce-11ea-8d06-3e2f8f8658f2.png)

**Comment by jpalardy** [comment]
hi @capitanoh,

can you try `:scriptnames` and see what gets loaded by vim?

You can also use [:echom](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html) if you need to add some "tracing" to the vim files…

**Comment by capitanoh** [comment]
Hi, @jpalardy 
When I checked the loaded script, Only I found the  31:~/.vim/bundle/vim-slime/plugin/slime.vim script. 
 
"~/.vim/bundle/vim-slime/ftplugin/python/slime.vim" should be loaded ?

```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim80/debian.vim
  3: /usr/share/vim/vim80/syntax/syntax.vim
  4: /usr/share/vim/vim80/syntax/synload.vim
  5: /usr/share/vim/vim80/syntax/syncolor.vim
  6: /usr/share/vim/vim80/filetype.vim
  7: ~/.vimrc
  8: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  9: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 10: ~/.vim/bundle/The-NERD-tree/plugin/NERD_tree.vim
 11: ~/.vim/bundle/The-NERD-tree/autoload/nerdtree.vim
 12: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/path.vim
 13: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/menu_controller.vim
 14: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/menu_item.vim
 15: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/key_map.vim
 16: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/bookmark.vim
 17: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/tree_file_node.vim
 18: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/tree_dir_node.vim
 19: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/opener.vim
 20: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/creator.vim
 21: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/flag_set.vim
 22: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/nerdtree.vim
 23: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/ui.vim
 24: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/event.vim
 25: ~/.vim/bundle/The-NERD-tree/lib/nerdtree/notifier.vim
 26: ~/.vim/bundle/The-NERD-tree/autoload/nerdtree/ui_glue.vim
 27: ~/.vim/bundle/The-NERD-tree/nerdtree_plugin/exec_menuitem.vim
 28: ~/.vim/bundle/The-NERD-tree/nerdtree_plugin/fs_menu.vim
 29: ~/.vim/bundle/Tagbar/plugin/tagbar.vim
 30: ~/.vim/bundle/taglist.vim/plugin/taglist.vim
 31: ~/.vim/bundle/vim-slime/plugin/slime.vim
 32: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 33: /usr/share/vim/vim80/plugin/gzip.vim
 34: /usr/share/vim/vim80/plugin/logiPat.vim
 35: /usr/share/vim/vim80/plugin/manpager.vim
 36: /usr/share/vim/vim80/plugin/matchparen.vim
 37: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 38: /usr/share/vim/vim80/plugin/rrhelper.vim
 39: /usr/share/vim/vim80/plugin/spellfile.vim
 40: /usr/share/vim/vim80/plugin/tarPlugin.vim
 41: /usr/share/vim/vim80/plugin/tohtml.vim
 42: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 43: /usr/share/vim/vim80/plugin/zipPlugin.vim
 44: /usr/share/vim/vim80/syntax/python.vim
 45: ~/.vim/bundle/The-NERD-tree/syntax/nerdtree.vim
```

**Comment by jpalardy** [comment]
Hi @capitanoh,

Before using slime, on a `.py` file:

- [...]slime/plugin/slime.vim
- [...]slime/ftplugin/python/slime.vim

After <kbd>ctrl-c</kbd> <kbd>ctrl-c</kbd>, add:

- [...]slime/autoload/slime.vim

I think you're using vundle, have you considered using vim's package loading? (if only as a test?)

**Comment by capitanoh** [comment]
Hi, @jpalardy @lodagro 

As you guys comments, filetype plugin were not loaded on my side even if filetype is python.
I've added the below option to my .vimrc by searching it on google.
`filetype plugin on`

After that, [...]slime/ftplugin/python/slime.vim is loaded and works very well.
Thanks to @jpalardy and @lodagro.
Finally, Vim-slime has been lovely and perfect tools for me. 😄

**Comment by jpalardy** [comment]
Glad to hear it 👍
