### ISSUE TITLE
IPython cpaste fails with vim terminal on windows 

### ISSUE THREAD

**Issue by schmidf** [jpalardy/vim-slime#223]
g:slime_python_ipython can be set to 1 in order to avoid issues when sending python code to the ipython interpreter. This automatically prefixes the paste with the %cpaste magic and adds the required "--" suffix.

This works fine when using ipython in the built-in vim terminal on Linux. On Windows however, the "--" line triggers a SyntaxError in IPython. I have also noticed that without this option the terminal behaves slightly differently. In Linux the code gets executed immediately after triggering vim-slime, whereas in Windows I have to switch to the terminal and press enter. I guess that this is the reason why the cpaste-mode doesn't work.

I am using the current version of IPython (7.11.1) on Python 3.6.6 and VIM 8.1.

**Comment by jpalardy** [comment]
Hi @schmidf,

I'm neither a Windows user nor a IPython one…

Do you have a workaround for this?

**Comment by Eason0210** [comment]
Hi @jpalardy ,

I have the same issue, and  you can reproduce the issue with my minimal vimrc. 
It worked well in Mac OS with macvim.

OS: Windows 10 pro  (1903)
vim：gvim 8.2
Python： Python 3.8.1
IPython：7.11.1

<img width="368" alt="version" src="https://user-images.githubusercontent.com/47546452/73344411-4c06fd00-42bd-11ea-8f5e-cbf66ddadc45.png">

<img width="408" alt="error" src="https://user-images.githubusercontent.com/47546452/73344426-52957480-42bd-11ea-98b8-02834adad9aa.png">



My vimrc config is as follow:

set nocompatible
set shortmess=atI
set langmenu=en_US
let $LANG='en_US'

filetype plugin indent on
syntax on

call plug#begin('~/.vim/plugged')
Plug 'jpalardy/vim-slime'
call plug#end()

let g:slime_target = "vimterminal"
let g:slime_python_ipython = 1

**Comment by Eason0210** [comment]
Hi @jpalardy ,
This issue is similar to #172 Paste issue in IPython 7.0.1

**Comment by jpalardy** [comment]
Would it work if an extra "newline" was attached to the string payload?

**Comment by Eason0210** [comment]
Hi @jpalardy ,
yes, It work well if I select extra "newline" and send the selected code.

**Comment by jpalardy** [comment]
@schmidf how about you?

Would either of you be interested in creating a PR for this?

- modifying the [python plugin](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim) -- possibly with a configuration flag if you cannot find a way to make it work in both circumstances
- appropriate updates to the [python README](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python) and [global README](https://github.com/jpalardy/vim-slime) as necessary

**Comment by schmidf** [comment]
I have now done some more testing by calling `term_sendkeys()` directly. ipython on Windows has a rather bizarre behavior regarding newlines:
- In regular mode, `"line\n"` directly executes a line of code. `"line\r"` also inserts a line of code followed by a line break, but does not execute it. All lines entered this way can then be executed as a block by sending `"\n"`
- In paste mode (activated by sending `"%cpaste -q\n"`), `"line\n"` **does not** insert a newline. Only `"line\r"` works correctly. The code is then executed by sending `"--\r"`.

On Linux there is no difference between `"\r"` and `"\n"` in ipython.

When using the vim terminal, slime ends each line with `"\r"` (I think): https://github.com/jpalardy/vim-slime/blob/cf896c1f4f37a9feb15d657dfd120aeeb6215ad8/autoload/slime.vim#L169
This means that no python code gets executed unless the user hits enter manually in the terminal. It also explains the syntax error when setting `g:slime_python_ipython`. For paste mode to work, `"%cpaste -q"` has to be called **before** pasting the rest of the code.

So in order to get ipython to work properly, slime would have to do the following:
- Without `g:slime_python_ipython` set: End each line with `"\r"` and the block of code with `"\n"` to execute.
- With `g:slime_python_ipython` set: First send `"%cpaste -q\n"` , then the code lines ended with `"\r"`, then `"--\r"`.

As far as I can tell, slime currently sends a wild mix of `"\r"` and `"\n"`. I am not very familiar with vimscript, so I haven't been able to easily make the changes. It is also worth noting that the regular python interpreter on Windows completely ignores `"\n"`, so it might not even be possible to find a default solution that works with both python and ipython.

**Comment by jpalardy** [comment]
Interesting, I hadn't connected the interaction between the python plugin and "vim terminal" mode:

![newline-interaction](https://user-images.githubusercontent.com/18142/73600271-988f4a00-4502-11ea-9bb0-848982beef3c.png)

In fact, I'm not sure (since I didn't write that code) why it substitutes the newlines `\n` with carriage returns `\r`…

I'm open to suggestions on this.
