### ISSUE TITLE
Feature for opening a new pane in tmux

### ISSUE THREAD

**Issue by kvngvikram** [jpalardy/vim-slime#224]
I have been using vimux until now, and it has a function to open a new vimux pane(make a tmux split).
This can be done manually but I want to have a mapping inside vim where a new pane is opened/split and some commands are entered. For example <my mapping> opens a new pane and enters ipython so now I have a ipython pane to send my code lines.
Is it possible to do such things with vim-slime may be using a similar function as Vimux?

**Comment by jpalardy** [comment]
Hi @kvngvikram,

I initially thought:

>With vim mappings, this sounds very feasible

but now I'm not so sure. I can imagine ways to script tmux from vim (that's what vim-slime does) but for specific commands, I would have to look it up. (or look at what vimux is doing)

How close does [this](https://stackoverflow.com/questions/5609192/how-to-set-up-tmux-so-that-it-starts-up-with-specified-windows-opened) get you to what you want to do?

**Comment by kvngvikram** [comment]
Yes, your link does the job. I am using the following mapping
	`map <some keys> :!tmux split-window -d 'ipython'<CR>`

It is easier than I thought. I can also send keys etc with tmux commands after :! .
Just curious, any plan for adding more functions to do such things?
Anyway thanks for you replay.

**Comment by jpalardy** [comment]
Hi @kvngvikram,

Glad it was easier than we expected ~ that's often not the case 🤔 

As for adding this to vim-slime itself, I feel it's outside the scope of what it does best. Opening splits (or similar customizations) quickly falls under personal preferences … of which there are MANY.

Maybe it's better if these add-on behaviors have their own (github) projects. I could link them from the README as needed.
