### ISSUE TITLE
vimterminal with belowright

### ISSUE THREAD

**Issue by m-wells** [jpalardy/vim-slime#226]
Typically one could call `:belowright terminal` but I have been unable to find in the code where `terminal` actually gets called to prepend a `g:slime_vimterminal_cmdmod` (where `g:slime_vimterminal_cmdmod = "belowright"`).

**Comment by jpalardy** [comment]
Hi @m-wells,

I didn't write the `terminal` plugin, but if it works like the other plugins, vim-slime expects the terminal to be open and ready by the time you call <kbd>ctrl-c</kbd><kbd>ctrl-c</kbd>

If you want to open the terminal belowright, you could package that functionality in a mapping, before the call to vim-slime.

**Comment by m-wells** [comment]
Simplest  workaround that I could find is to do
```vimrc
set splitright
set splitbelow
```
This will ensure that the terminal opens below any splits.  If there are any vertical splits it will open in the right-most split at the bottom.

This does mean that any `[v]new` command will open in the bottom right but I rarely use `[v]new` directly so this is a satisfactory workaround for my use.  Also, `split [file]` opens below and `vsplit [file]` opens to the right which is okay with me.  A better solution would be something that only changed the behavior of the `terminal` window.

**Comment by victorkristof** [comment]
@m-wells You could maybe add a wrapper function in your vimrc:
```
function! OpenTerminalBelowRight()                
    " Create new terminal below right and run ipython.                
    belowright terminal ipython                         
    " Get the terminal buffer number.                  
    let l:bufnr = term_list()[0]                   
    " Connect Slime to this terminal.                  
    let g:slime_default_config = {"bufnr": l:bufnr}
    " Don't prompt for termnal.
    let g:slime_dont_ask_default = 1
endfunction               
```

Then you would just `:call OpenTerminalBelowRight()` to launch your terminal below right with ipython and start using vim-slime.
