### ISSUE TITLE
Capturing output (getDifference branch current state)

### ISSUE THREAD

**Issue by dyamon** [jpalardy/vim-slime#228]
Hi,

I noticed there is a `getDifference` branch that tries to implement a way to capture the output of the command sent with Slime. I wonder what is the current state of the feature and why it was never included in `master`.

To me it seems a nice feature to have and I have a use case for it too:

Working with Scala + sbt I usually keep a Tmux pane open with sbt running. This tends to be useful for compiling the latest changes on your code base or just jump to a Scala console (within sbt) and test something. In this case I can send a `compile` command to the sbt pane via Slime but I would like to capture the output and feed it in Vim quickfix list.

**Comment by jpalardy** [comment]
Hi @dyamon,

vim-slime runs in a variety configurations, it would be challenging to provide support beyond the most popular options (screen, tmux).

As such, complexity-wise, I don't think I could maintain the extra functionality.
