### ISSUE TITLE
"Slurped X characters into buffer" message

### ISSUE THREAD

**Issue by idbrii** [jpalardy/vim-slime#23]
Every time I trigger a send to slime, my screen session gives a message: "Slurped X characters into buffer." This message stays on the screen for several seconds before anything happens. Is it possible to disable it?

I found a similar issue on another screen plugin, but I can't figure out how to apply it to slime:

https://github.com/ervandew/screen/issues/4

**Comment by travis-rodman** [comment]
Thanks for writing up the code modification @idbrii, I was having the same issue, helped out a lot.

**Comment by travis-rodman** [comment]
actually, that borked my send after the second call... apparently is set a global variable and only the original command was sent again :/
