### ISSUE TITLE
Command to send command instead of selection

### ISSUE THREAD

**Issue by astier** [jpalardy/vim-slime#230]
Hello. Would it be possible to implement a command like `:SlimeCommand cat %` which would send in this case the command ls with the path of the current file instead of the current selection?
I would like to use slime like [neoterm](https://github.com/kassio/neoterm) but for tmux. Right now I have to use vimux beside slime which is unfortunately not maintained anymore. Also both functionalities seem to be related and could be implemented in one single plugin, just like in neoterm.

edit: I meant cat and not ls

**Comment by jpalardy** [comment]
hi @astier,

You can look at [SlimeSend0](https://github.com/jpalardy/vim-slime/blob/master/plugin/slime.vim#L13) as a starting point. I use that command to send "exact text" to vim-slime, here's an [example](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L21-L22).

Step-wise, I can see:
- running the external command
- capturing the output
- pushing it through SlimeSend0

If the code makes sense (and isn't too big), I would considering adding it to vim-slime.
