### ISSUE TITLE
Send Keybindings instead of String

### ISSUE THREAD

**Issue by jgonsior** [jpalardy/vim-slime#231]
Hey, I'm not sure if that is possible, but I'd like to send a Ctr+C sequence to a tmux pane in order to kill the running program there via a keybinding from vim. Is that possible with slime?

I've managed so far, to save the current file and rerun the last command in a tmux pane using:
`nmap <localleader>r :w <bar> :SlimeSend1 !! <CR>`

But now I also want to include to first kill the running command in the pane and restart it.
What I've tried without success so far:
`nmap <localleader>r  :SlimeSend1 <C>C <bar> :w <bar> :SlimeSend1 !! <CR>`
and 
`nmap <localleader>r  :SlimeSend1 ^C <bar> :w <bar> :SlimeSend1 !! <CR>`

**Comment by jgonsior** [comment]
I'm able to execute what I want using `tmux send-keys -t {last} ""  C-c` now, but I'm wondering if it can be also achieved using vim-slime.

**Comment by jpalardy** [comment]
hi @jgonsior,

I use this in my vimrc config: 

`nmap <c-c><c-u> :SlimeSend0 "\x15"<CR>`

It sends a <kbd>ctrl-u</kbd> through vim-slime. I just tried the same with `\x03` (aka <kbd>ctrl-c</kbd>) and it seems to work.

Let me know

**Comment by jgonsior** [comment]
Thanks a lot, that did the trick! I used SlimeSend1 instead of SlimeSend0 in combination with "x03", but now I know the difference!

**Comment by jpalardy** [comment]
awesome 👍
