### ISSUE TITLE
Sending commands to multiple panes

### ISSUE THREAD

**Issue by jessesimpson36** [jpalardy/vim-slime#233]
Hey everyone,

As a operations guy at my current job who maintains a couple dozen VM's of the same application, it would be really nice to be able to send commands to multiple tmux panes. Using the following patch I created, I was able to do that in tmux.  (I did not include patches for screen or other terminal splitting software).

The main change here was just that I changed the config to allow target_pane  to be comma-separated.

```diff
> git diff
diff --git a/autoload/slime.vim b/autoload/slime.vim
index f317062..064b430 100644
--- a/autoload/slime.vim
+++ b/autoload/slime.vim
@@ -72,9 +72,11 @@ function! s:TmuxCommand(config, args)
 endfunction
 
 function! s:TmuxSend(config, text)
-  call s:WritePasteFile(a:text)
-  call s:TmuxCommand(a:config, "load-buffer " . g:slime_paste_file)
-  call s:TmuxCommand(a:config, "paste-buffer -d -t " . shellescape(a:config["target_pane"]))
+  for pane in split(a:config["target_pane"], ",")
+    call s:WritePasteFile(a:text)
+    call s:TmuxCommand(a:config, "load-buffer " . g:slime_paste_file)
+    call s:TmuxCommand(a:config, "paste-buffer -d -t " . shellescape(pane))
+  endfor
 endfunction
 
 function! s:TmuxPaneNames(A,L,P)
```

Quick demo:
[Asciinema Demo](https://asciinema.org/a/MTIgd4WaC2BkHuUNoI2qHMaNH
)
Yesterday, I was able to use one vim session and do things like set up logical volumes, reverse proxies, or just simply monitor deployments of our application just by writing the commands once.  

I'm putting this here in "Issues"  because I wanted a discussion around if this hack was a part of the vision of this project, and if I start wrapping other shells in for loops, separated by commas,  would such a thing get merged in assuming we had support for other things like screen, kitty, and whatever else slime is compatible with?

**Comment by jessesimpson36** [comment]
Heres a fork to test out
[jessesimpson36/vim-slime](https://github.com/jessesimpson36/vim-slime)

**Comment by jpalardy** [comment]
Hi @jessesimpson36,

Could the same effect be achieved using [synchronize-panes](https://sanctum.geek.nz/arabesque/sync-tmux-panes/)? Targeting any of the panes would copy to all other panes?

In that case, no changes would be required to vim-slime (except possibly a documentation patch to explain this technique)

Let me know

**Comment by jessesimpson36** [comment]
Woah. That's really handy!   Personally I still like using slime with my patch for this so that I get access to vims functionality, and get to save a bash/python/database script at the end.

I guess what I could do is use the synchronize-panes function on one terminal and have slime send output to that, which in turn sends the output to the output panes.  It's an extra step that would accomplish the same goal.

**Comment by jessesimpson36** [comment]
I'll play around with using synchronize-panes and see if the workflow is better/worse. Since there is a workflow that supports my needs without this patch, I wouldn't be hurt if you closed the issue.

**Comment by jpalardy** [comment]
ok, closing for now 👍 

but let me know how the different flows work for you (maybe replying to this thread)

**Comment by ScrumpyJack** [comment]
That's weird, it doesn't seem to work with synchronize-panes

If i set the slime target-pane to a window with a bunch of panes that are synchronized, it only sends to the first pane

**Comment by ScrumpyJack** [comment]
I like @jessesimpson36 's patch. I've applied it.
This means that you can now send to multiple panes inside multiple windows.
Great for ops stuff.

**Comment by pdex** [comment]
synchronized-panes does not work with this solution: https://stackoverflow.com/questions/52287388/is-it-possible-to-paste-in-all-tmux-panes-simultaneously-using-tmux-copy-paste

Would you be willing to accept a pull request that creates a new command for sending to multiple panes?

**Comment by jpalardy** [comment]
@pdex 

I'm not technically against this patch, though I have some concerns over how we expect the user to configure this
- ironically, I'm OK with "no hand-holding" — if users know this feature exists and create the list themselves  ✅ 
- or if there's an obvious way to facilitate this 🤔 

What I'm trying to avoid is complicated the existing functionality (or flow) for this case.

**Comment by pdex** [comment]
@jpalardy I'm trying to gauge if it makes sense to make the change in this repo (I took the comma separated list idea and got it working with the existing code base). Or if I should just fork this repo for my use case (sending the same blocks of text to two different repls that need to receive the exact same code).

**Comment by jpalardy** [comment]
@pdex 

Right, I think those are valid questions. How often do I need this? Do other people need this?

You can live with it for a while and let me know what you decide. I'll be here 😄
