### ISSUE TITLE
Tabbed support

### ISSUE THREAD

**Issue by huijunchen9260** [jpalardy/vim-slime#235]
Dear @jpalardy:

Recently I fell in love with the suckless tabbed. I am wondering whether it is possible to support tabbed. I will try my best to express my thought on how to implement this, but I don't know vim script, so I don't know how to do it.

My thought is based on the current implementation of `X11 window`. 

Tabbed will spawn an empty window to generate tabbed for any embed children window. Current `X11 window` doesn't work on tabbed. It is because when `xdotool selectwindow` select a tabbed terminal, instead of selecting that terminal, `vim-slime` actually selecting tabbed, not the terminal, so the window id is wrong.

If you run `xwininfo -children -id $(xdotool selectwindow)` on a tabbed terminal, you will get something similar to:

```
xwininfo: Window id: 0x2e00002 (has no name)

  Root window id: 0x182 (the root window) "LG3D"
  Parent window id: 0x182 (the root window) "LG3D"
     3 children:
     0x3e0000a "urxvt": ("urxvt" "URxvt")  1908x1042+0+0  +6+32
     0x3c0000a "urxvt": ("urxvt" "URxvt")  1908x1042+0+0  +6+32
     0x380000a "urxvt": ("urxvt" "URxvt")  1908x1042+0+0  +6+32
```

as you can see, if we can correctly assign windows id on the second children window, `0x3c0000a`, then it works. We can also transform hex number into decimal number use `printf '%d' "0x3c0000a"`. 

After some trial, I found out that replace the 
```
let b:slime_config["window_id"] = trim(system("xdotool selectwindow"))
``` 
with the following command works:

```
let b:slime_config["window_id"] = trim(system("xwininfo -children -id $(xdotool getactivewindow) | grep '     0x' | head -n 2 | tail -n 1 | cut -b 6-14 | xargs printf '%d'"))
```

Hope that you can formalize this and make `vim-slime` support tabbed!

**Comment by jpalardy** [comment]
hi @huijunchen9260,

it's @ynco who worked on that part of the code (support for X11 send).

@ynco is that something you would be interested in?
