### ISSUE TITLE
"--\n" is never sent to ipython

### ISSUE THREAD

**Issue by trallarn** [jpalardy/vim-slime#239]
To finish the ipython %cpaste command "--\n" should be submitted which it is not.

This patch fixes the issue:

```
diff --git a/ftplugin/python/slime.vim b/ftplugin/python/slime.vim
index f52a242..d111fcb 100644
--- a/ftplugin/python/slime.vim
+++ b/ftplugin/python/slime.vim
@@ -5,7 +5,7 @@ end

 function! _EscapeText_python(text)
   if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
-    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
+    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text .. "--\n"]
   else
     let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
     let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
```

Setup:

MacOs
Slime - master branch

.vimrc:
let g:slime_python_ipython = 1

$ ipython --version
7.11.1

**Comment by trallarn** [comment]
Here is a PR:
https://github.com/jpalardy/vim-slime/pull/240

**Comment by jpalardy** [comment]
hi @trallarn,

what's the current behavior you see when you paste?

the ftplugin has been running as-is for a while, I wonder what's different.

**Comment by trallarn** [comment]
Hi Jonathan

The cpaste and code chunk is pasted. Nothing else. Which means the code is
not executed.

I agree that it's strange that no one else has been effected by this. Could
it be my setup - I don't know. The suggested PR fixes it on my machine at
least.

**Comment by jpalardy** [comment]
if you're willing to experiment, the relevant code is [here](https://github.com/jpalardy/vim-slime/blob/master/autoload/slime.vim#L388-L397).

some things to try:
- can use `echom` in for-loop to see if all pieces are sent
- can use integers in the list of pieces to force a sleep between pieces

let me know how that goes 😄

**Comment by trallarn** [comment]
It seems like screen is a bit buggy. 

This is my change set used for demoing:

```
diff --git a/autoload/slime.vim b/autoload/slime.vim
index d60aeb2..38aa1b2 100644
--- a/autoload/slime.vim
+++ b/autoload/slime.vim
@@ -20,6 +20,7 @@ end
 """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 function! s:ScreenSend(config, text)
+  echom 'Sending ' . a:text
   call s:WritePasteFile(a:text)
   call system("screen -S " . shellescape(a:config["sessionname"]) . " -p " . shellescape(a:config["windowname"]) .
         \ " -X eval \"readreg p " . g:slime_paste_file . "\"")
@@ -389,6 +390,7 @@ function! slime#send(text)
   for piece in pieces
     if type(piece) == 0  " a number
       if piece > 0  " sleep accepts only positive count
+        echom 'Pausing for ' .. piece ' m'
         execute 'sleep' piece . 'm'
       endif
     else
diff --git a/ftplugin/python/slime.vim b/ftplugin/python/slime.vim
index d111fcb..e6c7b93 100644
--- a/ftplugin/python/slime.vim
+++ b/ftplugin/python/slime.vim
@@ -5,7 +5,7 @@ end

 function! _EscapeText_python(text)
   if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
-    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text .. "--\n"]
+    return ["%cpaste -q\n", "2\n", "3\n", "4\n", "5\n", "6\n", "--\n"]
   else
     let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
     let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
```

So essentially the numbers 2, 3, 4, 5, 6 with new lines are sent within the cpaste. The text argument is ignored.

Running this a few times yields this in my screen window:
```
In [80]: %cpaste -q
2
4
5
6
--
Out[80]: 6

In [81]: %cpaste -q
2
4
5
6
--
Out[81]: 6

In [82]: %cpaste -q
3
5
6
--
Out[82]: 6

In [83]: %cpaste -q
2
4
5
6
--
Out[83]: 6
```

See how the results differ? "3" is not sent except from one time, and when it is "2" and "4" is not sent...

This is from vim :messages

```
Sending %cpaste -q
Sending 2
Sending 3
Sending 4
Sending 5
Sending 6
Sending --
Sending %cpaste -q
Sending 2
Sending 3
Sending 4
Sending 5
Sending 6
Sending --
Sending %cpaste -q
Sending 2
Sending 3
Sending 4
Sending 5
Sending 6
Sending --
Sending %cpaste -q
Sending 2
Sending 3
Sending 4
Sending 5
Sending 6
Sending --
```

So the plugin seems to send everything always, but somehow it doesn't reach the screen window...

With the original code, "3" is the "--\n" that is never (or seldom) sent to screen which is the background to this issue.

So essentially, very weird :|

**Comment by jpalardy** [comment]
This behavior _screams_ "race condition" to me…

The Gnu Screen plugin writes the "paste file", and calls on `screen` to load-and-paste the same file. If this happens in a loop (as above), there might be a case where the next "send" is written to file before the previous paste was done.

Also, most non-Python plugins don't make a point of breaking a block of text into multiple chunks (causing that for-loop)

more experiments, if you're interested:
- what happens if you introduce sleeps between the chunks? something like `["%cpaste -q\n", 50, "2\n", 50, "3\n", 50, "4\n", 50, "5\n", 50, "6\n", 50, "--\n"]`
- what happens if you try to make "one chunk" with everything?

**Comment by jpalardy** [comment]
Looking back at the ftplugin code:

![sleep-vs-not](https://user-images.githubusercontent.com/18142/79806279-e2771780-831c-11ea-8559-6a8fa425fd01.png)

there would be a missing sleep exactly where you've had problem, no?

**Comment by trallarn** [comment]
Introducing sleeps between the arguments doesn't help. Argument "3" still doesn't make it to the screen window, and occasionally what arguments reach screen differs from time to time.

Concatenating like so resolves this issue
```
return ["%cpaste -q\n", "2\n" . "3\n" . "4\n" . "5\n" . "6\n" . "--\n"]
```

Two arguments works fine with screen, but three, of some reason, does not.

I've tried it in tmux where it works as expected.

**Comment by jpalardy** [comment]
hi @trallarn,

I don't have a good suggestion for this…  (is "use tmux" a good suggestion?)

I don't think there's a "next action" of this thread or the related PR. Maybe watch the repo and see if other people face a similar problem?

You've got a workaround for now, but I'm not sure I can promote it to `master`…

**Comment by trallarn** [comment]
Yeah I agree. It seems to be something related to screen on mac. I'll use my own branch to get around this  👍 

Thanks for the discussion @jpalardy !
