### ISSUE TITLE
<C-c> does not always work in Neovim

### ISSUE THREAD

**Issue by againxx** [jpalardy/vim-slime#242]
Having the same issue as #128.
When I start neovim, and use `<C-c><C-c>` to send paragraph, it works fine. But after a while, when I press `<C-c>`, it immediately shows the message "Type :qa and press \<Enter\> to exit Nvim". Although I can still use `<C-c>` in visual mode.
However, in vim 8.2 `<C-c>` always works fine, and If I bind `<C-q>` instead of `<C-c>` in neovim, everything is ok.
It seems that the key binding of `<C-c>` in neovim is not consistent.
My environment:
Neovim - 0.5.0
Alacritty - 0.4.2
tmux - 3.0a
ubuntu 18.04.1

**Comment by againxx** [comment]
I have tried it for a while. It seems binding `<C-c>` to `<nop>` in normal mode can work around this problem.

**Comment by jpalardy** [comment]
Hi @againxx,

Interesting ^

If your workaround, `<nop>`, keeps working, let me know. We'll put a note in the README.

**Comment by againxx** [comment]
Ok, I will feedback if this is a consistent workaround.

**Comment by againxx** [comment]
After a few days attempts, I think mapping `<C-c>` to `<nop>` works for me.
By the way, the native `<C-c>` may has some usage (in command line window) so I remap it to `<C-c><C-x>` which is also easy to press.
![slime](https://user-images.githubusercontent.com/22728604/81461679-f1484000-91df-11ea-87f9-1d48df0319ee.png)

**Comment by jpalardy** [comment]
Thanks for letting me know ^
