### ISSUE TITLE
Is it necessary to use s:WritePasteFile as a block for Neovim terminal

### ISSUE THREAD

**Issue by a-vrma** [jpalardy/vim-slime#243]
The line I am talking about is https://github.com/jpalardy/vim-slime/blob/a81139239d6447b1c021e4873e6a14b47f32b65a/autoload/slime.vim#L104
Coudn't we use something like `:sleep` instead? It will have less side effects.

**Comment by jpalardy** [comment]
Hi @a-vrma,

There isn't much code and you're probably in a better position to tell _me_. That workaround is kind of gross 😐 

Something "new" that might help: [SlimeOverrideSend](https://github.com/jpalardy/vim-slime#how-to-override-send-to-target) as part of the other [overrides](https://github.com/jpalardy/vim-slime#advanced-configuration-overrides).

If not, you can play with sleeps and let me know what you find.

**Comment by a-vrma** [comment]
> Something "new" that might help: SlimeOverrideSend as part of the other overrides.

Ah so we could define SlimeOverrideSend in the IPython ftplugin file? I'll see what I can do with that.

**Comment by a-vrma** [comment]
wait bot
