### ISSUE TITLE
Unicode characters don't get sent.

### ISSUE THREAD

**Issue by usmcamp0811** [jpalardy/vim-slime#244]
It seems as if unicode characters aren't getting sent as expected. 

*NeoVim*
```julia
s1 = "Julia concatenates strings a little ";
🐍 = "different than Python";
string(s1,🐍)
s1 * 🐍
```

doesn't end up in my REPL correctly. 

*Julia REPL*
```julia
julia> s1 = "Julia concatenates strings a little ";

julia>  = "different than Python";
ERROR: syntax: unexpected "="
Stacktrace:
 [1] top-level scope at REPL[45]:0

julia> string(s1,)
"Julia concatenates strings a little "

julia> s1 *
```

My vim version and info.. 
```bash
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by jpalardy** [comment]
hi @usmcamp0811,

here's a screenshot from my side:

![Screen Shot 2020-05-21 at 21 12 34](https://user-images.githubusercontent.com/18142/82630574-eb6f3900-9ba7-11ea-966b-ba7bcb495f54.png)

mix:
- macOS
- vim 8.2
- tmux 3.1b
- julia 1.4

can you try different combinations and let me know what works and doesn't work?

**Comment by usmcamp0811** [comment]
I just tried with `tmux` and it worked.. Before I was using `x11`. My terminal is `Alacritty`. I also just tried `kitty` and couldn't get anything to work.. but that could just be user error as I installed it really just to test this out.. 

any logs or anything I could check or get info from to help? 

in the end its not that big of a deal.. just thought I'd let ya know about it.

**Comment by Remiol** [comment]
I'm trying this, but how do I execute the code? Vim-slime copies the code to the ipython terminal but doesn't execute it.

**Comment by jpalardy** [comment]
Hmmm… I checked the x11 code, and it inserts them (escaped) onto a subshell:

```vim
call system("xdotool type --delay 0 --window " . b:slime_config["window_id"] . " -- " . shellescape(a:text))
```

does that work if you try to invoke it manually?

**Comment by usmcamp0811** [comment]
I pasted the command directly in `nvim` and get the following error. Looks like I don't have the function `shellescape`. Unless I needed to modify the command in some way. I tried some mods but all were unsuccessful. 

```vim

E121: Undefined variable: a:text
E116: Invalid arguments for function shellescape
E116: Invalid arguments for function system
Press ENTER or type command to continue
```

**Comment by jpalardy** [comment]
ah, sorry I wasn't clear… I meant directly in your terminal:

```
xdotool type --delay 0 --window $window_id  -- '🐍 = "different than Python";'
```
(with an appropriate value for `$window_id`)

This chain would remove nvim from the loop, but keep the other parts. It would allow us to see if it's one of {shell, terminal, xdotool}

**Comment by usmcamp0811** [comment]
Got it.. yea just tried it in the terminal and it got rid of the unicode character. But I did some playing around with several terminals and got some odd results... 

**Alacritty**
Unicode characters don't come across with the command.. but if I run the command in the same terminal as its target the characters work, and then I can run the command again from another terminal and and it works all day for that character. 

**Termite**
Nothing gets piped to it

**Kitty**
Regular characters get piped to it but with one minor oddity, uppercase letters are made lowercase. If I try the run the command in the same window trick, the unicode characters don't show up, but the case is preserved.

**Comment by jpalardy** [comment]
whoah… 😭
