### ISSUE TITLE
How to people send scripts to bash or other shell?

### ISSUE THREAD

**Issue by ScrumpyJack** [jpalardy/vim-slime#246]
Just wondering how people who use vim-slime send shell scripts to bash or a similar shell, so that it executes the script in a subshell and outputs the result in the target shell?

Maybe it's possible to execute .slime_paste in the target pane/window somehow when the "REPL" is a shell prompt?

**Comment by jpalardy** [comment]
Hi @ScrumpyJack,

Yes, you can run anything in your target window, bash isn't special.

Is that what you meant?

**Comment by ScrumpyJack** [comment]
Here I sent all the lines to the bash target window. Each line is echoed to the shell, then the shell executes them one by one, echoing each line again.

Would be cool to be able to only get the output of the script in the target pain, as if you were executing a shell script with the contents of .slime_paste, like this

<img width="1430" alt="Screenshot 2020-06-02 at 19 09 58" src="https://user-images.githubusercontent.com/3187469/83554464-b5fe1000-a504-11ea-8d32-5767df4c9027.png">

**Comment by ScrumpyJack** [comment]
Sorry, I closed this by mistake, re-opening

**Comment by jpalardy** [comment]
Yeah… I don't have a good solution for this. It's a bit target-specific and outside the scope of vim-slime itself.

I know sequences can cause the terminal to stop echoing (similar to password prompts). There are also sequences to indicate "paste mode".

If you find a solution, I would be interested to know.

**Comment by ScrumpyJack** [comment]
How about something like this for tmux for example:

An new variable so the user can set their preferred interpretive shell

let g:slime_interpretive_shell = "bash"

and some new mappings that do the following

SlimeRegionSendToShell
SlimeParagraphSendToShell

which would send the the string

$slime_interpretive_shell $slime_paste_file 

to the target pane, so that you'd end up with, say,

bash ~/.slime_paste 

being sent to the target pane, with ~/slime_paste containing the Region or Paragraph which would get executed.

**Comment by jpalardy** [comment]
I see where you're going with this.

I don't think this is core vim-slime and I wouldn't want to bake those features in.

Fortunately, with [overrides](https://github.com/jpalardy/vim-slime#advanced-configuration-overrides), you could do exactly what you mentioned. I would you write an external script to perform all the logic, and then forward to tmux.
