### ISSUE TITLE
vim-slime not recognizing terminals opened by user?

### ISSUE THREAD

**Issue by marcelosena** [jpalardy/vim-slime#249]
I was playing around with some configurations on vim-slime, but now I seem to have permanently messed it up somehow. First I had only the option to use vimterminal

`let g:slime_target = "vimterminal"`

Then I added options to run some command on startup and open vertically:

```
let g:slime_target = "vimterminal"
let g:slime_vimterminal_config = { "term_finish": "close", 
    \ "vertical": 1, 
    \ "term_cols": &columns * 1/3,}
```

Then I decided to go back to the plain vanilla mode, where I would manually open a terminal and then tell slime to choose that one, as for example suggested here: https://github.com/jpalardy/vim-slime/issues/168

However, when I try to do this, it never gives me the option to choose the terminal I opened, always opening a new one. I open my terminal through the following sequence of keys in case its relevant (I change directory and open the terminal):

```
nnoremap <silent> <F2> :lchdir %:p:h<CR>:pwd<CR>
nnoremap <silent> <F1> :botright vertical terminal<ENTER>
```

Also, on vim startup I open some other auxiliary tabs, but I believe those to be irrelevant. I have tried already removing and reinstalling vim-slime without any success. Why isnt vim-slime recognizing the terminal I open?

Thanks for the package!

**Comment by jpalardy** [comment]
Hi @marcelosena,

That question is more setup-specific than vim-slime -specific.

I would recommend starting from nothing and adding config back gradually (until things work, or stop working, as the case might be)

If you make can't make progress, come back for another round.
