### ISSUE TITLE
Question: How to mapping send and jump to the next paragraph

### ISSUE THREAD

**Issue by kguidonimartins** [jpalardy/vim-slime#250]
Hi there, thanks for this amazing plugin. I just switched from IDEs because of this plugin!

I'm new to vim (I'm using neovim) and I'm struggling to map vim-slime commands with motions. I browsed through the issues looking for similar questions but didn't find them.

Could you tell me how to map these commands? 
1. `SlimeRegionSend` and `}j`
2. `SlimeParagraphSend` and `}j`

My current configs are the following:

```
let g:slime_target = "tmux"
let g:slime_no_mappings = 1
let g:slime_python_ipython = 1

xmap <leader>ss <Plug>SlimeRegionSend
nmap <leader>ss <Plug>SlimeParagraphSend
nmap <c-c>v   <Plug>SlimeConfig
```

**Comment by jpalardy** [comment]
hi @kguidonimartins,

I'm happy that you're enjoying vim-slime!

I did a quick test on my side:

```vim
nmap <c-c>} <c-c><c-c>}j
```

map <kbd>ctrl-c</kbd><kbd>}</kbd> to:
- <kbd>ctrl-c</kbd><kbd>ctrl-c</kbd>     -- call SlimeParagraphSend
- <kbd>}</kbd>   -- move paragraph down
- <kbd>j</kbd>   -- move line down

I think that will give you a head start on your own mapping. Let me know how that goes.

**Comment by kguidonimartins** [comment]
Many thanks, @jpalardy!

I found it quite elegant to be able to combine the mappings in this way. I remapped it, as you suggested, with a slight difference. It has worked perfectly.

```vim
xmap <c-c><c-c> <Plug>SlimeRegionSend
nmap <c-c><c-c> <Plug>SlimeParagraphSend

nmap <leader><leader> <c-c><c-c>}j
```

But I need to start the slime with <kbd>ctrl-c</kbd><kbd>ctrl-c</kbd> before and only after that `<leader><leader>` (<kbd>,</kbd><kbd>,</kbd> in my case) works as expected.

This is a small detail, and I'm really happy with this improvement. The ergonomics improved a lot! 

Thanks for your time. I'm closing this issue.

**Comment by jpalardy** [comment]
Excellent 👍
