### ISSUE TITLE
Support for Scala Ammonite REPL?

### ISSUE THREAD

**Issue by LeoKavanagh** [jpalardy/vim-slime#252]
Hi,

I'm using Vim-Slime (normal Vim, with tmux) with Scala's [Ammonite REPL](http://ammonite.io/), an IPython-style improved Scala REPL.

The base Scala REPL you get from `scala` or `sbt console` treats a `^D` that follows `:paste` as "exit paste mode", but Ammonite only ever treats it as "exit the REPL entirely". (As a side note, Ammonite doesn't have a `:paste` command (see [this issue](https://github.com/lihaoyi/Ammonite/issues/81)), but rather wraps multi-line expressions in curly braces.)

The [Slime function for Scala](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/scala/slime.vim) is set up to work with the base console, and therefore doesn't work well with Ammonite.

I was wondering if an IPython-style flag and would be welcome here too. That is, get the user to add the following line to their `.vimrc`:

```
let g:slime_scala_ammonite = 1
```

and also add an if-statement to the `_EscapeText_scala` function to check for it. Something like:
```
function! _EscapeText_scala(text)
   if exists('g:slime_scala_ammonite')
     return ["{\n", a:text, "}\n"]
   else
     return [":paste\n", a:text, "^D"]
   end
endfunction   
```

I've been using this version of the function personally for the past few days, and it seems to be working fine. Unfortunately I don't know enough VimScript to offer anything like a passing unit test.

Curious to get your thoughts on this. I'm happy to submit a PR if you think it would be a useful addition.

**Comment by jpalardy** [comment]
Hi @LeoKavanagh,

If it works, and you're willing to help out with (potential) incoming issues, then I would be willing to merge that in 😀 

This would probably need a documentation patch … at least to document the new flag.

**Comment by LeoKavanagh** [comment]
Sounds good! I'll get to work on a PR.

**Comment by vando026** [comment]
Hi both, I followed this thread with interests, I have one issue and a suggestion. 

Suggestion: after checking its existence, shouldn't the _EscapeText function also include an `if g:slime_scala_ammonite==1` condition, as in 

```
function! _EscapeText_scala(text)
  if exists('g:slime_scala_ammonite')
    if g:slime_scala_ammonite==1
      return ["{\n", a:text, "}\n"]
    end
  end
  return [":paste\n", a:text, "C-d"]
endfunction

```
which does the first return statement if the variable exists and is equal to 1. 

Issue: More importantly, for the _EscapeText_scala function, my Ubuntu 20.04 install, neovim 0.4.3, and tmux, interprets the "^D" as a possible unknown character. Screenshot attached. 

![EscapeTest](https://user-images.githubusercontent.com/36604253/109165687-211b0100-777c-11eb-8ebc-549ff3fc3160.png)

I replaced it with "^D" and even tried "C-d", but it doesn't work and scala remains in paste mode when I call vim-slime. 

![shot2](https://user-images.githubusercontent.com/36604253/109167035-a0f59b00-777d-11eb-9407-8ea6ee5e1813.png)

However, when I dont call vim-slime, and scala is still in paste mode,  I can exit using 

exec '!tmux send-keys -t right C-d'

(or whatever -t is selected). So something is not working with the "^D" part in the second return statement. Do you have any suggestions on how to fix this?

**Comment by vando026** [comment]
Hi both, I also have one suggestion: after checking its existence, shouldn't the _EscapeText function also include an `if g:slime_scala_ammonite==1` condition, as in 

```
function! _EscapeText_scala(text)
  if exists('g:slime_scala_ammonite')
    if g:slime_scala_ammonite==1
      return ["{\n", a:text, "}\n"]
    end
  end
  return [":paste\n", a:text, "C-d"]
endfunction

```
which does the first return statement if the variable exists and is equal to 1.

**Comment by jpalardy** [comment]
Hi @vando026 

This is a bit fast-and-loose … checking for the existence (only) and not the value …

someone _could_ set `g:slime_scala_ammonite=0` and have unexpected behavior. In practice, (I checked) most vars in vim-slime assume this doesn't-exists vs exists (whatever value)

I don't think this is a major problem.
