### ISSUE TITLE
<Plug>SlimeSendCell breaks if g:slime_cell_delimeter is defined using an autocommand

### ISSUE THREAD

**Issue by mroavi** [jpalardy/vim-slime#256]
The `<Plug>SlimeSendCell` mapping added in 6755b54b66f565dcf6bb5c600af04aeb345af531 doesn't seem to be working at the moment. The other mappings like `<Plug>SlimeRegionSend` and `<Plug>SlimeLineSend` do work fine.

Version: NVIM v0.5.0-577-g48ac77a14
vim-slime sha: f7442cdb1fb37778ddff93649e172b0ad752c237
OS: Ubuntu 18.04.4 LTS
Target: tmux 2.6

**Comment by jpalardy** [comment]
Hi @mroavi,

In my [config file](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L30), I've been using this:

```vim
let g:slime_cell_delimiter = "#--"
nmap <c-c>d <Plug>SlimeSendCell
```

and it works.

What's your config? And what behavior do you see?

**Comment by mroavi** [comment]
This is my config:
```vim
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{right-of}"}
let g:slime_dont_ask_default = 1
let g:slime_no_mappings = 1
let g:slime_cell_delimiter = "%%"
nmap <Leader>cc <Plug>SlimeSendCell
nmap <Leader>ls <Plug>SlimeLineSend
```
I tested with a different delimeter but it still dosen't work. I'm testing this on matlab/octave files.

The behavior I see is that after I press the `<Leader>cc` nothing occurs, i.e. no text is sent to tmux. On the other hand, if I type `<Leader>ls` then the current line is sent. I replaced `<Plug>SlimeSendCell` with `:echo "Test"<CR>` to make sure the key binding is working properly.

**Comment by mroavi** [comment]
I found the problem: I had the `let g:slime_cell_delimiter` definitions inside several *filetype plugin* files (e.g. *ftplugin/octave.vim*). Apparently these files are sourced after the *plugin/slime.vim* file is sourced. This meant that the content of the following `if` block was not being executed:
```vim
if exists("g:slime_cell_delimiter")
  noremap <unique> <script> <silent> <Plug>SlimeSendCell :<c-u>call slime#send_cell(g:slime_cell_delimiter)<cr>
endif
``` 
My solution is to define a general (useless) `g:slime_cell_delimeter` in my *init.vim* and specialize it on the filetype plugin files. I think that the software design could be improved here since having custom cell delimeters depending on the filetype is such a common scenario. Or at least having a warning in the README configuration section noting that the definition of `g:slime_cell_delimeter` has to be in the *init.vim* or *.vimrc* would be very helpful.

**Comment by jpalardy** [comment]
(this code was a contribution, I had to re-read for more context)

I'm trying to think of a "general solution" for this. I agree with you that `slime_cell_delimiter` will usually require a ftplugin override.

thoughts:
- does vim-slime need a concept of `b:slime_cell_delimiter`?
- does the map need to exist and trigger a configuration prompt (if delimiter isn't set)?

**Comment by mroavi** [comment]
> does vim-slime need a concept of b:slime_cell_delimiter?
> does the map need to exist and trigger a configuration prompt (if delimiter isn't set)?

Personally, I think that the `b:slime_cell_delimeter` is a great feature added to vim-slim. Initially, I had no real plans on using it, then I gave it a shot, and now I use it almost exclusively.

The `if exists("g:slime_cell_delimiter")` is there is to avoid undefined behavior in case `g:slime_cell_delimiter` is not defined. One option is to move this check inside `slime#send_cell(cell_delimiter)` so that `<Plug>SlimeSend> gets always defined.

**Comment by jpalardy** [comment]
hi @mroavi,

Is this a change to vim-slime you would be interested in pursuing?

**Comment by mroavi** [comment]
Sure. Opened a PR: https://github.com/jpalardy/vim-slime/pull/257
