### ISSUE TITLE
Fails to Send Text to X11Target on Neovim

### ISSUE THREAD

**Issue by Neightro** [jpalardy/vim-slime#259]
Platform: Manjaro Linux
`xorg-server` version: 1.20.8-4 (current package version on Manjaro, from group `xorg`)*
Neovim 0.4.3

When hovering over a paragraph and pressing <C-c><C-c>, the cursor switches to the selector icon as expected. Upon clicking on a window, however, nothing happens. The selector cursor does not appear again on subsequent presses of <C-c><C-c>, implying that vim-slime successfully chooses a target, though it still fails to send text to the window.

Occurs on the latest commit of branch master; I just freshly reinstalled the plugin. It works as intended on Vim 8.2 with the same local repo.

*I'm not all that familiar with the workings of X11; this was the most relevant version number I could find. Please let me know if it isn't relevant; I will happily amend this post if so.

**Comment by jpalardy** [comment]
Hi @Neightro,

Thanks for reporting this ^

just to confirm: this used to work but doesn't on the latest version of vim-slime? (when nothing else changed)

**Comment by Neightro** [comment]
@jpalardy The best I can summarize the bug is that this had been working on classic Vim but not on Neovim, though it seems to now be working correctly on both versions of Vim.

I'm not sure what was responsible for this change. I can only conclude that it was due to some update that took place; I can see that Manjaro had at least one update to `xorg-server` since I reported the issue.

Whatever the case may be, I suppose it's best that I close this issue for now. Thank you anyways for your support!

**Comment by Neightro** [comment]
By the way, I was just digging through my config a little bit more and noticed an old comment. It seems that ctrl-c might behave inconsistently on Neovim. I still can't reproduce the issue I was having, even after removing my attempt at fixing the behavior.

On a similar note, it seems that on  both versions of Vim using ctrl-c to exit insert mode will break Slime's mapping; you start seeing the "Type :qa" message instead. It's uncommon that anyone should use ctrl-c to exit insert mode, though I think it's worth taking into account, provided that this behavior isn't specific to my setup.
