### ISSUE TITLE
Using vim-slime

### ISSUE THREAD

**Issue by LucasPa** [jpalardy/vim-slime#260]
Hi,

First of all thanks for this nice plugin!

Unfortunately  I am experiencing some trouble to make it run. I installed it with vim-plug and the installation seemed fine.

Then I tried to use from Gvim. As I understand, I just need to go on some text and hold Ctrl while pressing twice c. I am then asked to give the "screen session name" and the "screen window name". But once I enter both of them, nothing happen. 

Did I miss something  ?

Best,

Lucas

**Comment by jpalardy** [comment]
Hi @LucasPa,

vim-slime "trusts" that the commands it executes reach their destination (and has not obvious way to determine that they haven't 😢 )…

In practice, it's easier to debug this outside of vim: what does `screen -ls` say?

then, try:

```
screen -S $SESSION_NAME -p $WINDOW_NUM -X eval "readreg p $HOME/.slime_paste"
screen -S $SESSION_NAME -p $WINDOW_NUM -X paste p
```

(replacing $SESSION_NAME and $WINDOW_NUM with appropriate values)

If doing it manually doesn't work — vim-slime won't work either. (you can check the code, it's not too scary)

Let me know how that goes.

**Comment by LucasPa** [comment]
Thank you @jpalardy  for your answer.

Actually I am a total beginner to screen so I just missed how important is the session name.

Thanks to your help I understand that the session name should the value returned by `screen -ls`. I simply then assign the window number to 0 and it works fine.

Thanks again for the help,

Lucas

**Comment by jpalardy** [comment]
Hi @LucasPa,

Glad you could get it working 👍 

Enjoy vim-slime and I'll be here if you need anything else.

**Comment by SebastianBehrens** [comment]
Hey @jpalardy ,
what do I do when `screen ls` returns `No Sockets found in /var/folders/1f/c30n_2q14556_p9sxtzwyx7h0000gn/T/.screen.`?
