### ISSUE TITLE
vim-slime seems to append a "]" character to julia list comprehension lines

### ISSUE THREAD

**Issue by timrandg** [jpalardy/vim-slime#262]
I just started using your useful plugin. Thank you for your nice work. 

I am using vim-slime to send julia code form nvim to julia REPL in tmux. 

in my .vimrc I have the following vim-slime config:

let g:slime_target = "tmux"                                                                            
let g:slime_default_config = {"socket_name": "default", "target_pane": "0.1"}

in nvim:
a = [ x for x in (1:1:10) ]  <C-c C-c> 

julia window:
julia> a = [ x for x in (1:1:10) ]]
ERROR: syntax: extra token "]" after end of expression  

note the extra square bracket added to the line as it was passed by vim-slime.

Similarly, if an array is declared, an extra "]" gets appended. 
in nvim:
ar = [1,2,3] <C-c C-c>

julia window:
julia> ar = [1,2,3]]
ERROR: syntax: extra token "]" after end of expression

However, the ipython REPL works exactly as expected. No extra brackets are added on.

VERSIONS:
julia version 1.5.2

NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5

tmux 3.1b

no version is provided in vim-slime (but installed from github on ~Sept 30, 2020)

**Comment by timrandg** [comment]
Actually, it is a problem with the julia REPL plugin called "OhMyREPL". Which bracket matches as one types. Turning off that plugin fixed the problem. False bug report...sorry. Back to more important things.

**Comment by jpalardy** [comment]
hi @timrandg,

Happy to hear it's working after all 😃 

I'll be here if you need anything.
