### ISSUE TITLE
Code not executed within a tmux session using ipython.

### ISSUE THREAD

**Issue by kguidonimartins** [jpalardy/vim-slime#267]
Hello @jpalardy, thanks again for the great plugin you created. I have used it a lot for different languages. 

I recently realized that the integration with ipython stopped working as it should in tmux. When sending the code to the ipython terminal, the code is not executed. It looks like an Enter (<CR>) is missing. In order for the code to run, I need to move the cursor to the ipython terminal, delete the last pasted line and press Enter.

![out](https://user-images.githubusercontent.com/8163542/97084631-c6677200-15ee-11eb-8439-c1c4c4db7599.gif)

My settings:

```vim
let g:slime_paste_file = "/tmp/slime_paste"
let g:slime_no_mappings = 1
let g:slime_python_ipython = 1

xmap <c-c><c-c> <Plug>SlimeRegionSend
nmap <c-c><c-c> <Plug>SlimeParagraphSend
nmap <c-c>v   <Plug>SlimeConfig
nmap <leader><leader> <c-c><c-c>}jzz
nmap <leader><Space> <c-c><c-c>

function SlimeX11()
  let g:slime_target = "X11"
endfunction

function SlimeTmux()
  let g:slime_target = "tmux"
endfunction

let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{right-of}"}

function! _EscapeText_r(text)
  call system("cat > " . "/tmp/slime_r", a:text)
 return ["source('/tmp/slime_r', echo = TRUE, max.deparse.length = 4095)\r"]
endfunction

function! _EscapeText_rmd(text)
  call system("cat > " . "/tmp/slime_r", a:text)
 return ["source('/tmp/slime_r', echo = TRUE, max.deparse.length = 4095)\r"]
endfunction
```

Could you help me understand what is going on?

**Comment by jpalardy** [comment]
Hi @kguidonimartins 

is this a _recent_ problem? (did you update since yesterday?)

It looks like #265, could you confirm? (we might need to roll this back)

**Comment by carlocab** [comment]
@jpalardy I believe it's the same problem. It's probably a good idea to roll it back and I'll try to think of a better way to get bracketed-paste working where it's useful.

**Comment by jpalardy** [comment]
reverted 10e8c2b3bd19e99c4889e4135a34eaf5aa0b37c3

**Comment by kguidonimartins** [comment]
> is this a _recent_ problem? (did you update since yesterday?)

Yes, this is recent. But, you have reversed, and everything is working normally now. Many thanks!

**Comment by jpalardy** [comment]
Good good, sorry for the inconvenience 😅
