### ISSUE TITLE
Have to reconfigure target Tmux pane for each vim buffer?

### ISSUE THREAD

**Issue by zaid-g** [jpalardy/vim-slime#268]
I'm working with two Tmux panes, one of which has a Vim session with multiple buffers loaded. The problem is that vim-slime asks me to re-configure and re-specify the tmux socket name or absolute path and the target tmux pane for each buffer I load in my vim session. Is this normal behavior?

For example, I hit C-c C-c the first time, it asks me to set the socket name + target pane (expected behavior), I then load another buffer in the same vim session, but hitting C-c C-c on code in this buffer prompts me again to configure those same settings (unexpected behavior).

**Comment by jpalardy** [comment]
Hi @zaid-g 

This is a "feature". There are cases were you could decide to have different buffers target different tmux panes.

Here's what I use for [my config](https://github.com/jpalardy/dotfiles/blob/master/vim/plugins.vim#L20-L22):

```vim
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
let g:slime_dont_ask_default = 1
```

- target_pane at `{last}` is usually what I want (to other pane, the non-vim pane)
- `slime_dont_ask_default` won't query for the config and fall back to `slime_default_config`

give that a try and let me know if that's better

**Comment by zaid-g** [comment]
This works for me! Although ideally I would like it to ask me just the first time I open vim, and not anymore when switching buffers after that. But that can be just my opinion. And with this I can just remember to configure the default pane when I first open vim and get the same effect.

Thanks for your response and thanks a lot for writing this awesome plugin.

**Comment by jpalardy** [comment]
@nyngwang 

you want to be prompted every time you press ctrl-c, ctrl-c?

**Comment by jpalardy** [comment]
Hi @nyngwang 

let's open another issue for ☝️ — I have a few ideas
