### ISSUE TITLE
Feature Request: Ability to customize SlimeSend with preprocessing function 

### ISSUE THREAD

**Issue by dgkf** [jpalardy/vim-slime#269]
I've tried digging around in the source to see if there's a way to intercept and preprocess the text to be sent to the target terminal, but wasn't able to find anything - apologies if I missed this in the docs.

The motivating examples is to be able to execute function examples, often documented as doxygen-style function headers. Take the following code for example (including line numbers for illustration):

```r
 1 #' This is my simple addition function
 2 #' 
 3 #' @param a A numeric value
 4 #' @param b A numeric value
 5 #'
 6 #' @examples
 7 #' add(1, 2)
 8 #'
 9 add <- function(a, b) {
10   return(a + b)
11 }
```

I'd like to be able to select line 7 and send it to terminal, but preprocess the text by remove the leading `#' ` from each line, uncommenting it before sending it to the terminal. Would it be possible to add some sort of user-configurable option that would allow a user to write a function that preprocesses lines before they get sent to `slime#send`?

**Comment by jpalardy** [comment]
hi @dgkf 

how about this [override](https://github.com/jpalardy/vim-slime#how-to-override-language-transformations)? then you have 2 options:
- write the text transformation in vimscript
- write an executable script and filter your text through it

is this what you had in mind?

**Comment by dgkf** [comment]
Thanks for the speedy reply! Yes - that will work just fine. I had seen that, but initially thought it was intended for passing to an external script - in retrospect I should have realized I could just as easily process the text within vimscript. 

Thanks for the pointer! I'm going to close since this definitely is sufficient for what I need to do after a quick test.

**Comment by jpalardy** [comment]
let me know how that goes 👍

**Comment by dgkf** [comment]
Thanks for the direction - I settled on the function below. 

```vim
function SlimeOverride_EscapeText_r(text)
    let lines = split(a:text, '\n')
    let linesi = range(0, len(lines) - 1)

    " strip roxygen comment characters if all lines start with #' and no
    " lines continue by starting with a roxygen @tag
    let rox_re = '^\s*#\'''
    let is_rox = repeat([0], len(lines))
    for i in linesi | let is_rox[i] = lines[i] =~ rox_re | endfor
    let is_roxtag = repeat([0], len(lines))
    for i in linesi | let is_roxtag[i] = lines[i] =~ rox_re . '\s*@' | endfor
    if min(is_rox) && !max(is_roxtag)
        let rox_lines = map(deepcopy(lines), {_, x -> substitute(x, rox_re, '', "g")})
        let n_lead_ws = len(a:text)
        for i in linesi
            let n_lead_ws = min([
            \    n_lead_ws, 
            \    len(substitute(rox_lines[i], '^\(\s*\).*', '\1', "g"))
            \ ])
        endfor
        return(join(map(rox_lines, {_, x -> x[n_lead_ws:] . "\r"}), ""))
    endif

    return a:text
endfunction
```

#### Executes code when the snippet sent to the terminal always begins with `#' `

```r
#' x <- function(a, b) {
#'   a + b
#' }
```
will execute

```r
> x <- function(x, b) {
+   a + b
+ }
```

#### Keeps comments when the snippet contains a documentation tag `#' @...`

```r
#' @param a A number
#' @examples
#' x <- function(a, b) {
#'   a + b
#' }
```
will execute the following, printing comments instead of otherwise breaking code

```r
> #' param a A number
+ #' @examples
+ #' x <- function(x, b) {
+ #'   a + b
+ #' }
```

**Comment by jpalardy** [comment]
whoah… nice 😃
