### ISSUE TITLE
Concealing input when using vim-slime

### ISSUE THREAD

**Issue by paniash** [jpalardy/vim-slime#270]
Hi!

I'm pretty new to the idea of vim-slime, hence pardon me if I'm asking a novice question. When using vim-slime, it uses `%cpaste -q` to paste commands from vim to ipython, which executes the code block to get the result.

Is there a way to conceal this input and just let ipython spit the output? I'm sure [vim-ipython-cell](https://github.com/hanschen/vim-ipython-cell) has this feature but I was wondering if vim-slime has an option to enable this as well.

Thanks!

**Comment by jpalardy** [comment]
Hi @paniash 

I'm not a ipython user myself, so I'm not sure what's possible or not.

Presumably, if the terminal turned off echo mode (similar to password input), you could get an effect similar to what you want. It has to work for what you type in that terminal also (vim-slime) just "does the typing" for you.

I'll let you investigate. Let me know if you find a solution.

**Comment by paniash** [comment]
@jpalardy Hi! 

> I'll let you investigate. Let me know if you find a solution.

Yeah, I let you know if I find something. :)

**Comment by paniash** [comment]
@jpalardy I'm not sure what `%cpaste -q` does exactly but the concealed input functionality is resolved if `vim-slime` uses `%paste -q` instead of `%cpaste`.

Maybe an configuration option could be added?

**Comment by jpalardy** [comment]
hi @paniash 

Interesting ^

If you only want to fix this for yourself: [override](https://github.com/jpalardy/vim-slime#how-to-override-language-transformations)

If you're interested in making a PR:
- this might be better as a config like: `g:slime_python_ipython_paste` (defaults to `%cpaste -q`, can be set to `%paste -q`) — I'm open to a better config name too 😅 
- a blurb in the [python README](https://github.com/jpalardy/vim-slime/tree/main/ftplugin/python)

What do you think?

**Comment by paniash** [comment]
@jpalardy I'd suggest a config like: `g:slime_ipython_paste_magic` What do you think?

I'm interested in making the PR! Not sure where to start exactly but would love some pointers. Thanks :)

**Comment by jpalardy** [comment]
config: sounds good ^

as for the PR, make the changes and send the PR: we can either iterate on it, and I can put some finishing touches if that's less trouble

(you would have to do something similar to [this](https://github.com/jpalardy/vim-slime/blob/main/ftplugin/python/slime.vim#L2-L4))

**Comment by paniash** [comment]
Alright! I'll take a look and open a PR. Thanks!

**Comment by paniash** [comment]
Sorry, I haven't been able to find time for this. Commenting for removing stale status. 

Hopefully, I'll be able to make a PR soon. :-)
