### ISSUE TITLE
Modify `job-id` in neovim `:terminal`

### ISSUE THREAD

**Issue by iambrj** [jpalardy/vim-slime#271]
Hi, first of all thank you for making such an awesome and useful plugin!

Now my question - is it possible to modify `job-id` when using vim-slime with neovim's `:terminal`. I have two `:terminal`'s open and would like to switch between where the text is sent. I went through the readme, but couldn't find anything :(

Thanks!

**Comment by jpalardy** [comment]
hi @iambrj,

try: <kbd>ctrl-c</kbd><kbd>v</kbd>    (mnemonic: "variables") which will prompt you for config again.

Is that what you meant?

**Comment by iambrj** [comment]
@jpalardy yes, that did the trick! Thanks for the quick response :)

**Comment by iambrj** [comment]
@jpalardy wouldn't it be useful to add this to the readme? I wouldn't mind doing it, what do you think?

**Comment by jpalardy** [comment]
@iambrj 

it's already in the README 😛 

![re-config](https://user-images.githubusercontent.com/18142/101132434-deea8500-35bb-11eb-90e1-69c42a3513e4.png)

but I'd be interested in suggestions on how to make this clearer ^

**Comment by iambrj** [comment]
ah my bad, looks like I skimmed through it a little to fast :sweat_smile:

**Comment by jpalardy** [comment]
no, no, I was serious…

I have my own README-blindness, so I'm sure this could be improved 😄

**Comment by iambrj** [comment]
hmm perhaps putting it under its own `h3` would help? as in

```
Usage
-------------

### Sending text

Put your cursor over the text you want to send and type:

    C-c, C-c       --- the same as slime

_You can just hold `Ctrl` and double-tap `c`._

The current paragraph, what would be selected if you typed `vip`, is automatically
selected. To control exactly what is sent, you can manually select text before calling vim-slime.

### Modifying target

Vim-slime needs to know where to send your text, it will prompt you. Vim-slime
will remember your answers and won't prompt you again. But if you need to
reconfigure, type:

    C-c, v         --- mnemonic: "variables"

or call:

    :SlimeConfig
```

**Comment by jpalardy** [comment]
I'll do pass and wrap the keyboard shortcuts in &lt;kbd&gt; tags.
