### ISSUE TITLE
Windows+Neovim doesn't send the line break correctly

### ISSUE THREAD

**Issue by you-n-g** [jpalardy/vim-slime#273]
Hi,

vim-slime is really a great plugin that saves me a lot of time.
It works as what I expected most of the time.

But it fails to work under windows+neovim. 
Below is an example. The linebreaks can't be recognized by python interpreter in windows. 
![image](https://user-images.githubusercontent.com/465606/101273625-382c0180-37d2-11eb-97b3-faa780901140.png)

After some trials, I found that only  line breaks like '\M' can be recognized. 

Thanks

**Comment by jpalardy** [comment]
Hi @you-n-g 

Interesting that this never came up before 🤔 

For your own setup, you could fix the line endings with [overrides](https://github.com/jpalardy/vim-slime#how-to-override-language-transformations).

Let me know how that goes

(also, I don't know if different python shell would all behave like this)

**Comment by you-n-g** [comment]
@jpalardy 
Thanks your advices
I've tried the following code. But it seems doesn't work

```vimscript
function SlimeOverrideSend(config, text)
  " Neovim jobsend is fully asynchronous, it causes some problems with
  " iPython %cpaste (input buffering: not all lines sent over)
  " So this s:WritePasteFile can help as a small lock & delay
  " call s:WritePasteFile(a:text)

  let l:new_lines = []
  for l:li in split(a:text, "\n", 1)
      let new_lines += [li."\r\n"]
  endfor
  call chansend(str2nr(a:config["jobid"]), new_lines)
endfunction
```
 

![image](https://user-images.githubusercontent.com/465606/101508758-0920b600-39b3-11eb-9cbf-4f9951ad70ef.png)

**Comment by jpalardy** [comment]
try this:

```vim
let l:new_text = substitute(a:text, '\n', '\r\n', '')
```

though that doesn't seem to be the real problem… (at this point, I would try different combinations: maybe just `\r`?)

**Comment by you-n-g** [comment]
@jpalardy  
Thanks for your advice.
I made some modifications and It looks more reasonable ("^[" disappears now)

But I still have to press "Enter" to get the result in python.
The result is very strange
![image](https://user-images.githubusercontent.com/465606/102574558-0305a480-412c-11eb-9e49-902766c881bd.png)


Here is my latest configuration
```vimscript
function SlimeOverrideSend(config, text)
  " Neovim jobsend is fully asynchronous, it causes some problems with
  " iPython %cpaste (input buffering: not all lines sent over)
  " So this s:WritePasteFile can help as a small lock & delay
  " call s:WritePasteFile(a:text)

  " let l:new_lines = []
  " for l:li in split(a:text, "\n", 1)
  "     let new_lines += [li."\r\n"]
  " endfor
  
  echomsg a:text
  " let a:text = a:text."1"
  " let l:new_text = substitute(a:text, '\n', '\r\n', '')
  let l:new_text = substitute(a:text, '\n', '\r', 'g')
  " let l:new_text = substitute(a:text, '\n', '\n\r', '')
  " let l:new_text = substitute(a:text, '\n', '\n', '')
  " let l:new_text = l:new_text."2"
  echomsg l:new_text
  " call chansend(str2nr(a:config["jobid"]), split(new_text, "\n", 1))
  if new_text =~ "^--"
    " want to check if it will work if I enter one more linebreak
    let l:new_text = l:new_text."\r"
  endif
  call chansend(str2nr(a:config["jobid"]), new_text)
  " call chansend(str2nr(a:config["jobid"]), split(new_text, "\r", 1))
  " call chansend(str2nr(a:config["jobid"]), split(a:text, "\n", 1))
endfunction

```

**Comment by jpalardy** [comment]
Reminds me of what I had to do with Elm [recently](https://github.com/jpalardy/vim-slime/commit/20210bf3f99bd894ef10604fa239c390500a492d).

- one line: works fine
- multiple lines: needs extra newline 🤔 

try adding a few extras newlines, does that help?

**Comment by you-n-g** [comment]
@jpalardy  thanks for your quck response.

I change `let l:new_text = l:new_text."\r"`  to  `let l:new_text = l:new_text."\r\r\r\r"` now.

But it doesn't work.  The output looks like this. 

![image](https://user-images.githubusercontent.com/465606/102612920-952d9d00-416c-11eb-90b0-5ec4318bf2b5.png)

**Comment by jpalardy** [comment]
I've never installed ipython … let me try it out and we'll see if I find a fix/workaround 😄

**Comment by jpalardy** [comment]
Hi @you-n-g 

I installed ipython and it's working great 😄  

my setup:
- macos
- brew install ipython
- using tmux
- using `let g:slime_python_ipython = 1`

![Screen Shot 2020-12-18 at 17 48 43](https://user-images.githubusercontent.com/18142/102677844-4cb8b400-4159-11eb-80df-ebe9536f7500.png)

Maybe try tmux and see if it works?

**Comment by you-n-g** [comment]
Thanks for your reply.
Maybe there are some problems with  `windows+neovim+ipython`
