### ISSUE TITLE
Installation error with VimPlug ('invalid reference: master')

### ISSUE THREAD

**Issue by vanAmsterdam** [jpalardy/vim-slime#275]
Hi,

I tried installing vim-slime through VimPlug and got this error:

```
fatal: invalid reference: master
```

maybe has something to do with renaming master branch to main?

**Comment by jpalardy** [comment]
Hi @vanAmsterdam 

That's interesting … it's my first `master` -> `main` issue.

I don't personally use VimPlug, but let me look into this.

**Comment by jpalardy** [comment]
Reading on the [vim-plug](https://github.com/junegunn/vim-plug) page, there was a change 3 months ago relating to this.

There are multiple possibilities:
- is your vim-plug at the most recent version?
- was vim-slime already installed? (maybe keeping some `master` pointer)

There's also a `branch:` option, for config.

Can I ask you to try these things and let me know what works (or doesn't)?

**Comment by jpalardy** [comment]
Tried to install vim-plug, and vim-slime through it — it worked. (so I'm not sure what's different)

**Comment by vanAmsterdam** [comment]
updating vim-plug worked; should have tried that before opening the PR; thanks for the quick response

**Comment by jpalardy** [comment]
I'm here if you need anything else 😄
