### ISSUE TITLE
troubleshoot if my key mappings work

### ISSUE THREAD

**Issue by natesire** [jpalardy/vim-slime#276]
My default Vim uses a capital case C

```ctrl-C```

I checked by running the following Vim command:

```:nmap```

But the docs say to use a lower case c

```ctrl-c```

Is this just a typo? Do you want me to fix the documentation and do a pull request? Or do some Vim configs use a lower case c?

**Comment by jpalardy** [comment]
hi @natesire,

It seems like `:nmap` says "capital C" … and that <kbd>ctrl-C</kbd> also works (_I hadn't expected that!_)

Config-wise, I'm not sure if vim mappings can differentiate between lowercase and uppercase… would "capital C" mapped as <kbd>shift-ctrl-c</kbd>?

**Comment by natesire** [comment]
Well... the lower case ```c``` in ```ctrl-c``` was not working for me, according to Slime's docs. I have a vanilla Vim install. That's why I suspected it was a key map problem because ```:SlimeConfig``` was working. Sure enough... when I checked :nmap... that was the problem. My Vim :nmap points capital C in ```shift-ctrl-C``` to the plugin.

**Comment by jpalardy** [comment]
Can you confirm if [this line](https://github.com/jpalardy/vim-slime/blob/59d5e6c4bd99f6a1825ec83e9d56a333b12be36b/plugin/slime.vim#L31) is what runs for you?

(if necessary, you can add `echom` statements to the plugin code, and check what ran with `:messages`)

**Comment by natesire** [comment]
Ok... I will debug this tonight. Happy to help. It's a fantastic plugin. Especially for polyglots.

**Comment by natesire** [comment]
I am confirming that line 31 does run

```nmap <c-c><c-c> <Plug>SlimeParagraphSend```

I cannot tell which language this is? How do I use the ```:messages``` ?

**Comment by jpalardy** [comment]
This is vimscript :-/

For echom/messages, have a look at [this](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html).

**Comment by natesire** [comment]
Thanks! Would you prefer Capital C or lower case c for the command? I think
lower case c makes more sense. But that might conflict with the key map for
the operating system. Ctrl c (lower case) is often mapped to copy. I am not
sure if Vim can actually over ride the desktop's key map... nor should it.
I did notice that ctrl c was not working a few days ago before I installed
your plugin. I will keep researching it.
