### ISSUE TITLE
did not work with vim 8.0 with python3

### ISSUE THREAD

**Issue by Dekay999** [jpalardy/vim-slime#277]
Hi everyone,

I todeay installed vim-slime on my ubuntu 18.04. But ctrl+c+c didn't give any response. 

My vim version shows that my vim supports python3 but does not support python.  So I guess I should modify the sentence 
```
let g:slime_python_ipython = 1
```
But I have no idea how to modify it. Can you help me with this? Thank you very much.

Version of vim is the following:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
```

**Comment by jpalardy** [comment]
Hi @Dekay999 

The version of python linked with vim doesn't matter … because vim-slime grabs text and send it to an external REPL, running whichever python/ipython you started.

To be clear: you need a separate REPL, running inside tmux (or screen, or one of the targets that vim-slime can send text to)

Does that help?

**Comment by Dekay999** [comment]
Thanks jpalardy! I tried to install a tmux today, and create a seesion with two panes, and  edit a .py file with vim in the left pane, and open ipython3 in the right pane. Then I select a paragraph in .py file and press `ctrl+c+c`, but still, nothing happens.

Thank you anyway. I am a beginner with vim. So I guess when I become more familier with vim, I will find the solution.

**Comment by jpalardy** [comment]
Try `:scriptnames` in the vim command-line and, from the list, see if the vim-slime files were loaded.

Add for `let g:slime_python_ipython = 1`, that will need to be added in your `.vimrc` — along with `let g:slime_target = "tmux"`, if you haven't already done so.

Good luck, I'm here if you have more questions.

**Comment by Dekay999** [comment]
It works! Thank you jpalardy, you are so nice. It turns out that  vim-slime files were not loaded.
