### ISSUE TITLE
pressing enter is required when using winpty ipython with vim-slime in MSYS2

### ISSUE THREAD

**Issue by Dekay999** [jpalardy/vim-slime#283]
Hi Jpalardy, I have been using this plugin in ubuntu system for sereral months and appreciate it. 

Recently, I work in windows 10 system and try to use this plugin to help write python code again. I installed MSYS2, and have tmux, vim, vim-slime installed. In order to run ipython in interactive mode, I ran `winpty ipython`. Here is what happened when I choose some code and press `ctrl c ctrl c`:
![image](https://user-images.githubusercontent.com/37211395/106089715-7f47ca80-6163-11eb-8ee4-3b44ef0fb54b.png)
![image](https://user-images.githubusercontent.com/37211395/106089785-a7372e00-6163-11eb-83df-85ef43d4147c.png)

What I mean is that: I need to move my cursor to the right-pane and press enter to get the code executed.

After many experiments, I believe the problem is here (line 8 of `plugged/vim-slime/ftplugin/python/plug.vim`):
```
return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
```
the '\n' in the above sentence behaves differently with the action of pressing Enter directly, because when I type the code by hands everything is OK:
![image](https://user-images.githubusercontent.com/37211395/106090357-f0d44880-6164-11eb-8946-8c490a790e59.png)
I tried many times and don't know how to fix this problem. Any suggestions would be appreciated.

**Comment by jpalardy** [comment]
hi @Dekay999 

can you try `\r` or a combination of `\r\n` and see if that changes anything?

**Comment by Dekay999** [comment]
Than kou for your quick response @jpalardy , I have tried to replace `\n` with `\n`, `\r`, `\n\r`, but none of them worked, they only generate more newlines, still have to press Enter to get the code executed.

**Comment by jpalardy** [comment]
I wonder if a delay would make a difference 🤔 

    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--", "\n"]

with the last `"\n"` by itself, it will get sent separately (and there would be slight delay)

**Comment by Dekay999** [comment]
I tried as you said, and this time I don't have to press Enter, but I got this:
![image](https://user-images.githubusercontent.com/37211395/106094373-d605d200-616c-11eb-989c-b32f856df9aa.png)
It seems that `\n` is recognized as 'invalid syntax', this is pretty weird.

> I wonder if a delay would make a difference 🤔
> 
> ```
> return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--", "\n"]
> ```
> 
> with the last `"\n"` by itself, it will get sent separately (and there would be slight delay)

**Comment by Dekay999** [comment]
If I delete the last `\n`, like this:
```
return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--"]
```
Then after `ctrl c ctrl c`, the ipython will again wait for me to press Enter, and after pressing Enter, same mistake appears:
![image](https://user-images.githubusercontent.com/37211395/106096245-216daf80-6170-11eb-9800-a6e69bba4057.png)
so I guess some symbol is added at the end of the line automatically, maybe this is related to winpty. I am not familier with winpty, maybe when I get more familiar in the future, I can locate the problem.

**Comment by jpalardy** [comment]
if you discover more, let me know — this thread might end up helping someone else

**Comment by pijucha** [comment]
I ran into the same problem in Windows. I think an extra delay in `"%cpaste -q\n"` before `\n` fixes it.
This is what works for me:
```
diff --git a/ftplugin/python/slime.vim b/ftplugin/python/slime.vim
index f52a242..405f8bc 100644
--- a/ftplugin/python/slime.vim
+++ b/ftplugin/python/slime.vim
@@ -5,7 +5,7 @@ end
 
 function! _EscapeText_python(text)
   if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
-    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
+    return ["%cpaste -q", "\n", g:slime_dispatch_ipython_pause, a:text, "--", "\n"]
   else
     let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
     let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
@@ -13,7 +13,7 @@ function! _EscapeText_python(text)
     let dedented_lines = substitute(no_empty_lines, dedent_pat, "", "g")
     let except_pat = '\(elif\|else\|except\|finally\)\@!'
     let add_eol_pat = '\n\s[^\n]\+\n\zs\ze\('.except_pat.'\S\|$\)'
-    return substitute(dedented_lines, add_eol_pat, "\n", "g")
+    return [substitute(dedented_lines, add_eol_pat, "", "g"), "\n"]
   end
 endfunction
```

**Comment by lethargi** [comment]
> I ran into the same problem in Windows. I think an extra delay in `"%cpaste -q\n"` before `\n` fixes it. This is what works for me:
> 
> ```
> diff --git a/ftplugin/python/slime.vim b/ftplugin/python/slime.vim
> index f52a242..405f8bc 100644
> --- a/ftplugin/python/slime.vim
> +++ b/ftplugin/python/slime.vim
> @@ -5,7 +5,7 @@ end
>  
>  function! _EscapeText_python(text)
>    if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
> -    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
> +    return ["%cpaste -q", "\n", g:slime_dispatch_ipython_pause, a:text, "--", "\n"]
>    else
>      let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
>      let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
> @@ -13,7 +13,7 @@ function! _EscapeText_python(text)
>      let dedented_lines = substitute(no_empty_lines, dedent_pat, "", "g")
>      let except_pat = '\(elif\|else\|except\|finally\)\@!'
>      let add_eol_pat = '\n\s[^\n]\+\n\zs\ze\('.except_pat.'\S\|$\)'
> -    return substitute(dedented_lines, add_eol_pat, "\n", "g")
> +    return [substitute(dedented_lines, add_eol_pat, "", "g"), "\n"]
>    end
>  endfunction
> ```

I had the same problem and the fix from @pijucha fixed it for me. I am running it on windows 10 with vim 8.2

@jpalardy should i create PR with @pijucha 's changes unless he wants to do it himself?

**Comment by jpalardy** [comment]
Hi @pijucha and @lethargi 

Adding delays always feels like a workaround 😩 

But if that fixed it, please send a PR 👍
