### ISSUE TITLE
 SlimeSend doesn't preserve cursor position

### ISSUE THREAD

**Issue by djmarti** [jpalardy/vim-slime#284]
Hi there,

First off, thanks for this great plugin. It makes my everyday life much more pleasant.

This issue is somewhat related to ["SlimeSend doesn't preserve cursor position #151"](https://github.com/jpalardy/vim-slime/issues/151). I reckon the problem was fixed by then, but I am experiencing it with the latest updates. Given a visual selection encompassing these three lines, from 1 to 3 (borrowing example from @qwfy)
```
1  blah  # the first column is the line number
2  blah
3  blah <- current cursor position
```
running C-c C-c should keep the position at line 3, but it always goes back to the first line. At least that's what I understand  `slime_preserve_curpos = 1` (the default) should do.

I am using nvim with "tmux" target. I can reproduce the problem with the following minimal `.vimrc`:
```vim
call plug#begin('~/.vim/plugged')
    Plug 'jpalardy/vim-slime'
call plug#end()

" Vim-slime
if exists('$TMUX')
  let g:slime_preserve_curpos = 1
  let g:slime_target = "tmux"
  let g:slime_default_config = {"socket_name": split($TMUX, ",")[0], "target_pane": ":.2"}
endif
```

Thanks!

**Comment by jpalardy** [comment]
Hi @djmarti 

I'm happy that vim-slime can brighten your day 😄 

That problem is … weird. Theoretically, you don't need `let g:slime_preserve_curpos = 1` (it's the default; it only exists for backward compatibility)

Open questions:
- same behavior in "regular" vim?
- what if you don't make your config conditional?
- what if you remove `let g:slime_preserve_curpos = 1` from your config?

Beyond that, I would recommend instrumenting the code with `echom some-debug-msg` to see what code run 🤔 

Let me know how that goes, we'll iterate.

**Comment by djmarti** [comment]
Hi @jpalardy,

Thanks for your prompt response and your suggestions. I have tried:
  * using vim instead of nvim,
  * removing the conditional `if exists('$TMUX')`,
  * removing `let g:slime_preserve_curpos = 1` from my config,

but the issue persists in all cases.

I followed your advice of sprinkling relevant parts of the code with `echom`, and found out that `winresetview` in  `SlimeRestoreCurPos`:
```vim
function! s:SlimeRestoreCurPos()
  if g:slime_preserve_curpos == 1 && exists("s:cur")
    call winrestview(s:cur)
    unlet s:cur
  endif
endfunction
```
is not called because `exists("s:cur")` is 0. Investigating this further...

Thanks again for your help!

**Comment by jpalardy** [comment]
it had been a while, I tried to follow the `s:cur` chain

![s-cur-chain](https://user-images.githubusercontent.com/18142/108607750-28ef3580-7377-11eb-83d9-8a177cbf7d01.png)

if `s:cur` isn't set, it might be because your invocation of SlimeSend is different?

**Comment by djmarti** [comment]
Thanks Jonathan for the detailed description. My code is exactly the same as the snippet above.
Isn't the relevant call `SlimeRegionSend`, rather than `SlimeParagraphSend`? My understanding is that `SlimeParagraphSend` shouldn't care about storing the cursor position, because it just "sends the paragraph the cursor is in" (although it doesn't harm that it stores the cursor position). The call `SlimeRegionSend`, on the other hand, is done in selection mode and should store the cursor position just before the call (i.e., at the "end" of the selection), otherwise the cursor moves to the beginning of the selection after the call. I may be missing something, but it doesn't seem that `SlimeRegionSend` calls `store_curpos()` from the code above.

Thanks again for your quick feedback!

**Comment by jpalardy** [comment]
interesting …

I personally almost exclusively use `SlimeParagraphSend` so I'm always in cursor-saving mode. This might be an oversight, since I don't use it much (and nobody else mentioned it)

I just tried it:
- start line-select
- select down a few lines
- <kbd>ctrl</kbd><kbd>c</kbd> <kbd>ctrl</kbd><kbd>c</kbd>
- cursor is back on the first line

this is what I expected because I started from the top — if I start from the bottom, it keeps me on top 🤔 

what's your flow?

Patching this wouldn't be too hard, let me know.

**Comment by djmarti** [comment]
Oh, I see. I think I misunderstood what "preserving current current position" was : )

My usual flow is:
  1. select a piece of code with visual mode. That selection is defined by a start and and end
  1. slime-send it
  1. go to next relevant code snippet, usually below the first selection. Repeat the process from 1.

Since I may want to submit a second piece of code below my first selection, it is convenient to leave the cursor at the end of the first selection. For example in this piece of code
```python
1  def something():    # <-start first selection
2    pass              # <- end first selection.
3
4  def something_else():  # <- start second selection
5    pass                 # <- end second selection
```

it is convenient that C-c C-c in the first selection keeps the cursor at line 2, not line 1 (that matters when functions have more than two lines).

**Comment by jpalardy** [comment]
I see :-)

I solve this problem with mappings:

```
nmap <c-c><cr>  <c-c><c-c>}j
```

in other words:
- send paragraph (anywhere on line 1-2)
- `}` -- move to end of paragraph (line 3)
- `j` -- move down 1 line (line 4)

There's also `SlimeSendCell` (check bottom of [this section](https://github.com/jpalardy/vim-slime#advanced-configuration)), if you want another option.

**Comment by djmarti** [comment]
Thanks for the tip. I could find an easy fix based on your idea. I define the key mapping
```vim
xmap <leader>sl <Plug>SlimeRegionSend gv<esc>
```
which surfaces the visual selection after calling `SlimeRegionSend`, with the cursor at the *end* position, and returns to normal mode. The behavior is now exactly what I was after.

Thanks a lot for your help and suggestions!
