### ISSUE TITLE
Problem accommodating rlwrap

### ISSUE THREAD

**Issue by kctong529** [jpalardy/vim-slime#285]
I've been trying to use `vim-slime` in `tmux` with `neovim` for `mit-scheme`. When the `tmux` target pane is in `scheme` interpreter, the performance of `:SlimeSend` is as expected. However, when the `tmux` target pane is in `rlwrap scheme`, it appears that several duplicate lines are sent in an unpredictable and inconsistent manner (e.g. the prompt is gone etc) to the target pane. The corresponding results are as below:

```
$ scheme
1 ]=> (define (dupls-removed s)
  (if (empty? (bf s)) s
      (if (member? (first s) (dupls-removed (bf s)))
          (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))

;Value: dupls-removed
```

```
$ rlwrap scheme
(define (dupls-removed s)
  (if (empty? (bf s)) s
         (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))
      (if (member? (first s) (dupls-removed (bf s)))
          (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))

;Value: dupls-removed
```

The actual function definition (which is evaluated by the interpreter) does not seem to be affected, though.

```
1 ]=> (pp dupls-removed)
(named-lambda (dupls-removed s)
  (cond ((empty? (bf s)) s)
        ((member? (first s) (dupls-removed (bf s))) (dupls-removed (bf s)))
        (else (sentence (first s) (dupls-removed (bf s))))))
;Unspecified return value
```

`rlwrap` is important for customized autocomplete within the interpreter, and I would like to have both.

**Comment by jpalardy** [comment]
Hi @kctong529 

I'm wondering what could be different … my first thought is "bracketed paste mode" (maybe)

Ideas to try:
- does (gnu) screen exhibit the same behavior?
- on [this line](https://github.com/jpalardy/vim-slime/blob/main/autoload/slime.vim#L80), in your local clone of slime, does adding the `-p` flag change anything?

unrelated to above, does this also happen with "regular" vim?

I'll check some things on my side, but let me know what you find.

**Comment by jpalardy** [comment]
I installed mit-scheme and tried this:

![scheme-w-wo](https://user-images.githubusercontent.com/18142/108608122-ab78f480-7379-11eb-9217-3a49dc43d4b0.png)

the result is the same, but it's true the prompt disappeared under `rlwrap` (3rd arrow)

Hmmm… I just tried again and there's a mix of inputs/outputs intertwined together. Let me try more things.

**Comment by jpalardy** [comment]
there's an intersection of technologies at the core of this problem… when I tried GNU screen, it seemed to work fine 😐 

my combination of technologies:
- zsh
- tmux
- readline (indirectly, for rlwrap)
- iterm2?

I found a solution to your problem, but it's not necessarily "generalizable":
- in vim, grab a paragraph
- trim right whitespace (any trailing spaces and newlines)
- send with slime, using [bracketet paste mode](https://cirw.in/blog/bracketed-paste), … in practice adding the `-p` to the tmux command
- sending a "naked" newline to tmux to accept the bracketed paste

why does this work? what is going on? … here's my analysis, so far:
- without bracketed mode, `rlwrap` doesn't know this is a "paste", so it receives a block of text, tries to echo it _WITH_ newlines (with causes the _sometimes_ messy mixed-up output) while trying to process each line separately (a race-condition)
- with bracketed mode, it receives "the whole block" in one chunk … but zsh holds the paste for an explicit "return" from the user (blocking on highlighted text, if you've noticed this behavior before)

example:

![flow](https://user-images.githubusercontent.com/18142/108610276-63fa6480-7389-11eb-91ae-28bd58a21966.png)

this is unblocked by following with

`tmux send-keys -t '{last}' ^M`

here's my local experimental diff, if you want to try on your side:

```diff
diff --git vim/pack/bundle/start/slime/autoload/slime.vim vim/pack/bundle/start/slime/autoload/slime.vim
index 62a54b3..77da4a5 100644
--- vim/pack/bundle/start/slime/autoload/slime.vim
+++ vim/pack/bundle/start/slime/autoload/slime.vim
@@ -75,9 +75,11 @@ function! s:TmuxCommand(config, args)
 endfunction
 
 function! s:TmuxSend(config, text)
-  call s:WritePasteFile(a:text)
+  let trimmed = substitute(a:text, '\_s*$', '', '')
+  call s:WritePasteFile(trimmed)
   call s:TmuxCommand(a:config, "load-buffer " . g:slime_paste_file)
-  call s:TmuxCommand(a:config, "paste-buffer -d -t " . shellescape(a:config["target_pane"]))
+  call s:TmuxCommand(a:config, "paste-buffer -p -t " . shellescape(a:config["target_pane"]))
+  call s:TmuxCommand(a:config, "send-keys -t " . shellescape(a:config["target_pane"]) . " ^M")
 endfunction
 
 function! s:TmuxPaneNames(A,L,P)
```

**Comment by kctong529** [comment]
Thanks for your help, Jonathan! This workaround solves most of the problem for me. I just followed your local `slime.vim`, and I believe the race-condition is gone. However, when I tried to send the same paragraph for more than once, something weird showed up.

```
$ cat ~/.slime_paste
(define (dupls-removed s)
  (if (empty? (bf s)) s
      (if (member? (first s) (dupls-removed (bf s)))
          (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))% 
```

```
[200~(define (dupls-removed s)
  (if (empty? (bf s)) s
      (if (member? (first s) (dupls-removed (bf s)))
          (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))^[[201~1 ]=> (define (dupls1 ]=> (define (dupls-removed s)
  (if (empty? (bf s)) s
      (if (member? (first s) (dupls-removed (bf s)))
          (dupls-removed (bf s))
          (sentence (first s) (dupls-removed (bf s))))))

;Value: dupls-removed
```

Or in a simpler case,

```
$ cat ~/.slime_paste
(define (square n)
  (* n n))%
```

First attempt:

```
1 ]=> (define (square n)
  (* n n))

;Value: square
```

Second attempt:

```
[200~(define (square n)
1 ]=> (define (square n)
  (* n n))

;Value: square
```

```
$ tmux paste-buffer
(define (square n)
  (* n n))% 
```

**Comment by jpalardy** [comment]
Do you mean the `[200~` ?

That's the "start-paste" escape sequence. But, yes, I've seen that sometimes it shows up and sometimes it doesn't. I saw that rlwrap had a fairly recent [discussion](https://github.com/hanslub42/rlwrap/issues/113) about bracketed paste … but I don't know if this is a problem (or whether it's going to get fixed)

I tried different permutations, but the recipe I gave you was the most successful one (even if not perfect)

If you find a fix for this, let me know.
