### ISSUE TITLE
In scala escape paste mode, ^D is interpreted as an unknown symbol.  

### ISSUE THREAD

**Issue by vando026** [jpalardy/vim-slime#286]
Hi, thanks for the great plugin. I followed this thread #252 with interest  @LeoKavanagh @jpalardy.  For the _EscapeText_scala function, my Ubuntu 20.04 install, neovim 0.4.3, and tmux, interprets the "^D" as a possible unknown character. Screenshot attached. 

![EscapeTest](https://user-images.githubusercontent.com/36604253/109165687-211b0100-777c-11eb-8ebc-549ff3fc3160.png)

I replaced it with "^D" and even tried "C-d", but it doesn't work and scala remains in paste mode when I call vim-slime. 

![shot2](https://user-images.githubusercontent.com/36604253/109167035-a0f59b00-777d-11eb-9407-8ea6ee5e1813.png)

However, when I dont call vim-slime, and scala is still in paste mode,  I can exit using 

exec '!tmux send-keys -t right C-d'

(or whatever -t is selected). So something is not working with the "^D" part in the second return statement. Do you have any suggestions on how to fix this?

**Comment by jpalardy** [comment]
hi @vando026 

that is weird! … not sure how it got to be like this.

I created #287 to address this. Could you try that branch and let me know?

**Comment by vando026** [comment]
Apologies for the late reply. I pulled the fix-control-d branch and it works as expected. 

Thank you for this.

**Comment by jpalardy** [comment]
Merged #287 on `main`

Let me know if it causes problems.
