### ISSUE TITLE
Plug Mappings problematics in some cases

### ISSUE THREAD

**Issue by mdedonno1337** [jpalardy/vim-slime#288]
Hi,

Making a PR in another project, I was redirected to this page (https://vimways.org/2018/the-mapping-business/) regarding how to expose a function with the <Plug> keyword.

Willing to edit my init.vim configuration, I saw that slime is exporting the functions without the parents.
I think it could be useful to make this change for example with this kind of usage:

```
nmap <F10> <Plug>(SlimeLineSend)j
```
which will send the current line and go down, which is difficult to do at the moment (I think).
Note the `j` after the `)`.

What do you think?
It also means that it would be a breaking change (or we  have to export twice the functions).

To think about/do:
- [ ] impact at first run (configuration)
- [ ] deprecation (notify the user for the "old" export, but still export it)

**Comment by jpalardy** [comment]
Hi @mdedonno1337 

I'm not sure I follow. I'll have to go read the article before I get back to you.

**Comment by mdedonno1337** [comment]
Just the first paragraph, the rest is not useful in this case.

The aim would be to render the export of the plugin more universal (and idiomatic to vim), to allow users to use the mapping to do some other actions in the mapping (one example I have in mind is, like in other editors, a key to send the current line and go down one line, with `<Plug>(SlimeLineSend)j`).

For the record:

> Suppose we write a snippet plugin with these two mappings:
> 
> ```
> nnoremap <silent> <Plug>MyPluginFor ...internal RHS 1...
> nnoremap <silent> <Plug>MyPluginFori ...internal RHS 2...
> ```
> The first mapping might insert some for-loop snippet, and the second one could insert a for-loop variant that uses a variable called ‘i’.
> 
> So far so good, but now a user finds it convenient to go into insert mode right after inserting the first for-loop variant, and they want to make a mapping for it:
> 
> ```
> " Intent: call <Plug>MyPluginFor and hit 'i' to go into insert mode
> nmap <Leader>i <Plug>MyPluginFori
> ```
> You see the problem: the mapping will inadvertently call the wrong mapping from our snippet plugin!
> 
> Even though those cases are rare, it is common practice to avoid them altogether by surrounding the part after <Plug> in braces:
> 
> ```
> nmap <silent> <LocalLeader>f <Plug>(MyPluginFor)
> nmap <Leader><Tab> <Plug>(MyPluginFori)
> ```
> In user’s vimrc:
> 
> ```
> " Intent: call <Plug>(MyPluginFor) and hit 'i' to go into insert mode
> nmap <Leader>i <Plug>(MyPluginFor)i
> ```
> Problem solved.

**Comment by jpalardy** [comment]
Hi @mdedonno1337 

I see what you mean now. Personally, I've worked around this with:

<img width="349" alt="Screen Shot 2021-03-12 at 22 29 29" src="https://user-images.githubusercontent.com/18142/111021626-a8729200-8382-11eb-8ec4-ded027e19393.png">

(from my config)

The last example being, as I understand, _almost_ exactly the case you mentioned.
