### ISSUE TITLE
no input with tmux 3.0a on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by expositum** [jpalardy/vim-slime#289]
Great plugin!  I use this plugin all the time in other contexts and it works fine, but with a fresh system build it seems to not be working.

I'm running:
```
        * Ubuntu 2020 LTS
        * tmux 3.0a (default) with no .tmux.conf file
        * vim 8.1.2269 (default) with no .vimrc file
```

So this should be all defaults.  I installed vim-slime directly from git as instructed in the README to ~/.vim/pack/plugins/start

It works just fine with "screen", but with "tmux" I see nothing in the tmux pane
terminal 1:
```
        $ tmux new -s mytest
        <mytest $>
```

terminal 2:
```
        vim session,
        : let g:slime_target = "tmux"
        enter a line "ASDFASDF"
        ctrl-c, ctrl-c
                tmux socket name or absolute path: default
                tmux target pane: : mytest
        <nothing appears in terminal 1, mytest pane>
```

Is there a way to turn on verbose debugging/logging for vim-slime?

**Comment by jpalardy** [comment]
hi @expositum 

a quick test … the `-s mytest` would refer to the session, while the config of target pane wouldn't be `mytest` (thought there's a syntax for it, I forgot)

can you try using `echo $TMUX_PANE` (in terminal 1) and using the `%nnn` output as the target pane in terminal 2?

**Comment by expositum** [comment]
Interesting, the convenience of specifying the session name worked previously (quite conveniently and naturally).  What do you think changed?

Your suggestion sort of worked.  If I open multiple tmux sessions:

```
    terminal 1:
        tmux new -s test1
        <test1>$ echo $TMUX_PANE
        %0

    terminal 2:
        tmux new -s test2
        <test2>$ echo $TMUX_PANE
        %1

    terminal 3:
        tmux new -s test3
        <test3>$ echo $TMUX_PANE
        %2

    terminal 4:
        vim , SlimeConfig
        tmux socket name or absolute path: default
        tmux target pane: :0
```

The output appears in terminal 3/<test3> (or whatever was the last session I started).  I can't seem to target sessions <test1> or <test2> once I start a newer session.

Thanks for you help.

**Comment by jpalardy** [comment]
hi @expositum 

the answer to `tmux target pane:` is `%0` — not `:0` (those mean slightly different things)

I tried your setup locally (running tmux `stable 3.1c`), and I could send to "test1" if I used `test1:0` or `test1:` as target pane in the slime config. I didn't remember the colon-and-dot syntax, so I had to look up `man tmux`:

> target-pane (or src-pane or dst-pane) may be a pane ID or takes a similar
> form to target-window but with the optional addition of a period followed
> by a pane index or pane ID, for example: `mysession:mywindow.1'.  If the
> pane index is omitted, the currently active pane in the specified window
> is used.

does that work for you? (although I would recommend the `%nn` syntax)

**Comment by expositum** [comment]
That worked like a charm, thank you!
