### ISSUE TITLE
Error using vim-slime E492: Not an editor command: SlimeSend1

### ISSUE THREAD

**Issue by gerazov** [jpalardy/vim-slime#292]
Hi guys! Great and quite an essential plugin! :+1: 

I can't seem to make it work. I installed it via ```Plug 'jpalardy/vim-slime', {  'branch': 'main'}``` and everything went fine with ```PlugInstall``` but then I can't run any of the commands, e.g.:

```
:SlimeSend1
E492: Not an editor command: SlimeSend1
```

It doesn't list them when I do `:Sl` and press `Tab`, so they're not there I guess :thinking:

**Comment by gerazov** [comment]
It now works :thinking:

**Comment by jpalardy** [comment]
Hi @gerazov 

Glad it worked for you. I'll be here if you need anything.

**Comment by gerazov** [comment]
It's awesome :sunglasses: Thanks!
