### ISSUE TITLE
Improve pasting in IPython: %cpaste to %paste to Ctrl+Shift+V

### ISSUE THREAD

**Issue by gerazov** [jpalardy/vim-slime#293]
Awesome plugin :sunglasses: 

Makes it possible to use Vim as a IDE :love_you_gesture: 

I was wandering if it's better to use `%paste` for the `slime#send` instead of `%cpaste`. I know that `%paste` requires `tk` but that is not necessarily a problem, and it does color the syntax of the sent text.

Of course the best would be to just use the new `Ctrl+Shift+V` as discussed in #123, as can be seen here:

![image](https://user-images.githubusercontent.com/15214418/116302940-11cb2a80-a7a2-11eb-9153-f2bde719e8e1.png)

The last option also allows for potential editing of the code before execution, e.g. removing the `self` reference from this pasted function. 

I've tried to implement this manually by looping through the lines and sending them one by one using `SlimeSend0` (https://github.com/hanschen/vim-ipython-cell/pull/27). It does kinda work but it messes up indentation if the code is deindented :sweat_smile:

![vim-edit-region](https://user-images.githubusercontent.com/15214418/116162185-914ef000-a6f5-11eb-9404-86350331648c.gif)

Is it possible to send the `Ctrl+Shift+V` through `SlimeSend`?

**Comment by jpalardy** [comment]
Hi @gerazov 

> Awesome plugin 😎

Thank you 😄 

As in the other issues, not being a python user myself, it's hard to weigh in. If you send a PR, I'm definitely open to merging it, especially if other people can give it a 👍  / 👎  and we iterate on it.

> Is it possible to send the Ctrl+Shift+V through SlimeSend?

I … don't know. I've sent other sequences over (<kbd>ctrl</kbd><kbd>L</kbd>, for example). See some examples [here](https://github.com/jpalardy/dotfiles/blob/main/vim/plugins.vim#L24-L26).

Let me know what you find.

**Comment by gerazov** [comment]
Ok deal :+1:

**Comment by gerazov** [comment]
I can't seem to find how to send a `Ctrl+Shift+v` sequence as a string. In your example is `\x15` coding a `Ctrl`?

**Comment by jpalardy** [comment]
The github preview hides the details:

![github-vs-vim](https://user-images.githubusercontent.com/18142/116477867-0d4e5280-a832-11eb-9c09-5468fc387b25.png)

line 24 is "ctrl-l"  
line 25 is "ctrl-u" ("\x15" is ASCII hex 15)

I got those straight from vim … in insert mode, <kbd>ctrl</kbd><kbd>v</kbd>, <kbd>ctrl</kbd><kbd>u</kbd>, <kbd>esc</kbd> (back to normal mode), put the cursor on the character, <kbd>g</kbd><kbd>a</kbd> -- status bar will show details

![after-ga](https://user-images.githubusercontent.com/18142/116478473-f78d5d00-a832-11eb-9383-ec30322bcd3c.png)

ctrl-shift-v only insert ctrl-v … which I was afraid it would do.
