### ISSUE TITLE
<C-c> <C-c> just repasting text into my file instead of activating slime

### ISSUE THREAD

**Issue by harshasomisetty** [jpalardy/vim-slime#294]
I just installed vim-slime, but I'm having a hard time activating the text send function with <C-c>. Everytime I try the command, it just pastes a bunch of text into my buffer and doesn't do anything. Not even sure what information I should be providing. 

I grepped my entire vim config to see if < C-c> is mapped to anything else, and it looks like it isn't. 
I have python3 support. Any advice on what to do?

**Comment by jpalardy** [comment]
Hi @Empyr3an 

This seems like it could be a problem with the "destination". If the destination is the same pane you're in, it would explain pasting _into_ vim.

Can you provide more details? (is this tmux/screen/other? … what's the destination?)
 
Also, to eliminate interactions, you can try to only run vim-slime (and turn off other plugins during your tests)
