### ISSUE TITLE
Ideas on "sending" code in a markdown file

### ISSUE THREAD

**Issue by huijunchen9260** [jpalardy/vim-slime#295]
Daer Palardy:

Recently I am working on python (yes another college students have to use python lol), and I happens to notice that [jupytext.vim](https://github.com/goerz/jupytext.vim) is able to automatically transform jupyter notebook into a markdown file, and then we can just edit the markdown file. When we leave vim, this plugin can transform this markdown file back to ipynb file and still a valid jupyter notebook file.

Everything above is great, but the development using this method is cumbersome, since the filetype is read as markdown, vim-slime doesn't use `cpaste` magic to paste the python code correctly. 

Then I come up with the following possibly greedy function, and I am wondering whether it is possible to achieve it.

It is possible to allow vim-slime to automatically decide the "filetype" it should send based on the markdown code block?

For example, if the code block looks like:

```
\`\`\`python
import numpy as np
\`\`\`
```

then send the code block to the assigned window as python.

Hope this idea can work out. If you find it difficult to implement it or has no intention to do it, feel free to close it.

**Comment by jpalardy** [comment]
Hi @huijunchen9260 

I see the problem … I don't have a "general" solution for this, but there might be an easy workaround: in the directory of the vim-slime plugin, either softlink the extension/filetype name to the python directory … or, copy the directory over.

Let me know if that works 😄

**Comment by huijunchen9260** [comment]
As I `mkdir` a `markdown` directory inside the `ftplugin` and copy the `slime.vim` file over to the `markdown` directory, modify the following line from 

```vimL
function! _EscapeText_python(text)
```

into 

```vimL
function! _EscapeText_markdown(text)
```

It magically works lol

**Comment by jpalardy** [comment]
awesome!

(I had forgotten to rename the function, good catch)

**Comment by huijunchen9260** [comment]
Lol, somehow I just notice that.

Do you think making this function become general worth it? I feel that right now `vim-slime` is using vim filetype to decide which language to use, it might just override the default filetype using some preconfigured filetype?

**Comment by jpalardy** [comment]
I'm not sure how to "fix" this. I don't think _more_ configuration is necessarily the right answer.

I use rmarkdown and vim-slime into a R REPL without problem. This problem happens because Python code needs to be transformed into something palatable for its REPL.

I can think of other workarounds for this. For example, binding a keyboard shortcut that switches the FT, sends it to vim-slime, and switches the FT back …

[This](https://github.com/jpalardy/vim-slime#how-to-override-language-transformations) might also work.

**Comment by huijunchen9260** [comment]
Perfect! Now I can simply delete the `markdown` directory and add the following stuff into my `init.vim`:

```vimL
function SlimeOverride_EscapeText_markdown(text)
  if !exists("g:slime_dispatch_ipython_pause")
    let g:slime_dispatch_ipython_pause = 100
  end

  if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
    return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]
  else
    let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
    let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
    let dedent_pat = '\(^\|\n\)\zs'.matchstr(no_empty_lines, '^\s*')
    let dedented_lines = substitute(no_empty_lines, dedent_pat, "", "g")
    let except_pat = '\(elif\|else\|except\|finally\)\@!'
    let add_eol_pat = '\n\s[^\n]\+\n\zs\ze\('.except_pat.'\S\|$\)'
    return substitute(dedented_lines, add_eol_pat, "\n", "g")
  end
endfunction
```

**Comment by grwlf** [comment]
Hi. Recently I wrote a [LitREPL](https://github.com/grwlf/litrepl.vim) vim-plugin and a library which does something very close: it parses Markdown/Latex code, extracts \`\`\`python sections, pipes them through the background interpreter and pastes the result back into the file.
