### ISSUE TITLE
vim slime not using %cpaste? indentation problems

### ISSUE THREAD

**Issue by mufernando** [jpalardy/vim-slime#296]
For some magical reason vim-slime stopped working for me. I'm trying to send multi-line text from vim to ipython and it is not wrapping it around %cpaste, thus generating syntax errors.

I have the following in my .vimrc:

```
let g:slime_target = "tmux"
let g:slime_paste_file = "$HOME/.slime_paste"
let g:slime_python_ipython = 1
```

With only one indented line it works fine, but when you have more than one you start getting errors:

<img width="174" alt="Screen Shot 2021-08-03 at 10 44 48" src="https://user-images.githubusercontent.com/9950100/128061849-3f003935-57e9-4d95-9de9-3703bf7b7644.png">

<img width="547" alt="Screen Shot 2021-08-03 at 10 46 16" src="https://user-images.githubusercontent.com/9950100/128061972-7dcb064f-91ba-4b23-8261-1a7fe0edf32a.png">

**Comment by jpalardy** [comment]
Hi @mufernando 

You said:

> For some magical reason vim-slime stopped working for me.

Was it working before … and then it stopped working? Something must have changed, no? (other plugins, vim version, or ipython)

**Comment by muhark** [comment]
I have the same problem when trying to use vim-slime with jupyter console.

Jupyter console doesn't support the %cpaste magic, but when `let g:slime_python_ipython = 1` is disabled I get the same cascading indents issue as above.

**Comment by mufernando** [comment]
Hi all,

I think it was something I installed in one of my conda environments that messed up with vim-slime. But I couldn't figure out exactly what.

I'll close this issue, but a band-aid to this problem is to turn off auto-indent using the following ipython magic:

```
%autoindent off
```

**Comment by pinggit** [comment]
@mufernando @jpalardy 
this indentation issue is weird.

I can manually copy the code and paste into ipython. it works well.
how come it does not work for vim?

with the %autoindent off I don't see the wrong indentation, but the code was pasted only without being executed.
I need to manually hit enter again to get it executed.

for example in this dummy code:

class Nop(object):
    def nop(*args, **kw): pass
    def __getattr__(self, _): return self.nop

with my map:

 nmap ,sp <Plug>SlimeParagraphSend

the code was sent to ipython, correctly:

[ins] In [51]: class Nop(object):
          ...:     def nop(*args, **kw): pass
          ...:     def __getattr__(self, _): return self.nop
          ...:
but it won't be executed automatically. 

I guess we only need to add one more <CR> in the map, but how to?

**Comment by jpalardy** [comment]
hi @pinggit 

can you try the latest version of vim-slime with `let g:slime_bracketed_paste = 1` in your config?

(it _might_ work 🤔 )
