### ISSUE TITLE
Not working with QtConsole

### ISSUE THREAD

**Issue by Freddyilha** [jpalardy/vim-slime#297]
SO: ArchLinux

Hello, I have defined on my vimrc the 'let g:slime_target = "x11"'  and when I call *SlimeConfig* it asks which tmux socket and pane, although it works fine with tmux that's not what I want to use with QtConsole.
![image](https://user-images.githubusercontent.com/5214640/128795778-bc9fbc1d-b75d-4fb4-9c8d-b1e2fe67fb2d.png)

The *xdotool* is installed and working:
![image](https://user-images.githubusercontent.com/5214640/128795432-a300c7ea-34e6-
4a95-a4d0-f807498859c6.png)

Vim version and features:
![image](https://user-images.githubusercontent.com/5214640/128795032-14e1ae81-0570-4a0a-8a2e-711048b816e6.png)

Am I missing something?

**Comment by jpalardy** [comment]
Hi @Freddyilha 

I just tried locally and it does fail silently (when it fails) 🤔 

@ynco any thoughts?

In the meantime, I would recommend peppering the plugin code with `echom` statements, and reading out the output in `:messages` (it's console.log for vim! -- [details](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html))

Let me know what you find

**Comment by Freddyilha** [comment]
Ok, so what I've discovered is that the variable is that the variable **slime_target** is really been ignored and it's stuck in tmux. I put a **echom** at each **section** and on each **function!** call to see what is been called, is there some kind of cache in vim?
![image](https://user-images.githubusercontent.com/5214640/128947881-53e4d855-744f-4aa9-92ac-f8063f369220.png)

**Comment by jpalardy** [comment]
whoah…

although … this points towards your configuration not being picked up.

did you try to `echom` in your vimrc?  I wonder if something else is changing it… some things to try:
- temporarily disabling other plugins to remove "moving parts"
- check `scriptnames` to see what, and in what in order, is being loaded

**Comment by Freddyilha** [comment]
Ok, I'm stupid, there was another definition of the slime_target at the end of my vimrc sorry for this.

But now I saw that it's only send the text without the Return command. Is it intended?

**Comment by jpalardy** [comment]
hi @Freddyilha 

Happy to see you fixed some of it 😄 

> But now I saw that it's only send the text without the Return command. Is it intended?

that depends on the language plugin, and the target REPL ... what are the moving parts? and what's the behavior you see? (send me a screenshot, if possible)

**Comment by Freddyilha** [comment]
![image](https://user-images.githubusercontent.com/5214640/129122103-11d4d2fb-bc02-4ff6-9798-7b440fdbd25f.png)

I'm pressing ```ctrl+c ctrl+c``` an the text from the paragraph is sent to QtConsole but since there is no Return command, it get concatenated.

**Comment by jpalardy** [comment]
hmmm… python… it's always python 😆 

did you follow [this](https://github.com/jpalardy/vim-slime/tree/main/ftplugin/python)?

**Comment by jpalardy** [comment]
If you're up to experimenting, there are a bunch of places in the code dealing with `\n` or `\r` … you can try switching one for the other, or using combinations (the DOS/windows one).

I would start with `ftplugin/python/slime.vim` and debug from there.

**Comment by Freddyilha** [comment]
The text have the null character(^@) that is not replaced at all.
![image](https://user-images.githubusercontent.com/5214640/129296431-314a0993-235c-48d7-bb5d-1ea568e85078.png)

I tried to send directly from xdotool but the **\r** isn't even recognized. 
![image](https://user-images.githubusercontent.com/5214640/129296525-6b9f6292-f043-46a7-807c-1c22e8d28ac5.png)

Also tried to read [IPythonMagic](https://ipython.readthedocs.io/en/stable/interactive/magics.html) the documentation for the magic methods but could't find one to use ='(

**Comment by jpalardy** [comment]
sorry, this isn't a combination of tools I use (python, xdotool)

let me know if you find something — or someone else might see this and have some answers

**Comment by Barzi2001** [comment]
> I haven't read this but this not work with QtConsole : ![image](https://user-images.githubusercontent.com/5214640/129217536-6d35fd13-ead4-4d7d-96ef-d708d2622367.png)
> 
> But QtConsole works with multiple lines when I paste directly the code with `ctrl+v` or manually pressing `ctrl+Return`to break the line: ![image](https://user-images.githubusercontent.com/5214640/129217949-499c5225-cdbd-4bd5-a690-10c025f882f6.png)
> 
> When sending multiples lines it does not recognize the break line i don't know exactly who is the problem here xdotool, qtconsole, vim or python. Any idea?
> 
> I'll keep searching for something.

I have the same problem on Windows 10. 
I missed that this issue mentioned the line break problem for which I opened a thread in the Discussion section and on Reddit. 
Hopefully someone will find a solution (I don't have the competence for solving these kind of issues).

**Comment by jpalardy** [comment]
Let's hold on this and see if it comes up again ^

I'm hesitant to change anything, considering how long that code had _not_ changed.

Thanks for reporting back your findings, in the meantime 👍

**Comment by Barzi2001** [comment]
Hi! 
It was sometime I haven't used vim-slime and I re-opened it again right now, and surprisingly the problem appeared again, in-spite of the hack I did above. 
I think we can test your proposal if you tell me step-by-step what I should try to do. :)

**Comment by jpalardy** [comment]
Hi @Barzi2001 

Here's the code, for reference:  (`ftplugin/python/slime.vim`)

![Screen Shot 2021-11-07 at 23 10 21](https://user-images.githubusercontent.com/18142/140698949-d81fea3e-a618-40ba-a43f-0938c07d0d3c.png)

Two things to try:
- let's try increasing `g:slime_dispatch_ipython_pause` to a larger value … maybe 1000?
- let's put another pause after the text: (line 8)

```vim
return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, g:slime_dispatch_ipython_pause, "--\n"]
```

let me know how that behaves 😄

**Comment by Barzi2001** [comment]
Tested right now.
Things are just slower... but the problem persists :(

Any other idea that I could try? :) 
I don't want to start using Spyder because of this :(

**Comment by jpalardy** [comment]
Hi @Barzi2001 

I think you already tried various combinations of [ `\r` `\n` ] ?

I … don't have any other ideas for this at the moment.

**Comment by Barzi2001** [comment]
> Hi @Barzi2001
> 
> I think you already tried various combinations of [ `\r` `\n` ] ?
> 
> I … don't have any other ideas for this at the moment.

Yes, I did. 
I made some more tests today and I found something interesting. 
The slime **randomly** work with pretty much any combination I tested so far in `line 8`, but not with the original setting. 

Perhaps the cleanest implementation is the following:

`return ["%cpaste -q","\n",a:text,"--","\n"]`

but I also tried, e.g. 
 
`return ["%cpaste -q", g:slime_dispatch_ipython_pause, "\n", a:text, g:slime_dispatch_ipython_pause,"--", g:slime_dispatch_ipython_pause, "\n"]`
`...`
and for different values of `g:slime_dispatch_ipython_pause` obtaining the same random result all the times. 

This is an example of what happens by `<C-c><C-c>`-ing several times in a row. 
As you see in `In [22]:` and `In [23]:` it worked, then it didn't work any longer. Then, it eventually work again, then not and so on and so forth. All completely random. 

![image](https://user-images.githubusercontent.com/10845685/140945008-1a138e6c-63ab-4ba1-aa70-d20a43605ebe.png)

**Comment by jpalardy** [comment]
Hi @Barzi2001 

That certainly sounds like a race-condition (or something related to timing)

At this point, it might be worth going "upstream" to see if that project can help. (or, reading their code 🤔  … don't know how deep and complicated that would be)

**Comment by Barzi2001** [comment]
Auch! It sounds like a tough problem which is outside my scope of competence and skills.  
I am afraid that I won’t be able to solve it by myself. :( 

Sad that I cannot use this setup with Windows:(

Btw, which project do you mean?

**Comment by jpalardy** [comment]
I meant whatever you use as a REPL. (qtconsole? well, that's how this thread started off)

**Comment by Barzi2001** [comment]
Ok! 
Btw, given that we are going off-topic and this problem is kinda hidden, I was wondering if I should open an issue for this specific Windows 10 problem? 

Maybe someone will notice and pick it up. What do you think? 🙂

**Comment by jpalardy** [comment]
yes, let's do that 👍

**Comment by Henderake** [comment]
I managed to make it work with Jupyter QtConsole by adding the override to my `.vimrc`:
```vim
let g:slime_x11_lf_to_cr = 1

function! SlimeOverride_EscapeText_python(text)
  let escaped_text = _EscapeText_python(a:text)
  if g:slime_target =~ "x11" && exists("g:slime_x11_lf_to_cr") && g:slime_x11_lf_to_cr
      return substitute(escaped_text, '\n', '\r', 'g')
  end
  return escaped_text
endfunction
```

**Comment by MarcoCamilo** [comment]
@Henderake Could you share the rest of your slime configuration? I'm setting up slime using lazy.nvim and don't know how this code would fit with the rest of the plugin lua config. Here's what I have so far:

```
return {
  "jpalardy/vim-slime",
  init = function()
    vim.g.slime_target = "tmux"
}
```

This would be for working with tmux, but there it doesn't output plots. So I think qtconsole would be the solution. 

I'm trying to make this work, since I really want to work with plotting on ipython in a lightweight environment like nvim. I feel I'm so close to making this work, as slime works awesome in sending the lines not only to tmux but with this possibly to qtconsole
