### ISSUE TITLE
vimterminal support requires vim built with :terminal support

### ISSUE THREAD

**Issue by ahmedshaaban1** [jpalardy/vim-slime#298]
Hi, 
After installing the vim-slime, ctr+c ctrl+c gave me the following error: 

```
Error detected while processing function slime#send_op..slime#send..<SNR>31_SlimeGetConfig..<SNR>31_SlimeDispatch..<SNR>31_Vi
mterminalConfig:
line    2:
vimterminal support requires vim built with :terminal support
```

Vim version 7.4.629      

Any ideas

**Comment by jpalardy** [comment]
Hi @ahmedshaaban1 

which `g:slime_target` did you set? (I have a feeling you might need an newer version of vim 🤔 )

**Comment by ahmedshaaban1** [comment]
Thanks, I set it to vimterminal.
