### ISSUE TITLE
"filetype plugin indent off" breaks slime_python_ipython

### ISSUE THREAD

**Issue by TillFalko** [jpalardy/vim-slime#304]
Thank you for this plugin.

I noticed that when I include 
```
filetype plugin indent off
```
 in my vimrc, then
```
let g:slime_python_ipython = 1
``` 
no longer works, i.e. the selected text is pasted line for line instead of using the "%paste -q" command.
The minimal vimrc (or init.vim since I use nvim) that I could reproduce this behavior is
```
call plug#begin()
Plug 'jpalardy/vim-slime'
call plug#end()
filetype plugin indent off

let g:slime_target = "x11"
let g:slime_python_ipython = 1
```
I am not familiar enough with vimscript to know if this even is a bug that can be fixed, but I thought I'd mention it.

**Comment by jpalardy** [comment]
Hi @TillFalko 

My understanding is that `filetype plugin indent off` does 2 things:
- turns off `plugin`
- turns off `indent`

if `plugin` isn't running, python files aren't detected ... which means that mode won't trigger in vim-slime

here's what I found in vim's help:

![Screen Shot 2021-11-29 at 17 36 38](https://user-images.githubusercontent.com/18142/143969874-e45e99e7-3c72-478e-adc7-ec48ca84e89b.png)

**Comment by TillFalko** [comment]
That makes sense. Thank you. After removing the word `plugin` it works perfectly.
