### ISSUE TITLE
`g:slime_default_config` does not work with Tmux

### ISSUE THREAD

**Issue by fasterius** [jpalardy/vim-slime#305]
I've been using vim-slime for some time, so thanks for an excellent plugin! I recently wanted to try out how it worked together with Tmux rather than the vim terminal, which I had been using previously. When following the documentation and setting

```
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
```

It does not work, and I get the defaults specified inside `s:TmuxConfig()`, which uses

```
let b:slime_config = {"socket_name": "default", "target_pane": ":"}
```

I looked into the code and found the `s:SlimeGetConfig()` function, which I think is supposed to propagate values from `g:slime_default_config` into `b:slime_config`, but it doesn't seem to work for me. If I manually set `b:slime_config` to my desired values inside my `vimrc` everything works, but that's not how it's supposed to work, right? Am I doing something wrong?

**Comment by jpalardy** [comment]
Hi @fasterius 

That's interesting … that's similar to my [personal config](https://github.com/jpalardy/dotfiles/blob/main/vim/plugins.vim#L19-L22).

For this type of problem, I recommend:
- making a backup of your dotfiles
- restart you vim config with the minimum you need
- include vim-slime and its config 😄 

What's the behavior then?

You can start adding back things until it break again. Let me know how that goes.

**Comment by fasterius** [comment]
Thanks for your quick reply! I have already tried this, sadly, to no avail. The vim config I have tried is as follows:

```
call plug#begin('~/.vim/plugged')
Plug 'jpalardy/vim-slime',             { 'as': 'slime' }
call plug#end()

let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
let g:slime_dont_ask_default = 1
let g:slime_paste_file = "$HOME/.slime_paste"
```

And I still get the problems described above and in the other issue (#306). Any other ideas?

**Comment by jpalardy** [comment]
Can you try sprinkling the plugin's code with `echom` (see [this](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html)) to see what runs and what doesn't?

You can do the same to your vimrc, to make sure 🤔 

Let's get to the bottom of this 😄

**Comment by fasterius** [comment]
Okay, this is the changed plugin code:

```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Tmux
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

function! s:TmuxCommand(config, args)
  echom "TmuxCommand - function ran"
  let l:socket = a:config["socket_name"]
  " For an absolute path to the socket, use tmux -S.
  " For a relative path to the socket in tmux's temporary directory, use tmux -L.
  " Case sensitivity does not matter here, but let's follow good practice.
  " TODO: Make this cross-platform. Windows supports tmux as of mid-2016.
  let l:socket_option = l:socket[0] ==? "/" ? "-S" : "-L"
  return system("tmux " . l:socket_option . " " . shellescape(l:socket) . " " . a:args)
endfunction

function! s:TmuxSend(config, text)
  echom "TmuxSend - function ran"
  call s:WritePasteFile(a:text)
  call s:TmuxCommand(a:config, "load-buffer " . g:slime_paste_file)
  call s:TmuxCommand(a:config, "paste-buffer -d -t " . shellescape(a:config["target_pane"]))
endfunction

function! s:TmuxPaneNames(A,L,P)
  echom "TmuxPaneNames - function ran"
  let format = '#{pane_id} #{session_name}:#{window_index}.#{pane_index} #{window_name}#{?window_active, (active),}'
  return s:TmuxCommand(b:slime_config, "list-panes -a -F " . shellescape(format))
endfunction

function! s:TmuxConfig() abort
  echom "TmuxConfig - function ran"
  if !exists("b:slime_config")
    echom "TmuxConfig - if clause: slime_config does not exist"
    let b:slime_config = {"socket_name": "default", "target_pane": ":"}
  end
  let b:slime_config["socket_name"] = input("tmux socket name or absolute path: ", b:slime_config["socket_name"])
  let b:slime_config["target_pane"] = input("tmux target pane: ", b:slime_config["target_pane"], "custom,<SNR>" . s:SID() . "_TmuxPaneNames")
  if b:slime_config["target_pane"] =~ '\s\+'
    echom "TmuxConfig - if clause: target pane"
    let b:slime_config["target_pane"] = split(b:slime_config["target_pane"])[0]
  endif
endfunction

[...]

function! s:SlimeGetConfig()
  echom "SlimeGetConfig - function ran"
  " b:slime_config already configured...
  if exists("b:slime_config")
    echom "SlimeGetConfig - if cluase: slime_config exists"
    return
  end
  " assume defaults, if they exist
  if exists("g:slime_default_config")
    echom "SlimeGetConfig - if cluase: slime_default_config exists"
    let b:slime_config = g:slime_default_config
  end
  " skip confirmation, if configured
  if exists("g:slime_dont_ask_default") && g:slime_dont_ask_default
    echom "SlimeGetConfig - if cluase: slime_dont_ask_default exists and is true"
    return
  end
  " prompt user
  call s:SlimeDispatch('Config')
endfunction
```

When I run `SlimeConfig` using this code, the following messages appear:

```
TmuxConfig - function ran
TmuxConfig - if clause: slime_config does not exist
```

So it seems that the `SlimeGetConfig` function doesn't get called, which I assume it needs to be if the `g:slime_dont_ask_default` and `g:slime_default_config` values should be picked up. I tried to add it to the `TmuxConfig` function with `call s:SlimeGetConfig()`, but it didn't work:

```
Error detected while processing function slime#config[2]..<SNR>137_SlimeDispatch[6]..<SNR>137_TmuxConfig:
E486: Pattern not found: SlimeGetConfig()
```

Would have been nice to be able to solve it myself and submit a PR for once, but apparently it's not to be :-P

**Comment by fasterius** [comment]
The way I understand the code (and I'm clearly not super-experienced with vim-script) is that the `TmuxConfig` function checks if `slime_config` exists, and if it doesn't sets it to a default value (which is what I'm seeing). It then prompts the user for socket and target pane, regardless of whether `g:slime_dont_ask_default` is set or not. The way I understand `SlimeGetConfig` is that if the `g:slime_dont_ask_default` exists and is true it should just end and not call `SlimeDispatch('Config')`, which I'm not sure what it does.

It seems to me there's some missing logic in `TmuxConfig` that should check for `g:slime_default_config` and `g:slime_dont_ask_default`, but I'm not exactly sure where and how it is missing. I might be misunderstanding, though :-P

**Comment by jpalardy** [comment]
Hi @fasterius 

It's been a while since I followed this code. Now, re-reading what you wrote, I might see what's confusing.

You're only supposed to call `SlimeConfig` to force re-entry of the config. If you're going through one of the `send` command (e.g. calling <kbd>ctrl</kbd><kbd>c</kbd>, <kbd>ctrl</kbd><kbd>c</kbd>), the global flags would be picked up.

--

In the "normal flow", you send text and end up in `SlimeGetConfig`:

![Screen Shot 2021-12-01 at 13 25 40](https://user-images.githubusercontent.com/18142/144317168-2c2c0be1-5568-42b6-ac4a-fa2d86fe54a9.png)

**Comment by fasterius** [comment]
Oh, I see! I was not aware of this. Testing this it works just fine, so it was just a user error doing it in the wrong way, I guess :-P

When I am using the vim terminal I use a custom function to open a vim terminal, execute an appropriate language shell for it based on filetype (e.g. R for `.Rmd` or Python for `.py`), move back to vim from the vim terminal, followed by a call to `SlimeConfig` to set the terminal to send commands to. I thought I could do it  in this way for Tmux as well, but apparently it doesn't work that way. Would be nice, but maybe I can adapt the functions to get me a similar functionality somehow...

**Comment by jpalardy** [comment]
since vim terminal doesn't have a `{last}` (like tmux), you might be able to emulate it by setting the `b:` target.

let me know how that goes 👍
