### ISSUE TITLE
`g:slime_dont_ask_default` has no effect

### ISSUE THREAD

**Issue by fasterius** [jpalardy/vim-slime#306]
Thanks for an excellent plugin, been using it for quite some time! I recently wanted to try it out with Tmux rather than the vim terminal, but I ran into some problems. Setting `g:slime_dont_ask_default` to `1` does not seem to have any effect whatsoever, and I need to press enter twice, even if the pre-populated config values are correct. I tried putting it both before and after other vim-slime settings, but nothing worked. What am I doing wrong?

**Comment by jpalardy** [comment]
hi @fasterius 

This sounds similar to #305 , let's track both problem over there.
