### ISSUE TITLE
workaround till kitty select window is in main

### ISSUE THREAD

**Issue by ArbitRandomUser** [jpalardy/vim-slime#309]
what i do ..
open two kitty's side by side
check output of $KITTY_LISTEN_ON in one of them
open nvim in other one (i have it aliased to vim if that matters) 

ctrl-c ctrl-c in nvim 
it prompts me for kitty listen on (but not window id)
i enter the $KITTY_LISTEN_ON that i saw in the other window
but i dont see any output slimed over .

neovim version 
```
NVIM v0.7.0-dev+662-g73b35ef10
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

vim-slime version 
```
commit 7c49bd710e11268cac56cecfe6ff0426d0026808 (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: you-n-g <you-n-g@users.noreply.github.com>
Date:   Mon Dec 20 00:16:24 2021 +0800

    unset `slime_config` for automatically configuration next time (#308)
lines 1-5/5 (END)
```

kitty version 
```
kitty 0.23.1 created by Kovid Goyal
```

**Comment by ArbitRandomUser** [comment]
upong furthur inspection this seems to be cause by this line(52) in 
autoload/slime.vim
  ```call system("kitty @" . to_flag . " send-text --match id:" . shellescape(a:config["window_id"]) . " --stdin", a:text)```
  
changing this to 
```
call system("kitty @" . to_flag . " send-text  --stdin", a:text)     
```
seems to make it work as expected

**Comment by ArbitRandomUser** [comment]
okay the real issue is kitty @ select-window is not yet implemented in 0.23.1
maybe dont implement select window till its out on a release branch/tag yet ?

**Comment by ArbitRandomUser** [comment]
iv'e made a pull request , https://github.com/jpalardy/vim-slime/pull/310

**Comment by jpalardy** [comment]
Merged ✅
