### ISSUE TITLE
clear modifiers for x11

### ISSUE THREAD

**Issue by ArbitRandomUser** [jpalardy/vim-slime#312]
while using ctrl-c ctrl-c to slime the text over , the ctrl modifier is held down which for some reason alacritty seems to ignore, but kitty does not 

i tried to add the --clearmodifiers switch to xdotool in X11Send however it does not seem to work
i'll put in a PR if i do get it to work;

meanwhile can someone try getting this to work ?

**Comment by jarbus** [comment]
does this mean kitty isn't working for you with vim-slime?

**Comment by jpalardy** [comment]
hi @ArbitRandomUser 

would another binding work?

**Comment by ArbitRandomUser** [comment]
yup ; thats the workaround im using for now with a Leader
