### ISSUE TITLE
:SlimeSend1 <C-d> sends (un)expected extra carriage return

### ISSUE THREAD

**Issue by knpwrs** [jpalardy/vim-slime#318]
I have `<Leader>SD` mapped to `<Cmd>SlimeSend1 <C-d><Cr>`. This properly exits the running REPL, but then sends an additional `<Cr>` resulting in the following shell:

![image](https://user-images.githubusercontent.com/174864/149212269-886adb48-dfbb-47bb-a3c6-917011af38e9.png)

Given the following help text:

```
:SlimeSend1 {text}      Send a single line of text, specified on the command
                        line, to screen, tmux, or whimrepl. A carriage return
                        is automatically appended.
```

The behavior actually makes sense, it's just kinda funky to end up with an empty shell prompt after the REPL is closed.

**Comment by jpalardy** [comment]
Hi @knpwrs 

I think this is a side-effect of the mapping itself. Can you paste your exact mapping from your config file?

**Comment by knpwrs** [comment]
It's a side effect of the way vim-slime works. What's happening is `<C-d>` is closing the repl, leaving the shell, and then vim-slime sends `<Cr>` which submits nothing to `zsh`.

I think it might be nice to have an option to skip `<Cr>`, or automatically detect special cases like `<C-d>` and not send `<Cr>` in those cases.

I use https://github.com/folke/which-key.nvim to define my mappings. This particular mapping is defined here: https://github.com/knpwrs/dotfiles/blob/9cfa51f11418052b9a0050e789a03f14f53eb74b/home/config/nvim/lua/plugins/vim-slime.lua#L16

**Comment by jpalardy** [comment]
Hi @knpwrs 

Vim doesn't know if you're in a REPL or not. (there are cases where I use it on the shell, which is a REPL itself)

I think `SlimeSend0` is what you want, here's a [snippet from my dotfiles](https://github.com/jpalardy/dotfiles/blob/main/vim/plugins.vim#L25-L26):

```vim
nmap <c-c><c-u> :SlimeSend0 "\x15"<CR>     " send ctrl-u
nmap <c-c>q     :SlimeSend0 "q"<CR>        " send q
```

**Comment by knpwrs** [comment]
`:SlimeSend0 "\x04"<CR>` does the trick! (Though `:SlimeSend0 <C-d><Cr>` does not).

It looks like there aren't any help docs for `:SlimeSend0`, are there any particular nuances to be aware of? I can submit a PR to add documentation.
