### ISSUE TITLE
Feature request: Cell text object

### ISSUE THREAD

**Issue by fecet** [jpalardy/vim-slime#320]
Now that we can assign a cell delimiter
```
let g:slime_cell_delimiter = "#%%"
nmap <leader>s <Plug>SlimeSendCell
```
It would be great to make cell as a text object, so one can "ac"  for current cell + header, and "ic"  for cell without the header.

**Comment by Klafyvel** [comment]
TIL : text objects are a thing. :sweat_smile: 

I played a bit with that and decided to integrate it in vim-slime-cells. Feel free to try it @fecet !

**Comment by fecet** [comment]
I just test the feature in vim-slime-cells, it works perfectly, many thanks to @Klafyvel and @jpalardy !
