### ISSUE TITLE
Vim adds extra indentation for python

### ISSUE THREAD

**Issue by yegorchi** [jpalardy/vim-slime#321]
Hello! 
Please help to investigate. 

Suppose I edit the code in vim: 
```
def foo():
    print('Hi')
    print('Hi')
```
Then if I insert # into beggining of the line 2 which means 0i# the result is: 
```
def foo():
    #    print('Hi')
    print('Hi')
```

But if repeat for the line 3:
```
def foo():
    print('Hi')
#    print('Hi')
```

I always expect behaviour like for the line 3. 
If the plugin is plugged off then works as expected.

**Comment by jpalardy** [comment]
Hi @yegorchi 

You say this is happening in vim? (not when you send over vim-slime)

And if you toggle on/off only vim-slime, it behaves differently?

**Comment by yegorchi** [comment]
Hi, @jpalardy !

Yes, that's right, this is happening in vim and only if I toggle vim-slime. Even with empty vimrc, just vim-slime. 

I see that GetPythonIndent is responsible for the autoindentation but can't guess why vim-slime affects GetPythonIndent.

**Comment by jpalardy** [comment]
I don't have any ideas about this. (I don't use python much)

Let's leave this open and see if someone weighs in.

**Comment by yegorchi** [comment]
So I removed "vim-plug" manager, after that manulally installed vim-slime. 
Now everything is fine and indentation works as expected.
@jpalardy thank you for help and for the plugin, it makes me happy.
