### ISSUE TITLE
Error when using juper-console

### ISSUE THREAD

**Issue by MushiTheMoshi** [jpalardy/vim-slime#322]
Hi there,

I want to firstly thank for all the work done here , this is one of my favourite tools.

I have been trying using the this tool with jupyter-console without success, I get the below error, is weird cause I have used with lot of languages and repl consoles and every time worked like a charm.

![image](https://user-images.githubusercontent.com/13651419/153708437-88eef23c-3927-40a6-bde4-82d3649bce88.png)

![image](https://user-images.githubusercontent.com/13651419/153708445-0961a998-e2e8-4b23-b9eb-2186b400f4fd.png)

this is my current config vim vimrc:
![image](https://user-images.githubusercontent.com/13651419/153708461-3f947e98-c267-4207-a1f1-1f9a64c548c9.png)

Hope you can help me.

Regards,
Julio

**Comment by jpalardy** [comment]
Hi @MushiTheMoshi 

Ah… Python… 😩   (an endless source of vim-slime gotchas)

From your config, I assume you've tried `let g:slime_python_ipython = 1`?

Beyond that, I would recommend sprinkling the plugin's code with [echom](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html), so you can trace the code as it runs.

If you could also post a screenshot of:
- a simpler example
- with clear input and output window

I can try to reproduce it.

I'm here if you find anything, or need more help 👍

**Comment by MushiTheMoshi** [comment]
Hi , thank you so much for your prompt response. I think is not slime issue, is in the terminal side since the error comes even if I am not running slime. Will close this ticket and again thank you so much for your kind help!
