### ISSUE TITLE
iPython 8.2 results in "ERROR! Session/line number" message on macOS, kitty

### ISSUE THREAD

**Issue by xxyxxyxyx1** [jpalardy/vim-slime#323]
Upgrading iPython from 8.1.1 to 8.2.0 results in error messages being printed in the ipython terminal, e.g. sending
```
# comment
print('test')
```
results in:
```
In [1]: %cpaste -q
# comment
print('test')
--
ERROR! Session/line number was not unique in database. History logging moved to new session 113
test

In [3]:
```

The prior behavior was:
```
In [1]: %cpaste -q
# comment
print('test')
--
test

In [2]: quit
```

I notice that an ipython prompt index is skipped along with the error message in 8.2.0. 

Reverting to 8.1.1 fixes the problem. I manage the ipython package using `conda install ipython=8.x.x`. 

I am using neovim 0.6.1 and kitty 0.24.4:
```
" kitty slime
let g:slime_python_ipython = 1
let g:slime_target = "kitty"
let g:slime_default_config = {"listen_on": $KITTY_LISTEN_ON}
```

**Comment by jpalardy** [comment]
Hi @xxyxxyxyx1 

Thanks for reporting this ^

I don't have any special insights for this. Let's keep this up for visibility.

Let me know if you discover anything.

**Comment by Uni-qi** [comment]
I get exactly the same error with ipython  8.2.0 for both tmux and neovim as configurations for the slime_target. (OS: Linux). If I downgrade ipython, everything works fine again.

**Comment by CosmosAtlas** [comment]
Can confirm, happen to me on Linux too. With

```
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by xxyxxyxyx1** [comment]
This appears to be a bug in ipython, reported there after I opened this issue:
https://github.com/ipython/ipython/issues/13622

A core develper of ipython, Carreau, is aware of the issue, but it has not yet been fixed in 8.5.0. I hope it can be fixed because 8.5.0 includes some very nice improvements:
https://ipython.readthedocs.io/en/stable/whatsnew/version8.html

**Comment by jpalardy** [comment]
thanks for the update, @xxyxxyxyx1

**Comment by CosmosAtlas** [comment]
I've just submitted a pull request attempting to fix this issue. Let's wait and see how they think.

**Comment by CosmosAtlas** [comment]
The pull request has been merged. So in the next release of ipython, the issue should be resolved.

**Comment by xxyxxyxyx1** [comment]
ipython 8.6 has been released and this is now working for me. I will close this issue. 
Thank you cosmoatlas for fixing the ipython.
