### ISSUE TITLE
[Issue] Send code have problem with normal-terminal mode vim

### ISSUE THREAD

**Issue by hungpham3112** [jpalardy/vim-slime#326]
I map <Esc> to use normal mode inside terminal vim. When I send a group of code into this terminal, it has some problems

1. Code look weird when send from vim buffer to terminal

https://user-images.githubusercontent.com/75968004/162155262-ba90591b-258e-408e-a104-7146e3d2bc7b.mp4

2. In Windows Terminal, the julia header is wrapped. 

![image](https://user-images.githubusercontent.com/75968004/162158070-cf79ef4c-8db6-4c1a-b2ad-e71dabf2588e.png)

3. In normal-terminal mode, the sending code isn't updated when send from buffer to terminal.

https://user-images.githubusercontent.com/75968004/162159999-5a21bbe4-227f-4b88-bb93-897d9abadf76.mp4

**Comment by jpalardy** [comment]
hi @hungpham3112 

have you tried tmux? does this only happen with vim terminal?

**Comment by hungpham3112** [comment]
> hi @hungpham3112
> 
> have you tried tmux? does this only happen with vim terminal?

Thanks you for quick reply. I have never tried tmux, This happen to me with vim-terminal inside Windows Terminal, in Gvim the Julia header doesn't wrap but others issue still there. I just use this plugin for the first time and like it.

**Comment by hungpham3112** [comment]
> We can iterate: if you try different combinations are find something, let me know.

I can confirm to you that just Windows Terminal has the second issue. I tested cmd.exe, window powershell, window terminal, alacritty and still exist the first and third issue above.

**Comment by jpalardy** [comment]
Is that just with julia? Do other REPL behave the same?

**Comment by hungpham3112** [comment]
> Is that just with julia? Do other REPL behave the same?

I opened the issue https://github.com/JuliaLang/julia/issues/44927, it seems like problem with Julia REPL.

**Comment by jpalardy** [comment]
ok, keep me posted

**Comment by hungpham3112** [comment]
Today, I look back to this problem. The first issue is caused by the Julia REPL behavior in Windows, the third is caused by the expected behavior of terminal mode in vim, not related to this plugin. The second issue I assume it is a bug with Window Terminal.
