### ISSUE TITLE
Using IPython 8.2.0 -- ERROR! Session/line number was not unique in database. History logging moved to new session

### ISSUE THREAD

**Issue by jimcost** [jpalardy/vim-slime#327]
I've used Vim-slime without issue for a while now (thank you for this!). With a recent OS, conda, vim, tmux, etc. (new computer setup) installation, I receive the message `ERROR! Session/line number was not unique in database. History logging moved to new session` each time I execute `Ctrl-C-C` to paste code from Vim into IPython. For instance,

```
In [1]: %cpaste -q
import sys
import h5py
import glob
import argparse
--
ERROR! Session/line number was not unique in database. History logging moved to new session 11
```
Any ideas? I google searched the error and did not come up with anything of use -- either stale threads or one unrelated solution (the conversation was about using `fork()` and multiprocessing in python)

Software versions:

OS: Debian 10.0
Python: 3.10.4
IPython: 8.2.0
Vim: 8.2
Tmux: Unknown (latest)

**Comment by eosram** [comment]
I came here because I also receive this error message. Switching back to IPython 8.1.1. I don't get the error message anymore.

**Comment by jimcost** [comment]
Excellent, I appreciate the input.

**Comment by jimcost** [comment]
@eosram  solutions solved my problem. For future reference (to lessen web search load), if using conda:

```
conda remove ipython
conda install ipython=8.1.1
```
