### ISSUE TITLE
X11 Garbled Text

### ISSUE THREAD

**Issue by mwlow** [jpalardy/vim-slime#330]
Hi,

vim-slim seems to be sending garbled text when using the X11 option. Some of the other ones, like vimterminal, work fine.

`3 + 5` currently gets turned into `=[10;5u`

I've checked .slime_paste and the correct thing is there. Anyone have any ideas?

**Comment by mwlow** [comment]
Resolved: looks like something is wrong with vim copy and paste in general

**Comment by rivten** [comment]
Hello ! @mwlow coming late but I think I have the same issue. I thought it could be somewhat related to keyboard mapping. Did you find out what was wrong in general and were you able to fix it ?
