### ISSUE TITLE
is there a way to make the cursor move to next line?

### ISSUE THREAD

**Issue by pinggit** [jpalardy/vim-slime#331]
after sending some lines, the expected behavior is the cursor moving forward so next line(s) can be send.
currently the cursor always stay at the original position.
is there a way to make the cursor moving forward to the next line?

**Comment by pinggit** [comment]
I found it by reading the help.
nmap ,ss  <Plug>SlimeLineSend

**Comment by jpalardy** [comment]
Hi @pinggit 

Have a look at [this binding](https://github.com/jpalardy/dotfiles/blob/main/vim/plugins.vim#L28) from my dotfiles.

<kbd>ctrl</kbd> <kbd>c</kbd>, <kbd>enter</kbd> -- send the current paragraph and moves the cursor past it. You can modify to accommodate your needs.

Let me know how that goes.

**Comment by jpalardy** [comment]
They are both [defined here](https://github.com/jpalardy/vim-slime/blob/main/plugin/slime.vim#L12-L13).

**Comment by storopoli** [comment]
That is truly helpful, thanks @jpalardy.
