### ISSUE TITLE
Unicode sending issues

### ISSUE THREAD

**Issue by huijunchen9260** [jpalardy/vim-slime#339]
Dear Palardy:

Recently I started to code in julia, and julia has a great functionality that can easily enter unicode character, so I can directly let β = 1 something like that.

However when I use vim-slime to send these unicode character in the julia REPL, it seems like it doesn't send the unicode character:

![image](https://user-images.githubusercontent.com/54217138/182210385-10511f02-e2c4-4749-87e5-3eaea58dc76b.png)

If I copy and paste the line under the cursor to the julia REPL, then it would be correctly executed.

Is there any way that I can let vim-slime to send unicode character?

Thanks!

**Comment by huijunchen9260** [comment]
It turns out that it is the issue of xdotool, since I am using X11. When I changed to use vim terminal this issue goes away.

**Comment by jpalardy** [comment]
hi @huijunchen9260 

glad you have something working now 👍
