### ISSUE TITLE
SlimeSend0 with append a return or newline

### ISSUE THREAD

**Issue by huijunchen9260** [jpalardy/vim-slime#340]
Dear Jonathan:

Recently I am using SlimeSend0 with the julia terminal so that I can send customized debugger command to the terminal. Somehow I notice that the text sent by SlimeSend0 does not automatically being executed, and I have go to the terminal and press an enter. Is there anyway to do it?

I know there's SlimeSend1 which indeed append newline, while somehow SlimeSend1 doesn't execute my line and file information. Currently I am using the following keymapping:

```vimL
autocmd FileType julia nnoremap <c-s>e :SlimeSend0 '@enter ' . substitute(getline('.'), ".* = ", "", "")<CR>
```
So I need vim to evaluate the substitute command before send the result to the julia terminal.

HJ

**Comment by huijunchen9260** [comment]
What the heck I just figured how LMAO

Just append the newline character `\n` and somehow it will do the job:

```vimL
autocmd FileType julia nnoremap <c-s>e :SlimeSend0 "@enter " . substitute(getline('.'), ".* = ", "", "") . "\n"<CR>
```

**Comment by jpalardy** [comment]
Hi @huijunchen9260 

Good you found a workaround 👍
