### ISSUE TITLE
add motion-like keybinding

### ISSUE THREAD

**Issue by jam1015** [jpalardy/vim-slime#344]
I love that slime sends to a repl in the terminal of your choice, especially tmux

There is a similar plugin called zepl that only works with the built in neovim terminal, but I think has a better activation command than `<C-c><C-c>`.  It uses `gz` as a command that can then be followed by a motion.  So `gzap` will send the current paragraph to the repl.  I wonder if you might add this kind of motion functionality. I can figure out how to do it myself some day bur for now it is beyond my ability.

**Comment by jpalardy** [comment]
Hi @jam1015 

I don't use that myself, but I had a look [at the code](https://github.com/jpalardy/vim-slime/blob/main/plugin/slime.vim#L20). Then I checked [what other people do](https://github.com/search?q=SlimeMotionSend&type=code) on github.

Give that a try and let me know 👍

**Comment by jam1015** [comment]
oh nice! I hadn't read the documentation enough to see those plug mappings.  I'm temporarily ashamed of myself.
