### ISSUE TITLE
IPython with %cpaste -q returns ERROR! Session/line number was not unique in database.

### ISSUE THREAD

**Issue by dbatten5** [jpalardy/vim-slime#349]
I have the following settings for `vim-slime`:
```
let g:slime_target = "neovim"
let g:slime_bracketed_paste = 1
let g:slime_python_ipython = 1
```
When I send a chunk to IPython running in a neovim `:terminal`, the code gets run successfully but I see the following error output in IPython, wasn't sure if this was to do with `vim-slime` or with IPython

```
In [7]: %cpaste -q
def foo():
    print("bar")
--

ERROR! Session/line number was not unique in database. History logging moved to new session 33
```
Any ideas?

**Comment by jpalardy** [comment]
Hi @dbatten5 

I don't use IPython myself, do you get similar results with:
- using vim, instead of neovim?
- using tmux (or not terminal)?
- with `let g:slime_bracketed_paste = 0`?

let me know — maybe we'll be able to pin down the problematic combination

**Comment by dbatten5** [comment]
Seems like it's an issue with IPython actally, see [here](https://github.com/ipython/ipython/issues/13622). Will close this issue
