### ISSUE TITLE
commit 7d0cb34ccaa42fb683969ea10a7171845a820e9a

### ISSUE THREAD

**Issue by drgn9** [jpalardy/vim-slime#357]
I believe you have a bug in your most recent commit.  The function "slice" cannot be found. My environment is neovim + tmux. If I fall back one commit the code runs as expected.

**Comment by danilo-augusto** [comment]
Same here. Also, when I call `:h slice()` in vim it shows the documentation for it, but in neovim it leads me to the documentation of `vim.list_slice()`.
I've been using this plugin extensively for years, so I would like to kindly ask @jpalardy to test it for neovim compatibility before merging/committing to the master branch. 🙏
Excellent plugin by the way. Thanks for the great work!

**Comment by jpalardy** [comment]
damn … sorry about that.

let me work on it right now 😅

**Comment by jpalardy** [comment]
fixed on 5308556987857eb0fc5f1a774496b29d8dd70f34 ?

**Comment by danilo-augusto** [comment]
Yes! :)
It is working for me at least.
Thanks!

**Comment by danilo-augusto** [comment]
> damn … sorry about that.
> 
> let me work on it right now 😅

Hahah no problem

**Comment by jpalardy** [comment]
I'm not usually on neovim, so I appreciate the sanity check.

I created some local tests for next time.
