### ISSUE TITLE
Does vim-slime need to be properly shutdown?

### ISSUE THREAD

**Issue by ea42gh** [jpalardy/vim-slime#359]
Using `neovim` to connect to `screen` using vim-slime

it works great when first set up.
When I exit `neovim` and/or `screen` and/or both,
and then try to set up this connection again,
the connection fails: `screen` no longer receives the text sent from `neovim`

The only remedy I know of so far is to reboot my system?!
What would I need to fix?

**Comment by jpalardy** [comment]
Hi @ea42gh 

Let's try a few things:
- does this only happen in screen? (how about tmux?)
- is screen still running between session? can commands be sent manually (without vim-slime)? — (check the code in the plugin and try to run the `system` commands manually)

let's start with this and see where it goes

**Comment by ea42gh** [comment]
I found that screen was not properly shut down:
the las time I tried, I found two sessions.
I shut them down, and restarted a single one.
It worked!

You might consider adding a sentence in the documentation to that effect!

BTW, I really like what I can do with your software, in particular
when combined with the python pywiz panel and holoviews libraries!
Thank you!

**Comment by jpalardy** [comment]
I'm happy that worked out for you 🎉
