### ISSUE TITLE
About the verbose version of `SlimeSend` that always prompt the users for the output pane.

### ISSUE THREAD

**Issue by nyngwang** [jpalardy/vim-slime#370]
Moved from comments started [here](https://github.com/jpalardy/vim-slime/issues/268#issuecomment-1459752734) of #268:

> @jpalardy Neovim user here. It seems that setting `vim.g.slime_dont_ask_default` to either `0`, `false`, `nil` all still fallback to use the default config. Could you help me check this? What I want to achieve is that it always shows me the prompt even if I'm calling `'<,'>:SlimeSend` on the same buffer.

,

> @nyngwang
> 
> you want to be prompted every time you press ctrl-c, ctrl-c?

,

> @jpalardy Yes! This might sound silly to you at first, but I want to be able to send different lines of the same buffer to different tmux-panes so that I can categorize the output. It's OK for me to check it every time as you already did a good job pre-filling the prompt so I just need to press enter twice.
>
> To be more specific about my requirements, as a reference I also provide my current config below:
>
> - I have provided `slime_default_config`, I'm happy that these fields are always pre-filled when the prompt appears.
> - I have set `slime_dont_ask_default = false`, it will be great to provide something like `slime_verbose_mode = true` to prompt for the config (with pre-fills for sure!) everytime one call `:SlimeSend`.
>
> ```lua
> use {
>   'jpalardy/vim-slime',
>   init = function ()
>     -- NOTE: put in init to make sure all globals are applied every time `nvim` is called.
>     vim.g.slime_target = 'tmux'
>     vim.g.slime_no_mappings = true
>     vim.g.slime_dont_ask_default = false
>     vim.g.slime_preserve_curpos = false
>     vim.g.slime_default_config = {
>       socket_name = vim.split(vim.fn.getenv('TMUX'), ',')[1],
>       target_pane = ':',
>     }
>   end,
>   config = function ()
>   end
> }
> ```

**Comment by jpalardy** [comment]
Hi @nyngwang 

A few ideas:

The simplest way, for now, would be to delete `b:slime_config` before calling whatever vim-slime function or binding. For example:

```vim
nmap <c-c><c-c> :if exists("b:slime_config") \| unlet b:slime_config \| endif<cr><Plug>SlimeParagraphSend
```

Another way is to take over configuration -- like [this](https://github.com/jpalardy/vim-slime#how-to-override-configuration)

Let me know how that goes for you.
