### ISSUE TITLE
Issue using with wezterm+ipython

### ISSUE THREAD

**Issue by MadFisa** [jpalardy/vim-slime#373]
Hi,

I have been using vim-slime with tmux+ipython for some time and is quite happy with it. Thank you for this fantastic plugin.

However, recently I have been trying out wezterm and was very happy to see that vim-slime supports wezterm. I tried it out, but is facing some issues.  When I use SlimeSend it copies the line to ipython terminal, but does not execute, instead adding a new line at the end. This is basically same as #208 , except for wezterm.  I haven't tried the fix yet since I am not comfortable with vim script. 
Similarly, if I select multiple lines and try SlimeSend it copies the line, but does not execute and I get a '--' at the end. This is also similar to this issue #299 I found.

I tried using the exact same configuration with tmux and it worked as expected without any problems. My guess is that there is some problem with the handling of newline character '\n'. I don't know how to further troubleshoot this. Any suggestions would be very appreciated.

I am using neovim if that would make any difference.

**Comment by jpalardy** [comment]
@albheim @Strosel thoughts?

**Comment by MadFisa** [comment]
@jpalardy sorry if this is a basic question, I do not know vimscript.
What are these lines supposed to do?

https://github.com/jpalardy/vim-slime/blob/e5ae6a6d479c97d5352969574130956798e480b7/autoload/slime.vim#L165-L169

**Comment by MadFisa** [comment]
@albheim  Thanks for looking into it and the explanation. Currently, with my limited understanding, I think there are two possibilities since this exact same configuration works with tmux:

1.  The issue is due to vim-slime having something in tmux codes that take care of the new line character that is not being done in the wezterm parts.
2. The newline character is handled differently by the wezterm compared to tmux

Can you point me towards where the relevant code for wezterm is?

**Comment by albheim** [comment]
Here is wezterm, and right below is tmux. It might very well be possible to take some of the newline specific things from tmux to get wezterm to work, but I don't really know why and how this is handled differently so I can't really give any good tips.

https://github.com/jpalardy/vim-slime/blob/e5ae6a6d479c97d5352969574130956798e480b7/autoload/slime.vim#L105-L117

**Comment by MadFisa** [comment]
@albheim  I think I have some clue to what is happening. Assuming what this part of the code does is basically pipe the selected text through `wezterm cli send-text --pane-id=`, I did some experiments with the command.

`echo 'some-text-here' |wezterm cli send-text --pane-id=2 ` will automatically insert a new line after the text.

But adding the option --no-paste seem, which disables bracketed paste (I don't know what that means https://wezfurlong.org/wezterm/cli/cli/send-text.html ) seems to fix the issue. Maybe someone more knowledgeable can look into it and confirm.

All the tests were done outside vim-slime, maybe you could try adding the changes to vim-slime see if it helps.

**Comment by MadFisa** [comment]
So I went ahead and made the changes and seems to fix the issue.
Basically changed 
` call system("echo " . shellescape(a:text) . " | wezterm cli send-text --pane-id=" . shellescape(a:config["pane_id"])) `

to 

` call system("echo " . shellescape(a:text) . " | wezterm cli send-text --no-paste --pane-id=" . shellescape(a:config["pane_id"])) `

You can confirm if it worked on your end too.

**Comment by MadFisa** [comment]
On further testing, it works mostly fine. There is some issue when used with `let g:ipython_cell_send_ctrl_c = 1` because it tries to execute 'i'  as a command. 
Just using 
```
let g:ipython_cell_send_ctrl_c = 0
let g:ipython_cell_send_ctrl_u = 1
```
in the config helps with that problem.

**Comment by albheim** [comment]
That seems to make it work for ipython/bash/fish, though now it seems to insert an extra enter after running the command for all the different repls/shells I tried it with.

Maybe it is still better overall, but it would be a regression for those that worked fine before.

**Comment by MadFisa** [comment]
@albheim the extra enter used to appear even before the 'fix'. 
Maybe a better way to implement would be to make the already existing 'g:slime_bracketed_paste' option toggle the `--no-paste` flag since that is basically what it does i.e turn off bracketed-paste according to documentation.

**Comment by MadFisa** [comment]
@albheim Great, hopefully, you can add it to the code.

Just out of curiosity, why use echo and pipe?
Why not just use `system("wezterm cli send-text --pane-id=" . shellescape(a:config["pane_id"] . shellescape(a:text)  ))`?

**Comment by albheim** [comment]
You don't want to create a PR? 

I don't know why it is written as it is, seems like it could work equally well without echo but I haven't tested.

**Comment by MadFisa** [comment]
@albheim I don't know how to create a proper PR, but I could if you guide me through it. Do I need to fork the repo and then clone it to local machine before I make the modifications? After that I push to my fork then create a PR?

Also regarding the echo piping, I tested it with and without echo. Having echo seems to add an endline character at the end which could  be the culprit for that extra enter that appears. I tried with the variation of command I mentioned above, which does not insert anything. But, it seems to introduce another issue that it is unable to send '--' for some reason. This might be especially problematic if the user has `g:slime_python_ipython = 1` which sends '--' at the end when sending a region of text.

**Comment by albheim** [comment]
> Do I need to fork the repo and then clone it to local machine before I make the modifications? After that I push to my fork then create a PR?

Yes, sounds right.

Regarding the echo, leave it as it is if it seems messy to switch. 

You can ping when you have a PR ready and I'll try to check it out.

**Comment by albheim** [comment]
Haha, don't trust me too much. I did my first vim-script a few months ago with the zellij part of vim-slime which also was mostly copy-pasting and some trial-and-error.

But I will have a look, and will try it out on my computer.

**Comment by sho-87** [comment]
I'm having the same problem with ipython but using neovim terminal as the target instead of wezterm.

A normal python repl seems to be fine - so is this an ipython problem more generally, regardless of the target? from looking at all the related threads, it seems like ipython is the common problem across wezterm/neovim/tmux targets?

**Comment by MadFisa** [comment]
@sho-87 
Does the problem exists single when sending single lines to ipython also? or only when sending multiple line?

**Comment by sho-87** [comment]
both single and multi lines are an issue with ipython

ive resorted to having to do something like this, which has its own issues:

```
map("n", "<leader>rl", function()
	vim.cmd("SlimeSendCurrentLine")
	vim.api.nvim_command('SlimeSend0 "\n"')
end, { desc = "Send line" })
```

**Comment by jpalardy** [comment]
please have a look at #375 and let me know where we stand 👍
