### ISSUE TITLE
Send code to qtconsole?

### ISSUE THREAD

**Issue by ANP-Oxy** [jpalardy/vim-slime#377]
Hello i’m new NeoVim user and I was wondering is there a way to send the code using vim-slime to jupyter Qtconsole just like how it sends it to ipython console. The ipython console by itself can’t render plots inline but qtconsole can. I really like vim-slime and was wondering if this is possible

**Comment by jpalardy** [comment]
Hi @ANP-Oxy 👋 

The short answer is: I don't know 😆 

All vim-slime does it "execute a shell command with text you selected" — the _magic_ comes from screen, tmux, wezterm, etc … having commands to inject/paste text into themselves from the outside, something that can be scripted.

If you're willing to research that for Qtconsole, you'll already be 70% of the way toward a solution.

Let me know what you find

**Comment by ANP-Oxy** [comment]
I tried using other plugins that allow you to connect to ipython kernels but they aren't working due to being outdated. Vim-ipython, vim-ipy, jupyter-vim none of the them are working for me. I tried looking into what I could find about jupyter Qtconsole in the documentation. 
[here are the docs](https://qtconsole.readthedocs.io/en/stable/)
![this is one section from them](https://user-images.githubusercontent.com/94713251/233543890-ec4f50d6-03fa-4a54-a005-dd49a0d61d54.png)

[this is another link that could be useful](https://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Connecting%20with%20the%20Qt%20Console.html)


The other plugins might have some hint as to how to connect to an jupyter kernel the only problem is I don't understand shell scripting or other languages that they use

**Comment by jpalardy** [comment]
Hi @ANP-Oxy 

I don't have the bandwidth to personally take this on (and I'm not a jupyter Qtconsole either)

If you attempt a prototype, that's another matter.

You could also try to find someone else to team up for a solution.

**Comment by RyanGreenup** [comment]
I think this would be great!

There is a similar plugin [jupyter-vim](https://github.com/jupyter-vim/jupyter-vim) that connects to the [QtConsole](https://qtconsole.readthedocs.io/en/stable/), this could be used for insight.

One can also use [jupytext.vim](https://github.com/goerz/jupytext.vim) to edit as a pyscript seemlessly and then preview with something like `!jupyter nbconvert "%" --to markdown<CR> :vscplit "%:r".md`.

See Also:

- https://vi.stackexchange.com/questions/45059/interactive-python-script-development
-  https://github.com/luk400/vim-jukit

**Comment by lqz-hub** [comment]
To send code to the Jupyter QtConsole:

    Set the Slime target to x11.

    Run :SlimeConfig

    Use your mouse to click on the Jupyter QtConsole window to select it as the target.

For a better experience, you can also modify the source file. Add the following settings to the file path-to-plugin/vim-slime/autoload/slime/targets/x11.vim
``` 
function! slime#targets#x11#send(config, text)

  let lines = split(a:text, '\n')
  let window_id = a:config["window_id"]
  let delay = get(a:config, 'delay', 0)  

  
  for i in range(len(lines))

    if lines[i] == ''
      continue
    endif
    

    call slime#common#system("xdotool type --delay " . delay . " --window %s -- %s", [window_id, lines[i]])
    

    if i < len(lines) - 1
      call slime#common#system("xdotool key --delay " . delay . " --window %s -- ctrl+Return", [window_id])
    endif
  endfor
  

  call slime#common#system("xdotool key --delay " . delay . " --window %s -- Return", [window_id])
endfunction
```
    Those changes make it behave as expected when you send a single line or a code cell.
