### ISSUE TITLE
send to multiple panes

### ISSUE THREAD

**Issue by pinggit** [jpalardy/vim-slime#388]
is it possible to send to multiple panes?
for example send to 2 panes below ( {down-of} ) the vim pane?

**Comment by jpalardy** [comment]
Hi @pinggit 

Possible? Yes. — Convenient? Not so much.

You could create a new keyboard mapping to (probably) a function that:
- sends to vim-slime
- re-configures to a 2nd target
- sends to vim-slime
- re-configures (back) to the 1st target

That assumes you manage your own configurations (another variable, or, in the general case, a list) outside of vim-slime

If you come up with something, let me know

**Comment by pinggit** [comment]
thanks Jonathan. I'll think about it.
