### ISSUE TITLE
How to send <Ctrl-C> via tmux?

### ISSUE THREAD

**Issue by sieste** [jpalardy/vim-slime#389]
I want to be able to clear the current line or quit a running process in a tmux pane by sending the \<ctrl-c\> shortcut from vim. Is that possible? I tried `:SlimeSend1 <C-c>` but it just sends the string "\<C-c\>".

**Comment by sieste** [comment]
I figured it out with a bit of help from chatGPT. In my init.vim I added the line

```
nmap <silent> <c-c><c-x> ^Q^C<CR>
```

where `^Q` is a special character entered in vim by typing Ctrl+q Ctrl+q in insert mode, and the `^C` is entered with Ctrl+q Ctrl+c. Now the combination Ctrl-c Ctrl-x clears the current line or terminates a running process in the tmux pane. Apparently in some terminal emulators you have to use Ctrl-v instead of Ctrl-q to insert the key combinations.

**Comment by jpalardy** [comment]
If that helps, [here's how](https://github.com/jpalardy/dotfiles/blob/main/vim/plugins.vim#L25-L28) I've configured some special sequences.
