### ISSUE TITLE
<C-c><Text object>

### ISSUE THREAD

**Issue by YodaEmbedding** [jpalardy/vim-slime#395]
Feature request.

`<C-c>` followed by any arbitrary text object.

```
(Text objects)
<C-c>ip     send inner paragraph
<C-c>5j     send next 5 lines
<C-c>af     send outer function (via treesitter text object)
<C-c>ac     send outer class (via treesitter text object)

(Defaults)
<C-c><C-c>  send inner paragraph
<C-c>v      config
```

**Comment by jpalardy** [comment]
Hi @YodaEmbedding 

Technically, you can already do all these by picking the object/motion before pressing `<C-c><C-c>`

If not, check [these lines](https://github.com/jpalardy/vim-slime/blob/main/plugin/slime.vim#L16-L21) and [how people might have mapped them](https://github.com/search?q=slimemotionsend&type=code) already.

Let me know how that goes.

**Comment by jiz4oh** [comment]
there is a `<Plug>SlimeMotionSend` that you can map by yourself, there is my vimrc

```
nmap <silent> gz <Plug>SlimeMotionSend
```
