### ISSUE TITLE
neovim tmux in msys2 in windows

### ISSUE THREAD

**Issue by Yousuf28** [jpalardy/vim-slime#404]
On my windows machine I have msys2 installed. In msys2 system, I installed neovim and tmux using pacman.  I was trying to run R code.
When I hit `ctrl-c`  `ctrl-c` I get following error.  

![sl](https://github.com/jpalardy/vim-slime/assets/31291716/3e499339-b593-4000-9332-490962123f86)

Please help to solve this.

**Comment by jpalardy** [comment]
Hi @Yousuf28 

looking at the `write_paste_file` code

```vim
function! slime#common#write_paste_file(text)
  let paste_dir = fnamemodify(slime#config#resolve("paste_file"), ":p:h")
  if !isdirectory(paste_dir)
    call mkdir(paste_dir, "p")
  endif
  let output = slime#common#system("cat > %s", [slime#config#resolve("paste_file")], a:text)
  if v:shell_error
    echoerr output
  endif
endfunction
```

I can imagine that the `paste_file`, which defaults to `$HOME/.slime_paste` might not work in Windows. (especially the forward slash, now that I've looking at it…)

A few ideas:
- try overriding `paste_file` (`let g:slime_paste_file = "..."`), to a known and valid path for your machine
- if that fails, try adding [echom](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html) to the slime code to get a better idea of what's happening

Let me know how that works out, one way or another

**Comment by jpalardy** [comment]
I think
- the second one `:echo $SHELL` is an echo done by vim … with the `$SHELL` expanded in vim
- the first one, is shelling out (and failing), to run `echo` in bash

**Comment by djhaskin987** [comment]
I figured it out.
```
set shellslash
```

Should fix your issue. It fixed mine under the same setup.
