### ISSUE TITLE
kitty slime broken in kitty v0.32

### ISSUE THREAD

**Issue by xxyxxyxyx1** [jpalardy/vim-slime#412]
I have used vim-slime with kitty successfully through kitty version 0.31. However, on current release kitty v0.32, I have problems. 

After the first text is sent with vim-slime, most keyboard shortcuts break, along with most uses of the shift key. For example:
- I cannot type symbols requiring shift in vim, such as `_`; I just get `-`. I can, however, type capital letters. 
- kitty keyboard shortcuts do not work, such as `ctrl-tab` to switch tabs
- OS shortcuts do not work while kitty is focused, for example `cmd-q` does not quit kitty

Functionality is restored only after restarting kitty. The vim-slime seems to work as intended, sending text over to the other kitty window as intended. 

I am starting kitty with `kitty --config test.conf` and this minimal test.conf:
```
allow_remote_control yes
listen_on unix:/tmp/mykitty
```

I am starting neovim with `neovim -u test.vimrc` and this minimal test.vimrc:
```
call plug#begin()
Plug 'jpalardy/vim-slime'
call plug#end()

let g:slime_target = "kitty"
let g:slime_default_config = {"listen_on": $KITTY_LISTEN_ON}
```

I have tried some small manual tests with kitty, to see if I can break it without using vim-slime, but I have not been successful. I tried for example `kitty @ --to unix:/tmp/mykitty-1975 send-text --match id:2 --stdin ls`, and no keyboard problems occurred. 

My environment includes:
- current updated vim-slime
- kitty v0.26–0.31, versus kitty v0.32
- macOS 14.2.1
- en-US keyboard and languages 

I don't know if this should be an issue for vim-slime or kitty, and I am not too proficient at these things.

**Comment by xxyxxyxyx1** [comment]
Thank you for answering. Yes, everything worked correctly until kitty v0.32. I also have the v0.31 binary on my computer, and everything still works correctly when I use this instead of v0.31. 

Yes, using slime immediately renders kitty basically broken, until restart. vim-slime is up-to-date. 

Do you have any suggestions for logs or debug output to look at? Or should I open an issue with kitty?

**Comment by jpalardy** [comment]
Let's see what kitty has to say ^

Please `@` me in the comments, if necessary.

**Comment by xxyxxyxyx1** [comment]
I did not get anywhere with my kitty issue: https://github.com/kovidgoyal/kitty/issues/7074 

The developer kindly tested it (on linux) and could not reproduce it.

**Comment by xxyxxyxyx1** [comment]
The problem appears to have been fixed in the master branch of kitty on github.

**Comment by xxyxxyxyx1** [comment]
The problem appears to have been fixed in the master branch of kitty on github.
