### ISSUE TITLE
Additional 'return' required when sending indented, commented code to ipython

### ISSUE THREAD

**Issue by xxyxxyxyx1** [jpalardy/vim-slime#418]
I am using kitty+neovim+ipython. When I <Plug>SlimeParagraphSend to ipython, in most cases, the paragraph runs immediately in ipython. However, if the paragraph ends in an indented line followed by a comment, it does not work and I must manually press 'return' in the ipython interpreter. 

Here are some examples to explain the problem. They are equivalent when the indented code is a `def()`, a `for`, etc. 

```
# test that works
def test():
    print('test')
```

```
# test that doesn't work, I must press 'return' in the ipython interpreter to get the code to run
def test():
    print('test')
# this terminal comment line breaks it
```

After sending the above paragraph, the ipython interpreter looks like this until I press 'return':
```
In [1]: # test that doesn't work
   ...: def test():
   ...:     print('test')
   ...: 
   ...: #
   ...: 
```

Adding a `pass` (or any other non-comment, non-indented python line) between the indented line and the terminal comment prevents the problem:
```
# test that works 
def test():
    print('test')
pass 
# adding an extra non-indented, non-comment line prevents the problem
```

This is inconvenient for me because I use vim folds like `#{{{ ... #}}}` to organize files, so I often have a terminal `#}}}` after a function definition. 

My relevant vimrc is:
```
let g:slime_bracketed_paste = 1
let g:slime_target = "kitty"
let g:slime_default_config = {"listen_on": $KITTY_LISTEN_ON}
```

Any idea where this problem comes from?

**Comment by jpalardy** [comment]
Hi @xxyxxyxyx1 

Of all the REPLs out there, python is the one that caused the most problems. I would recommend trying different permutations until you can isolate the problem:
- `slime_bracketed_paste` versus not
- `kitty` versus not

Let me know what you find and we can iterate.

**Comment by xxyxxyxyx1** [comment]
Thank you for the suggestions. Switching from `slime_bracketed_paste` to `slime_python_ipython` seems to solve this problem. 

`slime_python_ipython` is inferior in other ways: 
- it is noticeably slower to execute with a long paragraph, as text is written to the interpreter and scrolls by line-by-line
- the pasted text doesn't have syntax coloring (not really important, as I have colors in vim where editing happens)

For speed, it would be very nice to fix the bracketed paste mode, but this is a usable solution that doesn't require changing the python file itself.

**Comment by jpalardy** [comment]
In the case of python itself, what would it take to fix bracketed mode?

**Comment by FIREBAT-66** [comment]
@jpalardy Running into this issue as well! My python interpreter basically just fills up with the code but never executes it! Any suggestinos on how to fix it? I have slime_python_ipython set via the lua API

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2c8e58a9-83a3-4ea2-9a16-6eb3bb02624a" />

**Comment by FIREBAT-66** [comment]
@jpalardy I found the issue. I was using the ``python`` interpreter instead of ``ipython``! It works perfectly with the slime_bracketed_paste variables set in there. If you have a spare moment, can you explain what is happening with the bracketed paste? Is it modifying the text that is being sent to the python interpreter?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fa8decba-d289-44b5-b5ec-8a57f4fc6c4c" />

**Comment by jpalardy** [comment]
Hi @FIREBAT-66 

I'll let wikipedia try to explain: https://en.wikipedia.org/wiki/Bracketed-paste

if that's not clear, I can take a different stab at it 😄

**Comment by FIREBAT-66** [comment]
> Hi [@FIREBAT-66](https://github.com/FIREBAT-66)
> 
> I'll let wikipedia try to explain: https://en.wikipedia.org/wiki/Bracketed-paste
> 
> if that's not clear, I can take a different stab at it 😄

Thank you! This helped clarify why bracketed paste is a feature in Slime. So did you have to impelement the bracketed paste functionality directly into the slime plugin? The ftplugin file for python files currently looks like this:

`
let g:slime_config_defaults["python_ipython"] = 0
let g:slime_config_defaults["dispatch_ipython_pause"] = 100

function! _EscapeText_python(text)
  if slime#config#resolve("python_ipython") && len(split(a:text,"\n")) > 1
    return ["%cpaste -q\n", slime#config#resolve("dispatch_ipython_pause"), a:text, "--\n"]
  else
    let empty_lines_pat = '\(^\|\n\)\zs\(\s*\n\+\)\+'
    let no_empty_lines = substitute(a:text, empty_lines_pat, "", "g")
    let dedent_pat = '\(^\|\n\)\zs'.matchstr(no_empty_lines, '^\s*')
    let dedented_lines = substitute(no_empty_lines, dedent_pat, "", "g")
    let except_pat = '\(elif\|else\|except\|finally\)\@!'
    let add_eol_pat = '\n\s[^\n]\+\n\zs\ze\('.except_pat.'\S\|$\)'
    return substitute(dedented_lines, add_eol_pat, "\n", "g")
  end
endfunction

`

Is this the "bracketed paste" implementation that is required to be able to send code lines into the ipython interpreter?

**Comment by jpalardy** [comment]
Hi @FIREBAT-66 

> Is this the "bracketed paste" implementation that is required to be able to send code lines into the ipython interpreter?

No.

The pipeline looks like `vim --> language-specific modifications --> target plugin`

Which [target](https://github.com/jpalardy/vim-slime?tab=readme-ov-file#targets) are you using? (there is support for kitty, neovim, tmux, wezterm, zellij right now)
