### ISSUE TITLE
working with ConqueTerm

### ISSUE THREAD

**Issue by pinggit** [jpalardy/vim-slime#425]
I have to work on a server with an old vim 7.4, no tmux. GNU screen is available though.
I see conqueTerm works well.
is it possible to make slime work with it and how to configure it?

**Comment by jpalardy** [comment]
Hi @pinggit 

If GNU screen is there, I would recommend that (that's how I developed and ran `vim-slime` for years)

As for config, try [this](https://github.com/jpalardy/vim-slime/blob/main/assets/doc/targets/screen.md)

Let me know how that goes.
