### ISSUE TITLE
Error raised after trigger send if there is no neovim terminal opened

### ISSUE THREAD

**Issue by jiz4oh** [jpalardy/vim-slime#427]
<img width="748" alt="image" src="https://github.com/jpalardy/vim-slime/assets/41264693/3e5de124-09da-4753-9d68-4c16e4567a0a">

reproduce steps:
1. `nvim test.coffee`
2. call `:SlimeSendCurrentLine`

only occured when exists the `_EscapeText_{&filetype}` function

**Comment by jpalardy** [comment]
cc @jam1015

**Comment by jam1015** [comment]
I'm not able to reproduce this using a minimal config:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


require("lazy").setup(
  {
    {
      "jam1015/vim-slime",
      init = function()
        require("plugin_configs.vim-slime.initi")


        vim.g.slime_target = "neovim"
        vim.g.slime_no_mappings = true
        vim.g.slime_input_pid = false
        vim.g.slime_suggest_default = true

        vim.g.slime_menu_config = false
      end,

      config = function()
        local keymap = vim.keymap.set
        keymap("n", "gz", "<Plug>SlimeMotionSend", { remap = true, silent = false })
        keymap("n", "gzz", "<Plug>SlimeLineSend", { remap = true, silent = false })
        keymap("x", "gz", "<Plug>SlimeRegionSend", { remap = true, silent = false })
      end,
    },
  }

)
```

I run `nvim --clean -u ./minimal.lua  test.coffee` and then `:SlimeSendCurrentLine` with no terminal open and just get the `Terminal not found.` warning message (I get it twice, this is a bug that will take some refactoring to fix, but that isn't relevant here).   The text is successfully sent when I open a terminal.  

Also tested on an example python file which also has an `_EscapeText_python` function and had no problems.

Maybe try adding your personal config piece by piece to the minimal config to see what causes the errors.

**Comment by jiz4oh** [comment]
Hi @jam1015, I think it's not able to reproduce because the `_EscapeText_{&filetype}` is loaded by a `ftplugin`, and the`filetype` is not set if you run `nvim --clean -u ./minimal.lua  test.coffee`, so the reproduce steps with the minimal config is 

1. `nvim --clean -u ./minimal.lua  test.coffee`
2. `:set ft=coffee`
3. `:SlimeSendCurrentLine`

**Comment by jam1015** [comment]
addressed by https://github.com/jpalardy/vim-slime/pull/428

**Comment by jpalardy** [comment]
@jiz4oh let us know if that works for you

**Comment by jiz4oh** [comment]
@jam1015 thanks for your quick response, it's ok now @jpalardy
