### ISSUE TITLE
Not working on ARM Macbook

### ISSUE THREAD

**Issue by radlyeel** [jpalardy/vim-slime#437]
I have Vim Slime running nicely on my (Intel-based) iMac, but it fails
silently on my ARM-based MacBook.  By "silently" I mean that C-c C-c
behaves differently on the two systems.  They were both installed
side-by-side on Aug. 1, 2024, both are running "Vi IMproved 9.1".

Startup sequence, both machines:

In vim, ":vert term" to get tall windows.

In the new Term window, "screen -S session01" then C-a A<ret> to name
the new window "zsh".  "guile" to get a Scheme REPL running, then C-w
C-w to switch back to my editor window. At that point, the behaviors on
the two machines differs.

On the iMac (properly working), the first C-c C-c results in a
status-line prompt similar to Vim's :buffers command, waiting for me to
choose one.  I choose the ~/bin/zsh buffer and then I'm in Slime heaven,
thankyouverymuch.

On the ARM Macbook, the C-c C-c results in a prompt for scrren seesion
name (session01")then window name (defaults to 0, but I enter "zsh". 
Thereafter , C-c C-c has no visible effect.  "C-c v" does prompt me for
session and window but I can't find an effective combination.

**Comment by jpalardy** [comment]
Hi @radlyeel 

I wonder what's different 🤔   (versions of GNU screen?)

Are you able to send text manually, from another terminal into your target `screen`?

```bash
# setup your session01 screen
# everything below happens in ANOTHER terminal

> seq 3 14 > 314.txt       # create a file with some (arbitrary) content
> screen -X eval "readreg p $PWD/314.txt"
> screen -S session01 -X paste p
```

Let me know the results

**Comment by radlyeel** [comment]
The problem is no more.  Based on https://github.com/jpalardy/vim-slime/issues/55, I added the following two lines to $HOME/.screenrc
and all is well.

msgwait 0
msgminwait 0

**Comment by jpalardy** [comment]
excellent news 🎉 

I'm here if you need anything else
