### ISSUE TITLE
tmux empty paste corner case

### ISSUE THREAD

**Issue by williamjameshandley** [jpalardy/vim-slime#443]
When sending a blank line to tmux (e.g. `slime#send('')`), it instead sends the contents of the last tmux yank register.

This is because [the buffered for loop](https://github.com/jpalardy/vim-slime/blob/f6bbbeb8f18393f2177cdcef764f3e0e1d7e9328/autoload/slime/targets/tmux.vim#L23-L31) has a `range(0,0)` (i.e `[0]`) command in this case, which executes one loop, which loads nothing into the buffer (which does nothing), and then sends the last non-empty thing that was loaded.

In my use case this has involved sending some relatively dangerous commands to a terminal!

This can be fixed by wrapping the loop in a `if len(text_to_paste) >0` statement, but wanted to check if

a) Is this a feature or a bug?
b) Is there a neater/more robust way to achieve this?

**Comment by jpalardy** [comment]
hi @williamjameshandley 

this is definitely a bug — thanks for catching this 👍 

I never ran into this myself, what did you run to get in this situation?

…

I personally cannot believe that's how `range(0 ,0)` works … let me explore this a little bit

**Comment by jpalardy** [comment]
I'm trying to reproduce this, but the `paste-buffer -d` clears the buffer and nothing happens on the next attempt 🤔

**Comment by jpalardy** [comment]
see #444
