### ISSUE TITLE
tmux sending the previous cell instead of the actual cell.

### ISSUE THREAD

**Issue by Halloway-93** [jpalardy/vim-slime#445]
Hello, 
It seems that i have a problem with vim-slime. I am using it to send python code onto ipython using tmux panes.
The only issue i have, is that it seems that pasting is sort of 'lagging' by one cell. 
Meaning that when the code  the current cell is sent, it is the code of the previous copy i.e cell  that was  previously copied. 
Does anyone have the same issue? 
thanks in advance for your answers!

**Comment by jpalardy** [comment]
Hi @Halloway-93 

Can you share:
- your slime-related config?
- how you setup your tmux?
- what binding you use?
- what python-related config?

also, you might want to simplify your vim config / plugins to a minimum to see if your problem continues

**Comment by Halloway-93** [comment]
Hello, 
This is my nvim configuration and how i set up tmux	{
		"jpalardy/vim-slime",
		ft = "python", -- Load only for Python files
		config = function()
		
			vim.g.slime_target = "tmux" -- Example: set the target to tmux
			vim.g.slime_python_ipython = 1
			vim.g.slime_default_config = {
				socket_name = 'default',
				target_pane = ':.+1',
			}
			-- vim.b.slime_bracketed_paste = 1
		end,
	},

this is my mapping to send the code to the second window:
map("n", "<leader>sa", ":IPythonCellExecuteCellJump<CR>", opts) 

I am using Ipython cell for my python related config
: {
		"hanschen/vim-ipython-cell",
		ft = "python", -- Load only for Python files
		config = function()
			vim.g.ipython_cell_highlight_type = "IPython" -- Example: set the highlight type
		end,
	},

**Comment by jpalardy** [comment]
Does the (standalone) slime binding work? (`ctrl-c, ctrl-c`)
Are you able to paste into tmux from the command-line? (no vim, no slime, just the commands from the plugin)

**Comment by Halloway-93** [comment]
Yes it works.
I am using it with zellij on my local computer, it works fine, but on the server i have to use tmux. and it is there where i have the problem. I remember that someone found a work around by modifying a  line in .local/share/nvim and modified a line in the code but I cannot find that solution anymore.

**Comment by Halloway-93** [comment]
I found it! sorry to have bothered you with this issue, it was a problem with ipython-cell not slime: here is the issue https://github.com/hanschen/vim-ipython-cell/issues/19
Thank you for help.

**Comment by jpalardy** [comment]
no problem — I'm glad you found a fix 👍
