### ISSUE TITLE
vim tmux error

### ISSUE THREAD

**Issue by sevakd** [jpalardy/vim-slime#49]
"Error detected while processing function <SNR>10_SlimeSendOp..<SNR>10_SlimeSend..<SNR>10_SlimeDispatch..
<SNR>10_TmuxSend:
line    4:
E484: Can't open file /tmp/vrhkGsT/1"

Unsure if I missed a step as far as setting things up.
When I go to that directory within /tmp/ there is a file named 0, but not 1.
Don't know if that is of any help.

**Comment by kariya2** [comment]
@sevakd  facing the same issue where I'm unable to open the tmp file. what helped you fix it?

**Comment by blackheaven** [comment]
I have the same issue, any hints?

**Comment by jpalardy** [comment]
As reported by @blackheaven in #307 

```vim
let g:slime_paste_file = tempname()
au VimLeave * call delete(g:slime_paste_file)
```

can solve this problem and cleanup
