### ISSUE TITLE
Lines after the first are not indented when "let" is added (Haskell)

### ISSUE THREAD

**Issue by dariusf** [jpalardy/vim-slime#67]
```hs
item :: Parser Char
item = Parser (\s -> case s of
    "" -> []
    c:cs -> [(c,cs)])
```
When sending the above to `tmux`, the following error occurs:

```hs
Prelude> :{
Prelude| let item :: Parser Char
Prelude|     item = Parser (\s -> case s of
Prelude|     "" -> []
Prelude|     c:cs -> [(c,cs)])
Prelude| :}

<interactive>:5:5:
    parse error (possibly incorrect indentation or mismatched brackets)
```
The problem is that only the first line is indented when `let` is added.

I took a look at the source and it seems that lines beginning with whitespace are [deliberately not indented](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/haskell/slime.vim#L40). May I ask why this is done? Should I be indenting my code in a different way?

**Comment by jpalardy** [comment]
Hi there, I didn't write the Haskell plugin, so I'll have to punt.

@romeovs @jdiez17 thoughts?

**Comment by jdiez17** [comment]
Yeah, I didn't know enough about Haskell when I added support for guards there. In reality, we should preserve the same indentation as the source.

**Comment by dariusf** [comment]
Ah, I see. I fixed it on my end by removing all the conditions, so all lines but the first are indented equally. Only thing I'm still unsure about is why lines beginning with whitespace were excluded (2e18e64758628465fe0cd055620f619aa9db8d22).

**Comment by romeovs** [comment]
I can't remember either. It's been a while since I've used haskell or this plugin. If there is no reason not to keep the indentation, let's just do it that way?

**Comment by dariusf** [comment]
Alright then, I'll send a PR. Thanks for all the help everyone :)

**Comment by jpalardy** [comment]
Merged.
