### ISSUE TITLE
Vim Slime not using slime_default_config values

### ISSUE THREAD

**Issue by ethagnawl** [jpalardy/vim-slime#69]
My .vimrc contains:

`let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}`

Yet when I attempt to evaluate a line of code, I'm still prompted for a socket and target pane. (I should note that the values listed above _are_ prepopulated in the prompt, but I was expecting to not have to manually accept each of them whenever I eval code in a new buffer.)

**Comment by jpalardy** [comment]
Hi there,

Prepopulated is the "correct" behavior. I'm sorry for the confusion. You can review [this](https://github.com/jpalardy/vim-slime/issues/62) too.

**Comment by ethagnawl** [comment]
Got it - thanks for clearing that up. 

If I come up with a better way to word what's in the README, I'll submit a PR.

Anyways, thanks for the prompt response and the great plugin!

**Comment by jpalardy** [comment]
I'd certainly welcome a README PR, thanks :-)
