### ISSUE TITLE
Pasting long Python function to iPython fails

### ISSUE THREAD

**Issue by argoneus** [jpalardy/vim-slime#71]
I'm using vim-slime to paste a function to iPython.  The function is 72 lines and indented with spaces.  iPython returns errors about invalid syntax when I paste.  However, if I find/replace 4 spaces with a tab character in the function, the function pastes properly into iPython without errors.  I've confirmed that there are no errant spaces in the original, and only the beginning indentation spaces are being replaced (none in the middle or ends of lines, in other words).  Other functions (also indented with spaces) from the same file seems to paste without any issues.  I updated to the latest vim-slime using git clone but it still has the same issue.

**Comment by argoneus** [comment]
Running iPython 2.4.1, Python 2.7.6, vim 7.4.52, latest vim-slime on Ubuntu 14.04.

**Comment by jpalardy** [comment]
Hi there,

Is this with GNU screen or tmux?

The first thing that comes to mind is a character-limit: a 72-line function is quite big (for a function). When you replace spaces with tabs, you might push it slightly under the limit.

Do you know how many characters that is? Is it around a magic number? (some power of 2, probably)

**Comment by argoneus** [comment]
This is with GNU screen.

72 lines  513 words 4226 bytes, according to wc

**Comment by argoneus** [comment]
With tabs instead of spaces, it's 3989 bytes.  So there may be a limit at 4096 (4K), possibly...

**Comment by jpalardy** [comment]
You've got a few options:

1. try tmux instead
2. limit to short functions … unfortunately
3. modify the python plugin to replace indentation spaces with tabs

I recommend solutions in that order.

**Comment by jpalardy** [comment]
Note that option 3 doesn't fix the problem, it just stretches that 4k limit.

**Comment by jpalardy** [comment]
this happened before: #65

**Comment by nilsbecker** [comment]
i filed this as a bug in ipython: https://github.com/ipython/ipython/issues/7042

**Comment by nilsbecker** [comment]
just checked again since i was running into the issue again. it works to copy the long function to the system clipboard and then paste it using `%cpaste` . so either tmux, screen or vim-slime are to blame at least in part.

**Comment by jpalardy** [comment]
vim-slime only pushes the bytes down to a file, and from that file into screen.

The fact that you hit a 4k limit, and that #65 hit a 1k limit, seems to suggest there might be some compilation flag in screen that's configurable.

Even if you don't want to switch to tmux, you might want to try to see if you hit the same problem. (is it tmux or screen?)

Alternatively, you can bypass vim-slime and send the commands directly to screen. (is it vim-slime?)

**Comment by nilsbecker** [comment]
for me it's tmux, (1k) for @argoneus it's screen (apparently 4k)

**Comment by nilsbecker** [comment]
and, strangely enough, still everything works when sending stuff to `cat > testfile -` instead of ipython. one gets a file which starts with %cpaste, then has the ungarbled content, then ends with a line with only -- in it as required by ipython....

**Comment by argoneus** [comment]
Just tested with tmux and it exhibits the same behavior -- works with tabs but not spaces.  So it doesn't appear to be an issue with screen.

**Comment by argoneus** [comment]
The ```cat > testfile``` trick works for me as well, i.e. it pastes without issues.

**Comment by argoneus** [comment]
For me, copying from the clipboard to iPython (using ```%cpaste```) still generates the error.  So it would appear to be an issue with iPython in my case.

**Comment by nilsbecker** [comment]
interesting. maybe you have a longer input. ok, i tried with a longer input and direct %cpaste: then also for me ipython barfs.

**Comment by nilsbecker** [comment]
while my last comment is true, there seems to be a range of medium length inputs for which it is possible to manually use the system clipboard and %cpaste , but for which direct sending via vim-slime does not work (with %cpaste emulation enabled). this could well be an issue of a buffer that gets read too early by ipython

i am wondering if a partial workaround would be to wait for 0.1s or so before actually sending the terminating `--` line in the %cpaste emulation? that way, the content of the buffer has a chance to get transferred fully before ipython slurps it up?

**Comment by nilsbecker** [comment]
i found a workaround similar to what i speculated above in a related project:

https://github.com/julienr/vimux-pyutils/commit/0e9aa29e852142f9e73903969e02a1fbab885f1b

they send the cpaste content in chunks and introduce a waiting period

**Comment by Alok** [comment]
Ipython 5 removed the %cpaste magic function and apparently just works with pasting long input directly. You may want to either add detection for ipython 5.x+, or require users to use it if they use ipython (it *has* been out for months now). Then, you can use something other than cpaste (I'm not sure how they made it work, but it apparently does).

**Comment by adamobeng** [comment]
I have been having the same issue, which I fixed in vim-tmux-runner by wrapping the text sent to iPython in bracketed paste escape sequences: https://github.com/christoomey/vim-tmux-runner/pull/81.

**Comment by jpalardy** [comment]
If someone wants to code, test, and send me a PR for this -- I'll merge it.

(logic: I'm not an ipython user, so I'm not in the best position to cover all relevant cases)

**Comment by pvmilk** [comment]
Has anyone try this with ipdb where %cpaste is not working?

Apparently, when I send the paragraph (either through connected text or `vip`) using C-c, C-c, ipdb only execute the first line.

**Comment by louismartin** [comment]
Any news on this?

**Comment by NedWestern** [comment]
I'd be interested to see if the latest commit fixes this issue.
