### ISSUE TITLE
Getting errors on unsaved files

### ISSUE THREAD

**Issue by skrisna** [jpalardy/vim-slime#76]
I am a long time vim user but just started using vim-slime and am loving every bit of it. Thank you. I have one annoyance and am not sure if there is a quick fix for this. The problem is this - 

I am using vim 7.4 (compiled for cygwin/Windows 7/x64). I am using it along with GNU screen to interface with a Julia REPL (I am also having this problem under tmux). 

I do not have any problems when:
1. Enter a new command at the end of a file
2. Save it
3. Type C-c C-c

I get problems when:
1. Enter a new command at the end of a file
2. Do NOT save it
3. Type C-c C-c

The error I get is:
![screenclip](https://cloud.githubusercontent.com/assets/2131842/7243393/8490c5bc-e79a-11e4-821d-3cecc1e44fa4.png)

For quick interactive use, I would really like to not have to save everytime before the C-c C-c. Is there a quick fix for this? 

Thanks.

**Comment by jpalardy** [comment]
Do you think it's related to your environment? Or maybe another plugin? I can't seem to reproduce the problem.

Here's what I did:

* I opened 2 terminals
* opened tmux in one, got the target with `echo $TMUX_PANE`
* in the other terminal, I typed `vim some.txt`
* I opened a few lines, keep my cursor on the last line, typed in some words
* C-c C-c, it asked for the socket and target, entered those
* text went to target, no error messages

Do you have a recipe for me to reproduce?

**Comment by skrisna** [comment]
I tried to localize the error. I moved to a linux machine running vim 7.4. I set the .vimrc to 

""""""""""""""""""""""
set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
let path='~/.vim/bundle'
call vundle#begin(path)
Plugin 'gmarik/Vundle.vim'
Plugin 'jpalardy/vim-slime'
call vundle#end()

colorscheme torte
syntax on
filetype plugin indent on
""""""""""""""""""""""

With this minimum setting, I am no longer getting an error. It is probably some setting in my earlier .vimrc that was causing the problem but I am not sure what exactly. 

This should work for now. Also, I mapped <c-c><c-c> to <c-j><c-j> because even a slight delay in the typing of <c-c><c-c> would result in something like-
![screenclip](https://cloud.githubusercontent.com/assets/2131842/7245580/7693c7cc-e7bb-11e4-8ed4-8e7d9c714d46.png)

Thanks.

**Comment by jpalardy** [comment]
The C-c C-c mapping exists for historical reasons (that's what SLIME uses on Emacs). It's also easy to type.
