### ISSUE TITLE
Unwanted let prefixing when using vim slime with Haskell

### ISSUE THREAD

**Issue by lpil** [jpalardy/vim-slime#85]
Hello!

I'm trying to use vim slime with Haskell and the Tidal library to programatically make drum beats live. I wish to evaluate expressions like these:

```haskell
d1 <- dirtStream

d1 $ sound "bd"
```

But when I try to do with with vim-slime, I get this:

```haskell
let d1 <- dirtStream

let d1 $ sound "bd"
```

Neither of these expressions are valid.

How do I work around this?

Thanks,
Louis

**Comment by jpalardy** [comment]
I'll refer to the Haskell plugin authors:

@ethagnawl @romeovs @dbeecham @werbitt @dariusf @jdiez17 thoughts?

**Comment by lpil** [comment]
Thanks Jonathan

**Comment by dbeecham** [comment]
What is the rationale for using not_prefixable_keywords? I'm trying to wrap my mind around when to prepend 'let'.

Do we need to search for an equal sign (=) before prepending?

This needs to be prepended
    f x = 3*x

but not this
    f <- x

and not this
    x

**Comment by ethagnawl** [comment]
@lpil Are you able to wrap those expressions in a `do`? That would solve the `let` problem.

**Comment by lpil** [comment]
No, I am not I'm afraid.

**Comment by lpil** [comment]
This is still quite the show stopper for me here. If we cannot fix this feature in the near future, is there at least a way to disable it?

**Comment by dbeecham** [comment]
Yes, in ftplugin/haskell/slime.vim, in _EscapeText_haskell, comment out the
line with 'Perhaps_prepend_let'.

lör 21 nov 2015 15:20 Louis Pilfold <notifications@github.com> skrev:

**Comment by lpil** [comment]
Thank you.
