### ISSUE TITLE
IPython 4's auto indentation breaks pasting

### ISSUE THREAD

**Issue by languitar** [jpalardy/vim-slime#86]
IPython (at least version 4) auto-indents after colons. This prevents that sent blocks of code are syntactically correct. I don't know whether there is some way for vim-slime to fix this, but it would be nice if this could work with default settings.

**Comment by languitar** [comment]
Ok, I didn't see that there is a special ipython mode. This mode is missing in the help page of the plugin.

**Comment by jpalardy** [comment]
The bottom of the main README links to [Python's README](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python).

As someone new to this project, what was missing?

**Comment by languitar** [comment]
The entry in the help page ;)

**Comment by jpalardy** [comment]
Which one is that? The :help page?

In that case, could you send me a PR.

**Comment by languitar** [comment]
Yes, the `:help` page.

Maybe one could generalize the specific ipython hack to let the user define certain characters to send before and after the text to send on a per-buffer basis, to make things more flexible? So for ipython one would set something like `slime_send_before` to `%cpaste<newline>` and `slime_send_after` to `--<newline>`. That way, the same mechanism can also be used for environments that weren't envisioned before.

This also relates to issue #88 for buffer-local assignment.

**Comment by languitar** [comment]
These variables cut be set using the filetype plugin mechanism of vim.

**Comment by jpalardy** [comment]
Old issue, re-open if needed.
