### ISSUE TITLE
Handle trailing newlines

### ISSUE THREAD

**Issue by languitar** [jpalardy/vim-slime#87]
When I send some function definition to IPython, I need two trailing newlines without spaces before to start the interpretation of the input in IPython. Currently, multiple newlines are always condensed to a single newline, when sending to tmux. This prevents the correct execution of the code without manually moving to the IPython shell and pressing enter. I would either expect that multiple newlines already contained in the lines to send are preserved, or their needs to be a setting to configure the amount of newlines to send after the target text.

**Comment by jpalardy** [comment]
if you're using the IPython mode now, is it fixing this?

**Comment by languitar** [comment]
For my special case yes. But in the general case, I don't know whether it is a good idea to strip trailing newlines. There might be valid use cases.

**Comment by jpalardy** [comment]
Fixed: glad to hear it.

If you find a use case, open an issue :-)

**Comment by languitar** [comment]
Thanks.
