### ISSUE TITLE
Allow buffer-local option for ipython mode

### ISSUE THREAD

**Issue by languitar** [jpalardy/vim-slime#88]
I would like to control for individual buffers, whether they need to use ipython mode or not.

**Comment by jpalardy** [comment]
Right now the IPython mode is controlled through a [global variable](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim#L3). It wouldn't be too hard to chain a conditional on a buffer variable `b:slime_python_ipython`.

In practice, when inside a specific buffer, how will you toggle the mode?

Alternatively, you could have another key mapping that:

- unsets the global variable
- sends the text
- resets the global variable

but that's not super-elegant.

**Comment by languitar** [comment]
> In practice, when inside a specific buffer, how will you toggle the mode?

I would like to set the variable with an `ftplugin` so that all python files automatically get this option, but other languages do not get it.

**Comment by jpalardy** [comment]
I'm sorry, we're commenting in a few issues at the same time. Can you walk me through your use cases? (I want to make sure I really understand the problem)

**Comment by languitar** [comment]
Right. Maybe I have several different file types open in different buffers. I want to connect them to multiple tmux panes. For some of these buffers, setting `g:slime_python_ipython` might be necessary because they are connected to ipython. For other buffers this option might not be necessary (maybe because I am sending code snippets to an IRC conversation in weechat or whatever).

**Comment by languitar** [comment]
Or maybe thinking the other way around: certain transformations applied to the text sent to e.g. tmux, could be tied to the slime connection.

**Comment by jpalardy** [comment]
Although the `g:slime_python_ipython` is a global variable -- it doesn't affect all buffers.

For example, when you send text, vim-slime checks what filetype you sent the text from and runs it onlu through the specific filter. As such, python files get the python filter, etc.

Is that not the behavior you see?

**Comment by languitar** [comment]
Oh right, I missed that.

**Comment by jpalardy** [comment]
I thought you might be mixing python and ipython buffers.

**Comment by languitar** [comment]
Ok. I understand.

The only thing that see from a design point of view is that the filters to apply not only relate to the file type, but also to the connection information. If I connect a python file to my mcabber session (inside tmux), I do not want to have the ipython transformation, but a transformation where the message starts with `/msay begin` etc.

If the transformations were maintained inside the connection information, and multiple connection could be open in parallel, then some very interesting use cases could be possible. E.g. I could create one key mapping to send to ipython and a second one to send to mcabber or weechat etc. That way it would be very easy to create code and on parallel discuss this code with others without ever having to use the clipboard manually.

**Comment by jpalardy** [comment]
This is all possible today, with some tweaking.

All buffers have their own "connection config". With different mappings, you could overwrite `b:slime_config` before invoking the slime binding.

- send text to python, slime gets configured
- (save b:slime_config, set to null)
- send text to mcabber, slime gets configured
- now you have the saved b:slime_config from the python connection, and b:slime_config currently points to mcabber … if you swap those before you send to slime, you can send to the connection you want

You would, essentially, build a channel-selector in front of vim-slime.

**Comment by languitar** [comment]
Ok, that's nice. But this lacks the ability so select the transformations to apply  as they are not contained in the `slime_config`.

**Comment by jpalardy** [comment]
2-year old, closing.
