### ISSUE TITLE
tmux 2.2

### ISSUE THREAD

**Issue by tcbtcb** [jpalardy/vim-slime#91]
Not sure if this qualifies as an issue even, but I downloaded the freshest version of tmux only for kicks and since I use tmux about 95% for sliming with vim I tried it and the panes (selected in the usual way via :SlimeConfig) were not communicating. No text was pasted. I uninstalled and went back to the standard tmux for debian Jessie and all is back to normal. I'll set up a virtual machine and investigate more, but I was just wondering if anyone was using the brand newest version of tmux with vim-slime? 

After I look into this more I will report back, but was wondering if anyone else had any experience.

**Comment by jpalardy** [comment]
Ok, let me know.

**Comment by vainikkaj** [comment]
I can verify that vim-slime does not work with Tmux 2.2.
For me, Vim corrupts terminal and becomes unresponsive when trying to use :SlimeSend.
Running on Ubuntu 15.10, Vim 7.4 and Tmux 2.2.

Please let me know if addiotional info is needed. Thanks for a great plugin.

**Comment by jpalardy** [comment]
I've looked at the [changelog](https://raw.githubusercontent.com/tmux/tmux/master/CHANGES) and didn't see anything that jumped at me.

On homebrew, the latest is tmux 2.1. I checked on ubuntu (docker image) and it's even older… 2.2 was released in April, that's pretty bleeding edge.

What do you think?

**Comment by vainikkaj** [comment]
Yes, I agree that 2.2 is quite new, but eventually it will become available in all platforms.

However, after fiddling around more with this, I found that tmux 2.2 works with following config:
 `let g:slime_paste_file = "$HOME/.slime_paste"`
Perhaps this is related to the change **Support for TMPDIR has been removed.  Use TMUX_TMPDIR instead.**

For me this is sufficient workaround and this issue can closed.

**Comment by jpalardy** [comment]
vim-slime itself doesn't explicitly use TMPDIR. I'll test more when 2.2 rolls out.

**Comment by sboysel** [comment]
I can confirm that the workaround by @vainikkaj works for tmux 2.2.  Thanks!

**Comment by jpalardy** [comment]
sounds like some tmux 2.2 brokenness… sigh.

**Comment by jpalardy** [comment]
as per commit, g:slime_paste is now the default, so tmux 2.2 works without config
