### ISSUE TITLE
Feature for supporting windows using ConEmu

### ISSUE THREAD

**Issue by djhaskin987** [jpalardy/vim-slime#92]
ConEmu is a program that can attach multiple consoles into one window. It's kind of like GNU screen, but more windowsy.

Something I've already gotten to work is vim can send *some* text, but I haven't gotten it to send carriage returns to the terminal window yet:

system(shellescape("C:\\Program Files\\ConEmu\\ConEmu\\ConEmuC64.exe") . "/GuiMacro:0 print: foo")

That command sends the string "foo" to the first ConEMU window.

A similar plugin for sublime text is here --> https://github.com/fbehrens/sublime_ExternalREPL
I'd just love to see something like this for vim. Thanks! :+1:

**Comment by jpalardy** [comment]
Hi there,

I'm not looking to add more code and/or complexity to vim-slime right now. And, unfortunately, vim-slime wasn't designed to easily approach plugins either…

Sorry.
