### ISSUE TITLE
Support for neovim

### ISSUE THREAD

**Issue by qiuwei** [jpalardy/vim-slime#93]
Neovim has a built in terminal emulator and has asynchronous feature.

**Comment by jpalardy** [comment]
Hi there,

I don't use neovim. If you have specific ways in which it's failing and suggestions, I'm open to consider it.

**Comment by lpil** [comment]
This plugin works with neovim just fine, I think @qiuwei is suggesting making use of neovim's built in terminal emulator to drop the tmux dependency.

I personally think this should be an entirely new plugin.
