### ISSUE TITLE
Function to clear REPL console 

### ISSUE THREAD

**Issue by meriops** [jpalardy/vim-slime#94]
It would be nice to have a function and key map to clean the REPL console. Something like sending `system(clear)` to the REPL...

**Comment by jpalardy** [comment]
I've been using something like that:

    nmap <c-c><c-l> :SlimeSend0 "^L"<CR>

send ctrl-L to the REPL. You can put it in your `.vimrc` and you're good to go. (change the mapping as needed)

**Comment by meriops** [comment]
This does the job, indeed. Although for some reason, I had to tweak that to:
`nmap <c-c><c-l> :SlimeSend0 "<c-l>"<CR>` 
Thanks.

**Comment by jpalardy** [comment]
Oh… that's probably because I typed mine as <ctrl-v><ctrl-l>.

Good times :-)
