### ISSUE TITLE
Help with defining a ftplugin for Stata do-files

### ISSUE THREAD

**Issue by ewancarr** [jpalardy/vim-slime#96]
I'm trying to write a ftplugin for [Stata](http://www.stata.com/) do-files. I'm new to Vimscript, so this is probably a basic question, but any assistance would be greatly appreciated. 
#### The problem

I need to escape lines that end in `//` or continuation lines, where a long command is spread over multiple lines ending in `///`.

For example, a do-file might contain:

``` stata
gen x = 1 // Set x to 1 <-- Comment

keep var1 var2 var3 /// <-- Continuation
     var4 var5 var6
```

And I need to escape this, to produce:

``` stata
gen x = 1

keep var1 var2 var3 var4 var5 var6
```
#### What I've tried

I've created a new subfolder in `.../ftplugin/stata` with the file `slime.vim`. I've tried to convert one of the existing solutions, e.g:

``` vimscript
function! _EscapeText_stata(text)
    let trimmed = substitute(a:text, "\/\/.*$", "\n", "")
    return [trimmed]
endfunction
```

But **I can only manage to escape a single line** -- anything after the first match of `\/\/.*$` is removed. Could anyone point me in the right direction?

Many, many thanks!

**Comment by jpalardy** [comment]
Unfortunately, this is beyond my Vimscript abilities.

**Comment by ewancarr** [comment]
Thanks for the reply.

After further trial and error, this is easier than I thought. I'm using the following `slime.vim` in the `/ftplugin/stata/` folder, and it appears to work. 

~~~vimscript
function! _EscapeText_stata(text)
	let remove_comments = substitute(a:text, '///\s*\n', " ", "g")
	return remove_comments
endfunction
~~~

I'll continue to test this, but it's working for now.
