### ISSUE TITLE
slime inserting %cpaste and -- when pasting to python

### ISSUE THREAD

**Issue by Sseziwa** [jpalardy/vim-slime#98]
If I turn off slime_python_ipython the slurped text is incorrectly formatted, eg:

```
def delete():
     m.delete_library('smukasa.alphas')
```

becomes

```
>>> def delete():    m.delete_library('smukasa.alphas')
...
```

Turning slime_python_ipython on correctly preserves the new line, but now everything is surrounded by an annoying %cpaste and --

> >>> %cpaste
> File "<stdin>", line 1
> %cpaste
> ^
> SyntaxError: invalid syntax
> >>> def delete():
> ...     m.delete_library('smukasa.alphas')
> ...
> >>> --
> File "<stdin>", line 1
>  --
> ^
> SyntaxError: invalid syntax
> 

is there any way to fix this?

**Comment by Sseziwa** [comment]
Ahh, yes it works better with ipython.  So is there a flag that would work with python?

**Comment by jpalardy** [comment]
I'm not a Python REPL specialist, this [disclaimer](https://github.com/jpalardy/vim-slime/tree/master/ftplugin/python) seem to say that the normal python REPL won't play nice.

**Comment by Sseziwa** [comment]
I can live with ipython, thanks.
